_ga_where="set";_a_fields=["id","text"];var bkg_page=chrome.extension.getBackgroundPage(),dy_bkg=bkg_page.dy_bkg,dy_settings=bkg_page.dy_settings,dy_engine=bkg_page.dy_engine,dy_rules=bkg_page.dy_rules,dy_tabman=bkg_page.dy_tabman;
$(function(){$("#help_holder").load(chrome.i18n.getMessage("helpFile"),function(){$("#about_holder").load(chrome.i18n.getMessage("aboutFile"),function(){function t(a,c){var d=dy_settings.categorys[a],p=d.name,h=$("#dy_"+a+" "+(c||".content"));$("#dy_"+a+" header").html("<h1>"+p+"</h1>");$(".menu a[href=#"+a+"]").text(p);for(var p=dy_engine.is_native,b="",u=[],e=0,f=d.sections.length;e<f;++e){var l=d.sections[e],b=b+"<section>";l.name&&(b+="<h3>"+l.name,l.tip&&(b+='<span class="simptip-position-top" data-tooltip="'+
l.tip+'">?</span>'),b+="</h3>");l.description&&(b+="<div>"+l.description+"</div>");for(var k=0,n=l.items.length;k<n;++k){var m=l.items[k],g=dy_settings.items[m];if(!g.native_only||p)switch(g.type){case "button":var q="<button"+(g.onclick?' id="optbtn_'+m+'"':"")+">"+g.buttonText+"</button>",b=b+("<div>"+(g.label?'<label>\t\t\t\t\t\t\t\t<span class="field_label">'+g.label+"</span>"+q+"</label>":q)+(g.moreText?"<span>"+g.moreText+"</span>":"")+"<div>");g.onclick&&u.push(m);break;case "bool":b+='<div class="checkbox">\t\t\t\t\t\t<label>\t\t\t\t\t\t\t<input id="'+
m+'"'+(!0==g.value?' checked="checked"':"")+' type="checkbox">\t\t\t\t\t\t\t<span style="margin-left:5px">'+g.label+"</span>\t\t\t\t\t\t</label>";g.tip&&(b+='<span class="simptip-position-top" data-tooltip="'+g.tip+'">?</span>');b+="</div>";break;case "string":b+='<div>\t\t\t\t\t\t<label>\t\t\t\t\t\t\t<span class="field_label">'+g.label;g.tip&&(b+='<span class="simptip-position-top" data-tooltip="'+g.tip+'">?</span>');b+='</span>\t\t\t\t\t\t\t<input id="'+m+'" value="'+g.value+'"'+(g.placeholder?
' placeholder="'+g.placeholder+'"':"")+' type="text">\t\t\t\t\t\t</label>\t\t\t\t\t\t</div>';break;case "int":b+='<div>\t\t\t\t\t\t<label>\t\t\t\t\t\t\t<span class="field_label">'+g.label;g.tip&&(b+='<span class="simptip-position-top" data-tooltip="'+g.tip+'">?</span>');b+='</span>\t\t\t\t\t\t\t<input id="'+m+'" min="'+g.min+'" max="'+g.max+'" value="'+g.value+'" type="number" >\t\t\t\t\t\t</label>\t\t\t\t\t\t<span>('+g.min+"-"+g.max+")</span>\t\t\t\t\t\t</div>";break;case "select":b+='<div><label><span class="field_label">'+
g.label;g.tip&&(b+='<span class="simptip-position-top" data-tooltip="'+g.tip+'">?</span>');b+='</span>\t\t\t\t\t\t<select id="'+m+'">';for(m=0;m<g.options.length;++m)b+="<option>"+g.options[m]+"</option>";b+="</select></label></div>"}}b+="</section>"}$(h).append(b);$(h).find("section").each(function(){var b=-1;$(this).find(".field_label").each(function(){var a=$(this).width();a>b&&(b=a)});$(this).find(".field_label").css("width",b+5)});for(e=0;e<u.length;++e)m=u[e],$("#optbtn_"+m).click(dy_settings.items[m].onclick)}
function v(a,c,d,p,e){return'<div class="'+(d?"cell_active":"cell_inactive")+'"><img src="../icons/tick.png"/></div>'}function w(a,c,d){a.setSelectionModel(new Slick.RowSelectionModel);var p=new Slick.RowMoveManager({cancelEditOnDrag:!0});p.onBeforeMoveRows.subscribe(function(a,b){for(var c=0;c<b.rows.length;c++)if(b.rows[c]==b.insertBefore||b.rows[c]==b.insertBefore-1)return a.stopPropagation(),!1;return!0});p.onMoveRows.subscribe(function(p,b){var e=[],h,f=b.rows,l=b.insertBefore;f.sort(function(b,
a){return b-a});for(var k=0;k<f.length;k++)e.push(c[f[k]]);f.reverse();h=c.splice(l,c.length);for(k=0;k<f.length;k++){var n=f[k];n<l?c.splice(n,1):h.splice(n-l,1)}l=c.length;c.push.apply(c,e.concat(h));d();e=[];for(k=0;k<f.length;k++)e.push(l+k);a.setSelectedRows(e);a.invalidateAllRows();a.render()});a.registerPlugin(p)}function x(a,c){return c-a}function y(){$(".menu a[href="+(window.location.hash||"#general")+"]").click()}chrome.runtime.onMessage.addListener(function(a,c,d){switch(a.cmd){case "font_size":$("#font_size").blur(),
setUIFontSize(a.data)}});$.fn.textWidth=function(){var a=$(this).children(),c=$('<span style="display: inline-block;" />');a.wrap(c);c=a.parent().width();a.unwrap();return c};"undefined"===typeof trim_str&&(trim_str=function(a){return a?a.trim():""});var h,f=1,n=[{id:f++,name:chrome.i18n.getMessage("headExtFilterEnable"),field:"filter_links",toolTip:chrome.i18n.getMessage("tipExtFilterEnable"),editor:Slick.Editors.Checkbox,formatter:v,sortable:!0,behavior:"selectAndMove",cannotTriggerInsert:!0},{id:f++,
name:chrome.i18n.getMessage("headExtFilterCaption"),field:"caption",editor:Slick.Editors.Text,sortable:!0,behavior:"selectAndMove",width:150},{id:f++,name:chrome.i18n.getMessage("headExtFilterRefName"),field:"int_name",toolTip:chrome.i18n.getMessage("tipExtFilterRefName"),editor:Slick.Editors.Text,sortable:!0,behavior:"selectAndMove",width:150},{id:f++,name:chrome.i18n.getMessage("headExtFilterExts"),field:"exts",editor:Slick.Editors.Text,sortable:!0,behavior:"selectAndMove",width:250}],e,f=1,f=[{id:f++,
name:chrome.i18n.getMessage("headRulesActive"),field:"active",toolTip:chrome.i18n.getMessage("tipRulesActive"),editor:Slick.Editors.Checkbox,formatter:v,sortable:!1,behavior:"selectAndMove",cannotTriggerInsert:!0},{id:f++,name:chrome.i18n.getMessage("headRulesAsFilter"),field:"as_filter",toolTip:chrome.i18n.getMessage("tipRulesAsFilter"),editor:Slick.Editors.Checkbox,formatter:v,sortable:!1,behavior:"selectAndMove",cannotTriggerInsert:!0},{id:f++,name:chrome.i18n.getMessage("headRulesCaption"),field:"caption",
editor:Slick.Editors.Text,sortable:!1,behavior:"selectAndMove",width:110},{id:f++,name:chrome.i18n.getMessage("headRulesRefName"),field:"int_name",toolTip:chrome.i18n.getMessage("tipRulesRefName"),editor:Slick.Editors.Text,sortable:!1,behavior:"selectAndMove",width:110},{id:f++,name:chrome.i18n.getMessage("headRulesCondition"),field:"condition",editor:Slick.Editors.Text,sortable:!1,behavior:"selectAndMove",width:220},{id:f++,name:chrome.i18n.getMessage("fieldFolder"),field:"folder",editor:Slick.Editors.Text,
sortable:!1,behavior:"selectAndMove"},{id:f++,name:chrome.i18n.getMessage("fieldNaming"),field:"naming",editor:Slick.Editors.Text,sortable:!1,behavior:"selectAndMove",width:110}];$(window).unload(function(){dy_settings.commit()});document.oncontextmenu=function(a){var c=a.target.nodeName.toLowerCase();if("input"!=c&&"textarea"!=c||a.target.disabled)return!1};do_i18n();(function(){$(".menu a").click(function(a){$(".mainview > *").removeClass("selected");$(".menu li").removeClass("selected");setTimeout(function(){$(".mainview > *:not(.selected)").css("display",
"none")},100);$(a.currentTarget).parent().addClass("selected");a=($(a.currentTarget).attr("href")||"#").replace("#","#dy_");"#dy_about"==a&&0==$(".share_buttons").children().length&&($("#version-number").text(chrome.runtime.getManifest().version),add_share_buttons($(".share_buttons")));var c=$(a);c.css("display","block");setTimeout(function(){c.addClass("selected")},0);setTimeout(function(){$("body")[0].scrollTop=0},200);dy_settings.commit()})})();t("general");t("interface");t("rules");$("#dy_panic_reset").click(function(){confirm(chrome.i18n.getMessage("confirmReset"))&&
($("#dy_panic_reset").prop("disabled",!0),dy_bkg.reset())});(function(){for(var a in dy_settings.items){var c=dy_settings.items[a],d=$("#"+a);switch(c.type){case "bool":d.attr("checked",c.value);d.change(function(){dy_settings.set(this.id,this.checked);"undefined"!==typeof gaTrackCustom&&gaTrackCustom("sets","changed",this.id+"["+this.checked+"]")});break;case "string":d.val(c.value);d.change(function(){var a=(this.value||"").trim();dy_settings.set(this.id,a);"undefined"!==typeof gaTrackCustom&&gaTrackCustom("sets",
"changed",this.id+"["+a+"]");a!=this.value&&(this.value=a)});break;case "int":d.val(c.value);d.change(function(a){a=parseInt(this.value);dy_settings.set(this.id,a);"undefined"!==typeof gaTrackCustom&&gaTrackCustom("sets","changed",this.id,a)});break;case "select":d.val(c.options[c.value]),d.change(function(){var a=parseInt(this.selectedIndex);dy_settings.set(this.id,a);if("undefined"!==typeof gaTrackCustom)try{gaTrackCustom("sets","changed",this.id+"["+dy_settings.items[this.id].options[a]+"]")}catch(c){}})}}})();
$("input[type=number]").numeric({decimal:!1,negative:!1});$("#dy_opendy").click(function(){dy_tabman.open_ui({activate:!0})});var s=chrome.i18n.getMessage("translateContributors");s?$("#translation_info").html("This "+chrome.i18n.getMessage("uilangName")+" language version is translated by "+s+("."==s[s.length-1]?"":".")+' Please help us improve <span id="btn_translation_site" style="cursor:pointer" class="rainbow">translation</span>.'):$("#translation_info").html('Help us with <span id="btn_translation_site" style="cursor:pointer" class="rainbow">translation</span>!');
$("#btn_translation_site").click(function(){chrome.tabs.create({url:"http://translate.chronodownloader.net"})});$(".simpletable tbody").hide();$(".simpletable thead").click(function(){$(this).next().toggle()});var q=dy_rules.getLinkFilters(),r=dy_rules.getRules();h=new Slick.Grid("#cats_grid",q,n,{enableColumnReorder:!0,enableAddRow:!0,editable:!0,autoEdit:!1});h.registerPlugin(new Slick.AutoTooltips({enableForHeaderCells:!0,enableForCells:!0,maxToolTipLength:256}));if(!dy_engine.is_native)for(n=
0;n<f.length;++n)if("folder"==f[n].field){f.splice(n,1);break}e=new Slick.Grid("#rules_grid",r,f,{enableColumnReorder:!0,enableAddRow:!0,editable:!0,autoEdit:!1});e.registerPlugin(new Slick.AutoTooltips({enableForHeaderCells:!0,enableForCells:!0,maxToolTipLength:256}));w(h,q,dy_rules.on_filters_change);w(e,r,dy_rules.on_rules_change);$("#cats_grid").on("blur","input",function(){setTimeout(function(){var a=h.getEditorLock();a.isActive()&&0==$("#cats_grid :focus").length&&a.commitCurrentEdit()})});
$("#rules_grid").on("blur","input",function(){setTimeout(function(){var a=e.getEditorLock();a.isActive()&&0==$("#rules_grid :focus").length&&a.commitCurrentEdit()})});h.onCellChange.subscribe(dy_rules.on_filters_change);e.onCellChange.subscribe(dy_rules.on_rules_change);h.onAddNewRow.subscribe(function(a,c){var d=jQuery.extend(!0,{},dy_rules.def_link_filter);$.extend(d,c.item);dy_rules.add_filter(d);h.updateRowCount();h.invalidateRow(q.length-1);h.render()});h.onKeyDown.subscribe(function(a,c){var d=
h.getSelectedRows().slice(0);if(46==a.keyCode&&!h.getEditorLock().isActive()&&0<d.length&&confirm(chrome.i18n.getMessage("confirmRemoveExtFilter"))){d.sort(x);for(var e=0;e<d.length;++e)q.splice(d[e],1);dy_rules.on_filters_change();h.setSelectedRows([]);h.invalidate()}});e.onAddNewRow.subscribe(function(a,c){var d=jQuery.extend(!0,{},dy_rules.def_rule);$.extend(d,c.item);dy_rules.add_rule(d);e.updateRowCount();e.invalidateRow(r.length-1);e.render()});e.onKeyDown.subscribe(function(a,c){var d=e.getSelectedRows().slice(0);
if(46==a.keyCode&&!e.getEditorLock().isActive()&&0<d.length&&confirm(chrome.i18n.getMessage("confirmRemoveRule"))){d.sort(x);for(var f=0;f<d.length;++f)r.splice(d[f],1);dy_rules.on_rules_change();e.setSelectedRows([]);e.invalidate()}});h.onSort.subscribe(function(a,c){var d=c.sortCol.field,e=c.sortAsc;q.sort(function(a,b){var c=a[d]<b[d]?-1:1;return e?c:-c});dy_rules.on_filters_change();h.invalidateAllRows();h.render()});e.onSort.subscribe(function(a,c){var d=c.sortCol.field,f=c.sortAsc;r.sort(function(a,
b){var c=a[d]<b[d]?-1:1;return f?c:-c});dy_rules.on_rules_change();e.invalidateAllRows();e.render()});h.enableColumnFit();e.enableColumnFit();window.onhashchange=y;y();0.5>Math.random()?$("#adwrap").append("<iframe src='http://www.chronodownloader.net/versions-page.html' framespacing='0' frameborder='no' scrolling='no' width='160' height='601' allowtransparency='true'></iframe>"):$("#adwrap").append("<iframe src='http://www.chronodownloader.net/home-page.html' framespacing='0' frameborder='no' scrolling='no' width='160' height='601' allowtransparency='true'></iframe>")})})});
