var dy_ui={tabid:-1,uilayout:null};
(function(){function f(){$("#dy_searchbox input").val("").change()}function e(a,b){var d=document.getElementsByTagName("head")[0],n=document.createElement("script");n.type="text/javascript";n.src=a;n.onreadystatechange=b;n.onload=b;d.appendChild(n)}function g(){function a(){$("#bg-chooser-wrap").removeClass("disableme");var a=dy_settings.get("bg_image_url");a&&("#"==a[0]?$("#dy_bg").css("background-color",a):$("#dy_bg").css("background-image",'url("'+a+'")'));a=dy_settings.get("bg_image_opacity");
$("#dy_bg").css("opacity",a).css("-webkit-filter","blur("+dy_settings.get("bg_image_blur")+"px)");$("body").toggleClass("bgtransparent",0<a);$("#dy_bg").show()}$(b.BtnChangeBG).click(function(a){$(this).dropdown("show");a.stopPropagation()});$(".dropdown").on("show",function(a,c){$(b.TotalWrap).addClass("not-clickable")}).on("hide",function(a,c){$(b.TotalWrap).removeClass("not-clickable")});$("#dropdown-change-bg").on("show",function(a,b){p()}).on("hide",function(a,b){$("#bg-provided").empty()});
$("#bg-weburl-btn").click(function(){var a=$("#bg-url-input"),b=(a.val()||"").trim(),c=0==b.indexOf("file:///"),f=0==b.indexOf("data:image/");c||f||validateURL(b)?(c?b=b.replace(/\\/g,"/"):f||/^((https?|ftp):\/\/)/.test(b)||a.val(b="http://"+b),$("#dy_bg").css("background-image",'url("'+b+'")').css("background-color",""),dy_settings.set("bg_image_url",b)):show_error_field(a)});$("#bg-ccolor").colorPicker({onColorChange:function(a,b){$("#dy_bg").css("background-color",b).css("background-image","");
dy_settings.set("bg_image_url",b)}});$("#bg-opacity").val(dy_settings.get("bg_image_opacity")).bind("input",function(){$("#dy_bg").css("opacity",this.value);dy_settings.set("bg_image_opacity",this.value);$("body").toggleClass("bgtransparent",0<this.value)});$("#bg-blur").val(dy_settings.get("bg_image_blur")).bind("input",function(){$("#dy_bg").css("-webkit-filter","blur("+this.value+"px)");dy_settings.set("bg_image_blur",this.value)});$("#dropdown-change-bg .close-button").click(function(){$(b.BtnChangeBG).dropdown("hide")});
dy_bkg.file_access?$("#mytip-url").attr("data-tooltip",chrome.i18n.getMessage("tipBGURLHasFileAccess")):$("#mytip-url").attr("data-tooltip",chrome.i18n.getMessage("tipBGURLNoFileAccess")).click(function(){chrome.tabs.create({url:"http://faq.chronodownloader.net/index.php?action=artikel&cat=7&id=12"})});dy_settings.get("bg_image_everset")||$(b.BtnChangeBG).one("click",function(a){dy_settings.set("bg_image_everset",!0);$(this).find("img").removeClass("blink-anim");"undefined"!==typeof gaTrackCustom&&
gaTrackCustom("ext_stat","ui","bg-first-clicked")}).find("img").addClass("blink-anim");var c=dy_settings.get("bg_image_enable");$("#bg-enable").prop("checked",c).change(function(){this.checked?a():($("#bg-chooser-wrap").addClass("disableme"),$("#dy_bg").hide(),$("body").removeClass("bgtransparent"));dy_settings.set("bg_image_enable",this.checked);"undefined"!==typeof gaTrackCustom&&gaTrackCustom("ext_stat","ui",this.checked?"bg-enabled":"bg-disabled")});c&&a()}function p(){for(var a="",b=1;8>=b;++b)a+=
'<span class="bg-preview"><img src="../icons/bg/'+b+'-s.jpg"/></span>';$("#bg-provided").html(a);$(".bg-preview img").click(function(){var a=this.src.replace("-s.jpg",".jpg");$("#dy_bg").css("background-image",'url("'+a+'")').css("background-color","");dy_settings.set("bg_image_url",a)})}var b={TotalWrap:"#dy_tot_wrap",BtnAdd:"#dy_tbar_add",BtnStart:"#dy_tbar_start",BtnStartA:"#dy_tbar_startall",BtnPause:"#dy_tbar_pause",BtnPauseA:"#dy_tbar_pauseall",BtnRestart:"#dy_tbar_restart",BtnTrash:"#dy_tbar_trash",
BtnDelete:"#dy_tbar_delete",BtnClear:"#dy_status_btn_clear",BtnSort:"#dy_status_btn_sort",BtnOptions:"#dy_tbar_options",BtnHelp:"#dy_tbar_help",BtnChangeBG:"#dy_status_btnbg",LNavFilters:"#dy_lnav_filters",LNavBtnRecycled:"#dy_lnavbtn_recycled",LNavBtnRecycled_:"dy_lnavbtn_recycled",LNavBtnConfig:"#dy_lnavbtn_config",LNavBtnAbout:"#dy_lnavbtn_about",Menu:"#dy_menu"};dy_ui.enable_toolbar=function(a){a?($(b.BtnStart).removeAttr("disabled"),$(b.BtnPause).removeAttr("disabled"),$(b.BtnRestart).removeAttr("disabled"),
$(b.BtnTrash).removeAttr("disabled"),$(b.BtnDelete).removeAttr("disabled")):($(b.BtnStart).attr("disabled",!0),$(b.BtnPause).attr("disabled",!0),$(b.BtnRestart).attr("disabled",!0),$(b.BtnTrash).attr("disabled",!0),$(b.BtnDelete).attr("disabled",!0))};dy_ui.save_selected_filter=function(){var a=$(b.LNavFilters+" li").index($(b.LNavFilters+" li.selected"));localStorage.current_filter=a};dy_ui.load_selected_filter=function(){var a=parseInt(localStorage.current_filter);if(isNaN(a)||!isFinite(a)||0>a)a=
0;(a=$(b.LNavFilters+" li")[a])&&$(a).find("a").click()};dy_ui.refresh_display_filters=function(){var a=dy_rules.get_display_filters(),c=$(b.LNavFilters+" li.dd-item a");c.shift();if(c.length!=a.length)alert("error: lias.length!=disp_filters.length");else for(var d=0;d<c.length;++d)$(c[d]).attr("filter_str",a[d].filter),$(c[d]).text(a[d].caption)};dy_ui.reset_filter_all=function(){$("#filterTaskAll").click()};var r=0;dy_ui.rebuild_display_filters=function(a){var c=dy_rules.get_display_filters(),d=
"<ul class='dd-list menu'>",e=chrome.i18n.getMessage("ruleAllTasks"),d=d+("<li class='dd-item"+(a?"":" selected")+"'><a id='filterTaskAll' filter_str='true'>"+e+"</a></li>");!0!=a&&dy_tasktb.set_custom_filter("true");var g;a=0;for(e=c.length;a<e;++a)c[a].indent<g?d+="</li></ul></li>":c[a].indent==g?d+="</li>":void 0!=g&&(d+="<ul class='dd-list'>"),d+="<li class='dd-item' data-id="+c[a].id+"><a filter_str='"+c[a].filter+"' class='dd-handle'>"+c[a].caption+"</a>",g=c[a].indent;d=(0==g?d+"</li>":d+"</li></ul></li>")+
"</ul>";$(b.LNavFilters).html(d);$(b.LNavFilters).nestable({maxDepth:2,listNodeName:"ul",expandBtnHTML:"",collapseBtnHTML:"",dragClass:"dd-dragel menu"});$(b.LNavFilters+" a").click(function(a){a.preventDefault();$(a.currentTarget).parent().hasClass("selected")||(dy_settings.get("clear_search")&&f(),$(b.LNavBtnRecycled).parent().hasClass("selected")&&($(b.BtnAdd).show(),$(b.BtnStart).show(),$(b.BtnStartA).show(),$(b.BtnPause).show(),$(b.BtnPauseA).show(),$(b.BtnTrash+" img")[0].src="../icons/toolbar/trash.png",
$(b.BtnTrash).addClass("action_recycle").data("dtitle",chrome.i18n.getMessage("tipBtnRecycle"))),$(".menu li").removeClass("selected"),$(a.currentTarget).parent().addClass("selected"),dy_tasktb.set_custom_filter($(a.currentTarget).attr("filter_str")),dy_ui.save_selected_filter(),2>r?r++:ui_notify.show_tip("tip_taskfilter",6))})};var s="";dy_ui.toggle_details_panel=function(a){var b=dy_ui.uilayout.center.children.table_layout;a?b.state.east.isSliding||b.slideOpen("east"):b.close("east")};dy_ui.setup=
function(a){function c(){!dy_bkg.popup_dlist_open&&dy_engine.numDownloading()&&chrome.runtime.sendMessage({cmd:"poll_progress"});setTimeout(c,250)}(function(){dy_ui.enable_toolbar(!1);$(b.BtnAdd).click(function(){open_new_dlg(dy_settings.get("down_clipboard")?{url:"<clipboard>"}:null)});$(b.BtnStart).click(function(){for(var h=dy_tasktb.grid.getSelectedRows(),a=[],b=0,c=h.length;b<c;++b)a.push(dy_tasktb.dataView.getItem(h[b]));dy_bkg.start_tasks(a)});$(b.BtnStartA).click(function(){dy_bkg.start_tasks(dy_tasktb.dataView.getRows())});
$(b.BtnPause).click(function(){for(var h=dy_tasktb.grid.getSelectedRows(),a=[],b=0,c=h.length;b<c;++b)a.push(dy_tasktb.dataView.getItem(h[b]));dy_bkg.stop_tasks(a)});$(b.BtnPauseA).click(function(){dy_bkg.stop_tasks(dy_tasktb.dataView.getRows())});$(b.BtnRestart).click(function(){for(var a=dy_tasktb.grid.getSelectedRows(),b=[],c=0,d=a.length;c<d;++c){var f=dy_tasktb.dataView.getItem(a[c]);f&&(dy_notify.remove(f.id),b.push(f))}dy_bkg.restart_tasks(b)});$(b.BtnTrash).click(function(){var a=$(this).hasClass("action_recycle"),
b=dy_tasktb.grid.getSelectedRows(),c=[],d=!0==dy_settings.get("recycle_cancel");if(a)for(var a=0,f=b.length;a<f;++a){var e=dy_tasktb.dataView.getItem(b[a]);e.state==DyEnums.TaskState.DOWNLOAD?c.push(e):(e.state==DyEnums.TaskState.QUEUE&&(e.state=DyEnums.TaskState.PAUSE),d&&dy_engine.erase(e,!0,!0),e.recycled=!0,e._cf={},dirtyTaskMan.set(e.id))}else for(a=0,f=b.length;a<f;++a)e=dy_tasktb.dataView.getItem(b[a]),e.recycled=!1,e._cf={},dirtyTaskMan.set(e.id);c.length&&(b={animation:250,buttons:{recycle_task:{action:function(){Apprise("close");
for(var a=0;a<c.length;++a){var b=c[a];d?(dy_engine.erase(b,!0,!0),DYTask.reset(b,DyEnums.TaskState.PAUSE)):dy_engine.pause(b);b.recycled=!0;b._cf={};dirtyTaskMan.set(b.id)}dy_tasktb.dataView.refresh();dy_taskstarter.reschedule()},className:null,id:"recycle_task",text:chrome.i18n.getMessage("confirmBtnYes")},recycle_none:{action:function(){Apprise("close")},className:null,id:"recycle_none",text:chrome.i18n.getMessage("btnCancel")}},input:!1,override:!0},Apprise(chrome.i18n.getMessage("confirmRecycleRunning"),
b));dy_tasktb.dataView.refresh();dy_taskstarter.reschedule()});$(b.BtnDelete).click(function(){function a(b){var h=dy_tasktb.grid.getSelectedRows();if(h.length){for(var t=!1,c=[],d=0,e=h.length;d<e;++d){var f=dy_tasktb.dataView.getItem(h[d]);f.state==DyEnums.TaskState.DOWNLOAD&&(t=!0);c.push(f)}dy_bkg.remove_tasks(c,b,null);dy_tasktb.dataView.deleteItems(c);dy_tasktb.isFreeOrder()&&dy_tasktb.update_free_order();dy_taskstarter.reschedule();chrome.runtime.sendMessage({cmd:"u_clear",src:"ui"});t&&dy_ui.update_status_downloading()}}
var b={animation:250,buttons:{delete_task:{action:function(){Apprise("close");a(!1)},className:null,id:"delete_task",text:chrome.i18n.getMessage("confirmBtnYes")},delete_file:{action:function(){Apprise("close");a(!0)},className:null,id:"delete_file",text:chrome.i18n.getMessage("confirmBtnYesFile")},delete_none:{action:function(){Apprise("close")},className:null,id:"delete_none",text:chrome.i18n.getMessage("btnCancel")}},input:!1,override:!0};Apprise(chrome.i18n.getMessage("confirmRemoveTask"),b)});
$(b.BtnSort).click(function(a){$(this).dropdown("show");a.stopPropagation()});$(b.BtnHelp).click(function(a){$(this).dropdown("show");a.stopPropagation()});$("#btn_help_about").click(function(){chrome.tabs.getCurrent(function(a){dy_tabman.open_options({uiWinId:a.windowId,pos:a.index+1,section:"about"})})});$("#btn_help_help").click(function(){chrome.tabs.getCurrent(function(a){dy_tabman.open_options({uiWinId:a.windowId,pos:a.index+1,section:"help"})})});$("#btn_help_faq").click(function(){chrome.tabs.create({url:"http://faq.chronodownloader.net"})});
$(b.BtnClear).click(function(a){$("#cb_clear_file").prop("checked",dy_settings.get("pop_clear_file"));$("#autoclear_type").val(dy_settings.get("autoclear_type"));$("#autoclear_timer").val(dy_settings.get("autoclear_timer"));$(this).dropdown("show");a.stopPropagation()});$("#cb_clear_file").change(function(){dy_settings.set("pop_clear_file",this.checked)});$("#btn_clear_finished").click(function(){dy_tasktb.busyLoading();setTimeout(function(){var a=dy_settings.get("pop_clear_file");dy_bkg.clear_tasks(function(a){return a.state==
DyEnums.TaskState.FINISH},a);dy_tasktb.loadingDone()},25)});$("#btn_clear_fmissing").click(function(){dy_tasktb.busyLoading();setTimeout(function(){dy_bkg.clear_tasks(function(a){return a.state==DyEnums.TaskState.FINISH&&!a.exists},!1);dy_tasktb.loadingDone()},25)});$("#btn_clear_failed").click(function(){dy_tasktb.busyLoading();setTimeout(function(){var a=dy_settings.get("pop_clear_file");dy_bkg.clear_tasks(function(a){return a.state==DyEnums.TaskState.INTERRUPTED},a);dy_tasktb.loadingDone()},25)});
$("#btn_clear_all").click(function(){dy_tasktb.busyLoading();setTimeout(function(){var a=dy_settings.get("pop_clear_file");dy_bkg.clear_tasks(function(a){return a.state==DyEnums.TaskState.FINISH||a.state==DyEnums.TaskState.INTERRUPTED},a);dy_tasktb.loadingDone()},25)});$("#autoclear_type,#autoclear_timer").change(function(){var a=$("#autoclear_type").val(),b=parseInt($("#autoclear_timer").val());if(isNaN(b)||!isFinite(b))b=-1,$("#autoclear_timer").val("-1");dy_bkg.auto_clear(a,b)});$(b.BtnOptions).click(function(){chrome.tabs.getCurrent(function(a){dy_tabman.open_options({uiWinId:a.windowId,
pos:a.index+1})})})})();(function(){function a(b){b=(b||"").replace(/\s/g,"");s!=b&&(dy_tasktb.dataView.setSearchText(s=b),dy_tasktb.dataView.refresh())}dy_ui.rebuild_display_filters(!0);$(b.LNavFilters).on("change",function(a){a=$(this).nestable("serialize");for(var b=[],h=1;h<a.length;++h)if(b.push(a[h].id),b.push(0),a[h].children)for(var c=0;c<a[h].children.length;++c)b.push(a[h].children[c].id),b.push(1);dy_rules.set_display_filters(b)});$(b.LNavBtnRecycled).click(function(a){a.preventDefault();
$(a.currentTarget).parent().hasClass("selected")||(dy_settings.get("clear_search")&&f(),$(".menu li").removeClass("selected"),$(a.currentTarget).parent().addClass("selected"),dy_tasktb.set_recycled_filter(),$(b.BtnAdd).hide(),$(b.BtnStart).hide(),$(b.BtnStartA).hide(),$(b.BtnPause).hide(),$(b.BtnPauseA).hide(),$(b.BtnTrash+" img")[0].src="../icons/toolbar/restore.png",$(b.BtnTrash).removeClass("action_recycle").data("dtitle",chrome.i18n.getMessage("tipBtnRestore")),dy_ui.save_selected_filter())});
$("#dy_searchbox .delete").click(function(){$("#dy_searchbox input").val("").change()});$("#dy_searchbox input").bind("input",function(){a($(this).val())});$("#dy_searchbox input").bind("change",function(){a($(this).val())})})();var d=chrome.i18n.getUILanguage();if("en-US"!=d&&"zh-CN"!=d&&"en"!=d&&!dy_settings.get("tip_translate")){var k=chrome.i18n.getMessage("uilang"),l=chrome.i18n.getMessage("uilangName"),m=d==k?2592E5:432E6,d=d==k?"If you find inappropriate word translation on GUI, please help us improve it!":
"Display Chrono in "+(l||"your language")+"? Please help us with translation!";Date.now()-(localStorage.ver1_t||0)>m&&$('<div title="http://translate.chronodownloader.net" class="status-tooltip" id="translate-info-box"><a class="delete">x</a>'+d+"</div>").appendTo("#dy_lnav").click(function(){chrome.tabs.create({url:"http://translate.chronodownloader.net"})}).find(".delete").click(function(){$(this).parent().remove();dy_settings.set("tip_translate",1)})}(function(){$("body").keydown(function(a){switch(a.which){case 65:if(a.ctrlKey&&
(a.target==document.body||"DIV"==a.target.tagName))return dy_tasktb.select_all(),!1;break;case 67:if(a.ctrlKey&&(a.target==document.body||"DIV"==a.target.tagName)&&!window.getSelection().toString()){a=dy_tasktb.grid.getSelectedRows();for(var b="",c=0;c<a.length;++c){var d=dy_tasktb.dataView.getItem(a[c]);d&&(b+=d.url+"\r\n")}if(b=b.trim())dy_ui.update_status_queue(chrome.i18n.getMessage("statusCopyURL")),setTimeout(function(){writeClipboard(b);dy_ui.update_status_queue(chrome.i18n.getMessage("statusCopyURLDone"),
2500)},10);return!1}}return!0});document.oncontextmenu=function(a){var b=a.target.nodeName.toLowerCase();if("input"!=b&&"textarea"!=b||a.target.disabled)return!1};window.addEventListener("dragover",function(a){var b=a.target.nodeName.toLowerCase();("input"!=b&&"textarea"!=b||a.target.disabled)&&a.preventDefault()},!1);window.addEventListener("drop",function(a){var b=a.target.nodeName.toLowerCase();if("input"!=b&&"textarea"!=b||a.target.disabled)b=a.dataTransfer.getData("text/plain").replace(/ /g,
"%20"),validateURL(b)&&(open_new_dlg({url:b}),a.preventDefault())},!1)})();dy_taskinfo.setup();dy_tasktb.setup();$("#dy_tbar button, .dy_status_toolbtn, .status-tooltip").each(function(){var a=$(this),b=a.attr("title");b&&(a.data("dtitle",b),a.removeAttr("title"))}).hover(function(){dy_ui.update_status_queue($(this).data("dtitle"),-2)},function(){dy_ui.restore_status_queue(void 0,200)});$("#dy_status_btn_open_location").click(function(){chrome.downloads.showDefaultFolder();$("#dy_status_btn_change_location").addClass("force_hide")});
$("#dy_status_btn_change_location").click(function(){chrome.tabs.create({url:"chrome://settings/search#"+encodeURIComponent(chrome.i18n.getMessage("chromesysDownloadLocation"))});$(this).addClass("force_hide")});$("#dy_status_btn_open_location").mouseenter(function(){$("#dy_status_btn_change_location").css("left",$(this).find("img").offset().left).removeClass("force_hide")});$("#dy_status_btn_location_wrap").mouseleave(function(){$("#dy_status_btn_change_location").addClass("force_hide")});$("#dropdown-sort .btn-sort-up").click(function(){if(!$(this).hasClass("btn-sorted")){$(".btn-sorted").removeClass("btn-sorted");
var a=$(this).parent().data("sortcol");dy_tasktb.sort_by(a,!0);dy_tasktb.update_sort_header(a,!0);$(this).addClass("btn-sorted")}});$("#dropdown-sort .btn-sort-down").click(function(){if(!$(this).hasClass("btn-sorted")){$(".btn-sorted").removeClass("btn-sorted");var a=$(this).parent().data("sortcol");dy_tasktb.sort_by(a,!1);dy_tasktb.update_sort_header(a,!1);$(this).addClass("btn-sorted")}});$("#dropdown-sort a").click(function(){var a=$(this).siblings(),b=a.find(".btn-sort-up").hasClass("btn-sorted");
$(".btn-sorted").removeClass("btn-sorted");var c=a.data("sortcol");dy_tasktb.sort_by(c,!b);dy_tasktb.update_sort_header(c,!b);b?a.find(".btn-sort-down").addClass("btn-sorted"):a.find(".btn-sort-up").addClass("btn-sorted")});g();m=!0==dy_settings.get("ui_grid_list")?"list":"table";$("input[name=ui_table_list]").change(function(){var a=$(this).filter(":checked").val();dy_tasktb.switch_ui(a)}).filter('[value="'+m+'"]').prop("checked",!0);(function(){dy_ui.uilayout=$(b.TotalWrap).layout({west__size:175,
resizable:!1,closable:!1,slidable:!1,south__size:25,east__size:164,resizerClass:"ui-layout-resizer-none",togglerClass:"ui-layout-toggler-none",spacing_open:0,spacing_closed:0,center__childOptions:{name:"table_layout",north__resizable:!1,north__closable:!1,north__slidable:!1,north__spacing_open:0,north__spacing_closed:0,north__resizerClass:"ui-layout-resizer-none",north__togglerClass:"ui-layout-toggler-none",east__spacing_open:15,east__spacing_closed:0,north__size:80,east__size:430,east__minSize:430,
east__maxSize:800,east__resizable:!0,east__initClosed:!0,east__slideTrigger_close:"click",east__slidable:!1,east__hideTogglerOnSlide:!1,east__togglerLength_open:40,east__paneSelector:"#dy_details_panel",east__resizerClass:"ui-layout-resizer-none",east__togglerClass:"details-panel-toggler",east__livePaneResizing:!0,east__sliderCursor:"resize-e",east__togglerTip_open:"",togglerLength_open:150,togglerLength_closed:150,hideTogglerOnSlide:!0,center__onresize:function(){dy_tasktb.grid&&dy_tasktb.grid.resizeCanvas()},
south__onopen:function(a,b,c,d,e){-1!=dy_tasktb.cur_task_id&&dy_tasktb.grid&&(a=dy_tasktb.dataView.getRowById(dy_tasktb.cur_task_id),dy_tasktb.grid.scrollRowIntoView(a,!1))}}});dy_tasktb.grid.init()})();$(".loading-overlay").fadeOut(1E3,function(){$(this).remove()});a&&a();a=dy_settings.get("tip_rateshare");0<a&&(m=Date.now(),1==a||isNaN(a)?dy_settings.set("tip_rateshare",m):2592E5<m-a&&setTimeout(function(){ui_notify.show_share()},6E4*rand(2,11)));c();e(chrome.extension.getURL("com/ga.js"),function(){gaTrackCustom("ext_stat",
"log","ui-rep");if(dy_settings.get("bg_image_enable")){var a=Date.now(),b=dy_settings.get("stat_lastbgimgtime");864E5<a-b&&(dy_settings.set("stat_lastbgimgtime",a),b&&gaTrackCustom("ext_stat","ui","bg-image",dy_settings.get("bg_image_url")))}})};dy_ui.update_sortasc_button=function(a,b){$(".btn-sorted").removeClass("btn-sorted");$("[data-sortcol="+a+"] .btn-sort-"+(b?"up":"down")).addClass("btn-sorted")};window.onunload=function(){dy_bkg.ui_close()};var u=function(a){var b=a.style.display;a.style.display=
"none";a.style.display=b},q="",k,l;dy_ui.update_status_queue=function(a,b,d){clearTimeout(l);l=void 0;if(-2!=b||void 0==k||-2==k)k&&-1!=k&&-2!=k&&clearTimeout(k),k=void 0,u($("#dy_status_queue").text(a).addClass("dy_status_temp")[0]),k=0<b?setTimeout(function(){$("#dy_status_queue").text(q).removeClass("dy_status_temp");k=void 0},b):b||-1,d&&d()};dy_ui.restore_status_queue=function(a,b){a&&(q=a);if(void 0==k||-2==k)k=void 0,clearTimeout(l),l=void 0,0<b?l=setTimeout(function(){$("#dy_status_queue").text(q).removeClass("dy_status_temp");
l=void 0},b):$("#dy_status_queue").text(q).removeClass("dy_status_temp")};dy_ui.update_status_downloading=function(){var a=dy_engine.numDownloading();0<a?(a=chrome.i18n.getMessage("statusNumDownloading",[a])+", "+get_byte_string_(dy_engine.overallSpeed,"/s"),$("#dy_status_downloading").text(a)):$("#dy_status_downloading").text("")}})();
$(function(){function f(){chrome.webRequest.onBeforeRequest.addListener(function(e){if(e.tabId!=dy_ui.tabid)return dy_tabman.open_ui(),chrome.tabs.remove(e.tabId),{cancel:!0}},{urls:[dy_tabman.index_url+"*"]},["blocking"])}do_i18n();chrome.tabs.getCurrent(function(e){dy_bkg&&dy_engine?(dy_ui.tabid=e.id,f(),chrome.runtime.onMessage.hasListener(ui_listener)||chrome.runtime.onMessage.addListener(ui_listener),dy_ui.setup(function(){dy_bkg.ui_ready(dy_ui.tabid);dy_settings.get("override_cr")&&ui_notify.show_tip("tip_openmanager",
4);$("#dy_status_bgbusy").toggle(dy_bkg.isBusy())})):window.close()})});
var ui_notify={show_updateinfo:function(f){f?(f={text:'<span class="noty-title">'+chrome.i18n.getMessage("msgTitleWelcome")+'</span><span style="text-align: left;padding-top:6px">'+chrome.i18n.getMessage("msgTextWelcome",['<a class="link_settings_saveas">chrome://settings</a> > <em>'+chrome.i18n.getMessage("chromesysShowAdvSettings")+"</em> > <em>"+chrome.i18n.getMessage("chromesysDownloadsSection")+"</em>","<em>"+chrome.i18n.getMessage("chromesysAllowFileAccess")+"</em>",'<a class="link_enable_file_access">chrome://extensions</a>']).replace(/\n/g,
"<br><br>")+"</span>",type:"information",layout:"center",modal:!0,closeWith:[],buttons:[{addClass:"notybtn-info",text:chrome.i18n.getMessage("btnImportChromeHistory"),onClick:function(e){e.options.callback.afterClose=function(){chrome.runtime.sendMessage({cmd:"import",src:"chrome"},function(){dy_tasktb.loadingDone(500,function(){dy_ui.update_status_queue(chrome.i18n.getMessage("statusImportDone"),2500)})})};dy_tasktb.busyLoading();dy_ui.update_status_queue(chrome.i18n.getMessage("statusImporting"));
e.close()}},{addClass:"notybtn-info",text:chrome.i18n.getMessage("btnStart"),onClick:function(e){e.close()}}],callback:{afterShow:function(){this.$bar.find(".link_settings_saveas").click(function(){chrome.tabs.create({url:"chrome://settings/search#"+encodeURIComponent(chrome.i18n.getMessage("chromesysDownloadLocation"))})});this.$bar.find(".link_enable_file_access").click(function(){chrome.tabs.create({url:"chrome://extensions/?id="+chrome.runtime.id})})}}},noty(f)):(f='<a target=_blank href="http://bugs.chronodownloader.net/changelog_page.php">'+
chrome.i18n.getMessage("titleUpdateLog")+"</a>",f=chrome.i18n.getMessage("msgUpdated",[chrome.runtime.getManifest().version,f]),noty({text:f,type:"success",layout:"top",modal:!0}))},show_share:function(){var f=dy_settings.items.tip_rateshare;if(f&&0<f.value&&!0!=f.shown_session){var e=chrome.i18n.getMessage(f.i18n),e={text:'<span class="noty-title">'+chrome.i18n.getMessage("titleRateShare")+'</span><span style="text-align: left;padding-bottom: 15px;">'+e+'</span><span class="share_buttons"></span>',
type:"information",closeWith:[],layout:"topCenter",maxVisible:2,callback:{afterShow:function(){add_share_buttons($(".share_buttons"))}}};e.buttons=[{addClass:"notybtn-info",text:chrome.i18n.getMessage("btnShareDone"),onClick:function(e){e.close();dy_settings.set("tip_rateshare",0);"undefined"!==typeof gaTrackCustom&&gaTrackCustom("ext_stat","log","shared")}},{addClass:"notybtn-info",text:chrome.i18n.getMessage("btnLater"),onClick:function(e){e.close();dy_settings.set("tip_rateshare",Date.now())}}];
noty(e);f.shown_session=!0;"undefined"!==typeof gaTrackCustom&&gaTrackCustom("ext_stat","ui","share-showed")}},show_tip:function(f,e){if(!(1<=$.noty.visibleCount())){var g=dy_settings.items[f];if(g&&g.message&&!(g.value>=e)&&(dy_settings.inc(f),!e||g.value==e)){var p={text:'<span class="noty-title">'+chrome.i18n.getMessage("titleTips")+"</span>"+g.message,type:"information",layout:"bottomRight",maxVisible:2};if(g.set_section||g.set_page){var b={addClass:"notybtn-info",text:chrome.i18n.getMessage("btnTakeMeThere"),
onClick:function(b){b.close();g.set_section?chrome.tabs.getCurrent(function(b){dy_tabman.open_options({uiWinId:b.windowId,pos:b.index+1,section:g.set_section})}):g.set_page&&chrome.tabs.create({url:g.set_page})}};p.buttons=[];p.buttons.push(b)}noty(p)}}}};
