(function(d){d.extend(!0,window,{Slick:{Editors:{Text:function(c){var a,b;this.init=function(){a=d("<INPUT type=text class='editor-text' />").appendTo(c.container).bind("keydown.nav",function(a){a.keyCode!==d.ui.keyCode.LEFT&&a.keyCode!==d.ui.keyCode.RIGHT||a.stopImmediatePropagation()}).focus().select()};this.destroy=function(){a.remove()};this.focus=function(){a.focus()};this.getValue=function(){return a.val()};this.setValue=function(b){a.val(b)};this.loadValue=function(e){b=e[c.column.field]||
"";a.val(b);a[0].defaultValue=b;a.select()};this.serializeValue=function(){return a.val()};this.applyValue=function(a,b){a[c.column.field]=b};this.isValueChanged=function(){return!(""==a.val()&&null==b)&&a.val()!=b};this.validate=function(){if(c.column.validator){var b=c.column.validator(a.val());if(!b.valid)return b}return{valid:!0,msg:null}};this.init()},Integer:function(c){var a,b;this.init=function(){a=d("<INPUT type=text class='editor-text' />");a.bind("keydown.nav",function(a){a.keyCode!==d.ui.keyCode.LEFT&&
a.keyCode!==d.ui.keyCode.RIGHT||a.stopImmediatePropagation()});a.appendTo(c.container);a.focus().select()};this.destroy=function(){a.remove()};this.focus=function(){a.focus()};this.loadValue=function(e){b=e[c.column.field];a.val(b);a[0].defaultValue=b;a.select()};this.serializeValue=function(){return parseInt(a.val(),10)||0};this.applyValue=function(a,b){a[c.column.field]=b};this.isValueChanged=function(){return!(""==a.val()&&null==b)&&a.val()!=b};this.validate=function(){return isNaN(a.val())?{valid:!1,
msg:"Please enter a valid integer"}:{valid:!0,msg:null}};this.init()},Date:function(c){var a,b,e=!1;this.init=function(){a=d("<INPUT type=text class='editor-text' />");a.appendTo(c.container);a.focus().select();a.datepicker({showOn:"button",buttonImageOnly:!0,buttonImage:"../images/calendar.gif",beforeShow:function(){e=!0},onClose:function(){e=!1}});a.width(a.width()-18)};this.destroy=function(){d.datepicker.dpDiv.stop(!0,!0);a.datepicker("hide");a.datepicker("destroy");a.remove()};this.show=function(){e&&
d.datepicker.dpDiv.stop(!0,!0).show()};this.hide=function(){e&&d.datepicker.dpDiv.stop(!0,!0).hide()};this.position=function(a){e&&d.datepicker.dpDiv.css("top",a.top+30).css("left",a.left)};this.focus=function(){a.focus()};this.loadValue=function(d){b=d[c.column.field];a.val(b);a[0].defaultValue=b;a.select()};this.serializeValue=function(){return a.val()};this.applyValue=function(a,b){a[c.column.field]=b};this.isValueChanged=function(){return!(""==a.val()&&null==b)&&a.val()!=b};this.validate=function(){return{valid:!0,
msg:null}};this.init()},YesNoSelect:function(c){var a,b;this.init=function(){a=d("<SELECT tabIndex='0' class='editor-yesno'><OPTION value='yes'>Yes</OPTION><OPTION value='no'>No</OPTION></SELECT>");a.appendTo(c.container);a.focus()};this.destroy=function(){a.remove()};this.focus=function(){a.focus()};this.loadValue=function(d){a.val((b=d[c.column.field])?"yes":"no");a.select()};this.serializeValue=function(){return"yes"==a.val()};this.applyValue=function(a,b){a[c.column.field]=b};this.isValueChanged=
function(){return a.val()!=b};this.validate=function(){return{valid:!0,msg:null}};this.init()},Checkbox:function(c){var a,b;this.init=function(){a=d("<INPUT type=checkbox value='true' class='editor-checkbox' hideFocus>");a.appendTo(c.container);a.focus()};this.destroy=function(){a.remove()};this.focus=function(){a.focus()};this.loadValue=function(d){(b=!!d[c.column.field])?a.prop("checked",!0):a.prop("checked",!1)};this.serializeValue=function(){return a.prop("checked")};this.applyValue=function(a,
b){a[c.column.field]=b};this.isValueChanged=function(){return this.serializeValue()!==b};this.validate=function(){return{valid:!0,msg:null}};this.init()},PercentComplete:function(c){var a,b,e;this.init=function(){a=d("<INPUT type=text class='editor-percentcomplete' />");a.width(d(c.container).innerWidth()-25);a.appendTo(c.container);b=d("<div class='editor-percentcomplete-picker' />").appendTo(c.container);b.append("<div class='editor-percentcomplete-helper'><div class='editor-percentcomplete-wrapper'><div class='editor-percentcomplete-slider' /><div class='editor-percentcomplete-buttons' /></div></div>");
b.find(".editor-percentcomplete-buttons").append("<button val=0>Not started</button><br/><button val=50>In Progress</button><br/><button val=100>Complete</button>");a.focus().select();b.find(".editor-percentcomplete-slider").slider({orientation:"vertical",range:"min",value:e,slide:function(b,c){a.val(c.value)}});b.find(".editor-percentcomplete-buttons button").bind("click",function(c){a.val(d(this).attr("val"));b.find(".editor-percentcomplete-slider").slider("value",d(this).attr("val"))})};this.destroy=
function(){a.remove();b.remove()};this.focus=function(){a.focus()};this.loadValue=function(b){a.val(e=b[c.column.field]);a.select()};this.serializeValue=function(){return parseInt(a.val(),10)||0};this.applyValue=function(a,b){a[c.column.field]=b};this.isValueChanged=function(){return!(""==a.val()&&null==e)&&(parseInt(a.val(),10)||0)!=e};this.validate=function(){return isNaN(parseInt(a.val(),10))?{valid:!1,msg:"Please enter a valid positive number"}:{valid:!0,msg:null}};this.init()},LongText:function(c){var a,
b,e,f=this;this.init=function(){var e=d("body");b=d("<DIV style='z-index:10000;position:absolute;background:white;padding:5px;border:3px solid gray; -moz-border-radius:10px; border-radius:10px;'/>").appendTo(e);a=d("<TEXTAREA hidefocus rows=5 style='backround:white;width:250px;height:80px;border:0;outline:0'>").appendTo(b);d("<DIV style='text-align:right'><BUTTON>Save</BUTTON><BUTTON>Cancel</BUTTON></DIV>").appendTo(b);b.find("button:first").bind("click",this.save);b.find("button:last").bind("click",
this.cancel);a.bind("keydown",this.handleKeyDown);f.position(c.position);a.focus().select()};this.handleKeyDown=function(a){a.which==d.ui.keyCode.ENTER&&a.ctrlKey?f.save():a.which==d.ui.keyCode.ESCAPE?(a.preventDefault(),f.cancel()):a.which==d.ui.keyCode.TAB&&a.shiftKey?(a.preventDefault(),c.grid.navigatePrev()):a.which==d.ui.keyCode.TAB&&(a.preventDefault(),c.grid.navigateNext())};this.save=function(){c.commitChanges()};this.cancel=function(){a.val(e);c.cancelChanges()};this.hide=function(){b.hide()};
this.show=function(){b.show()};this.position=function(a){b.css("top",a.top-5).css("left",a.left-5)};this.destroy=function(){b.remove()};this.focus=function(){a.focus()};this.loadValue=function(b){a.val(e=b[c.column.field]);a.select()};this.serializeValue=function(){return a.val()};this.applyValue=function(a,b){a[c.column.field]=b};this.isValueChanged=function(){return!(""==a.val()&&null==e)&&a.val()!=e};this.validate=function(){return{valid:!0,msg:null}};this.init()}}}})})(jQuery);
