/*

 (c) 2009-2013 Michael Leibman
 michael{dot}leibman{at}gmail{dot}com
 http://github.com/mleibman/slickgrid

 Distributed under MIT license.
 All rights reserved.

 SlickGrid v2.2

 NOTES:
     Cell/row DOM manipulations are done directly bypassing jQuery's DOM manipulation methods.
     This increases the speed dramatically, but can only be done safely because there are no event handlers
     or data associated with any cell/row DOM nodes.  Cell editors must make sure they implement .destroy()
     and do proper cleanup.
*/
(function(d){d.fn.drag=function(c,g,e){var f="string"==typeof c?c:"",k=d.isFunction(c)?c:d.isFunction(g)?g:null;0!==f.indexOf("drag")&&(f="drag"+f);e=(c==k?g:e)||{};return k?this.bind(f,e,k):this.trigger(f)};var k=d.event,m=k.special,f=m.drag={defaults:{which:1,distance:0,not:":input",handle:null,relative:!1,drop:!0,click:!1},datakey:"dragdata",noBubble:!0,add:function(c){var g=d.data(this,f.datakey),e=c.data||{};g.related+=1;d.each(f.defaults,function(c,d){void 0!==e[c]&&(g[c]=e[c])})},remove:function(){d.data(this,
f.datakey).related-=1},setup:function(){if(!d.data(this,f.datakey)){var c=d.extend({related:0},f.defaults);d.data(this,f.datakey,c);k.add(this,"touchstart mousedown",f.init,c);this.attachEvent&&this.attachEvent("ondragstart",f.dontstart)}},teardown:function(){(d.data(this,f.datakey)||{}).related||(d.removeData(this,f.datakey),k.remove(this,"touchstart mousedown",f.init),f.textselect(!0),this.detachEvent&&this.detachEvent("ondragstart",f.dontstart))},init:function(c){if(!f.touched){var g=c.data,e;
if(!(0!=c.which&&0<g.which&&c.which!=g.which||d(c.target).is(g.not)||g.handle&&!d(c.target).closest(g.handle,c.currentTarget).length)&&(f.touched="touchstart"==c.type?this:null,g.propagates=1,g.mousedown=this,g.interactions=[f.interaction(this,g)],g.target=c.target,g.pageX=c.pageX,g.pageY=c.pageY,g.dragging=null,e=f.hijack(c,"draginit",g),g.propagates&&((e=f.flatten(e))&&e.length&&(g.interactions=[],d.each(e,function(){g.interactions.push(f.interaction(this,g))})),g.propagates=g.interactions.length,
!1!==g.drop&&m.drop&&m.drop.handler(c,g),f.textselect(!1),f.touched?k.add(f.touched,"touchmove touchend",f.handler,g):k.add(document,"mousemove mouseup",f.handler,g),!f.touched||g.live)))return!1}},interaction:function(c,g){var e=d(c)[g.relative?"position":"offset"]()||{top:0,left:0};return{drag:c,callback:new f.callback,droppable:[],offset:e}},handler:function(c){var g=c.data;switch(c.type){case !g.dragging&&"touchmove":c.preventDefault();case !g.dragging&&"mousemove":if(Math.pow(c.pageX-g.pageX,
2)+Math.pow(c.pageY-g.pageY,2)<Math.pow(g.distance,2))break;c.target=g.target;f.hijack(c,"dragstart",g);g.propagates&&(g.dragging=!0);case "touchmove":c.preventDefault();case "mousemove":if(g.dragging){f.hijack(c,"drag",g);if(g.propagates){!1!==g.drop&&m.drop&&m.drop.handler(c,g);break}c.type="mouseup"}default:f.touched?k.remove(f.touched,"touchmove touchend",f.handler):k.remove(document,"mousemove mouseup",f.handler),g.dragging&&(!1!==g.drop&&m.drop&&m.drop.handler(c,g),f.hijack(c,"dragend",g)),
f.textselect(!0),!1===g.click&&g.dragging&&d.data(g.mousedown,"suppress.click",(new Date).getTime()+5),g.dragging=f.touched=!1}},hijack:function(c,g,e,E,m){if(e){var n=c.originalEvent,L=c.type,C=g.indexOf("drop")?"drag":"drop",w,ia=E||0,u,ja;E=isNaN(E)?e.interactions.length:E;c.type=g;c.originalEvent=null;e.results=[];do!(u=e.interactions[ia])||"dragend"!==g&&u.cancelled||(ja=f.properties(c,e,u),u.results=[],d(m||u[C]||e.droppable).each(function(E,m){ja.target=m;c.isPropagationStopped=function(){return!1};
w=m?k.dispatch.call(m,c,ja):null;!1===w?("drag"==C&&(u.cancelled=!0,e.propagates-=1),"drop"==g&&(u[C][E]=null)):"dropinit"==g&&u.droppable.push(f.element(w)||m);"dragstart"==g&&(u.proxy=d(f.element(w)||u.drag)[0]);u.results.push(w);delete c.result;if("dropinit"!==g)return w}),e.results[ia]=f.flatten(u.results),"dropinit"==g&&(u.droppable=f.flatten(u.droppable)),"dragstart"!=g||u.cancelled||ja.update());while(++ia<E);c.type=L;c.originalEvent=n;return f.flatten(e.results)}},properties:function(c,d,
e){var k=e.callback;k.drag=e.drag;k.proxy=e.proxy||e.drag;k.startX=d.pageX;k.startY=d.pageY;k.deltaX=c.pageX-d.pageX;k.deltaY=c.pageY-d.pageY;k.originalX=e.offset.left;k.originalY=e.offset.top;k.offsetX=k.originalX+k.deltaX;k.offsetY=k.originalY+k.deltaY;k.drop=f.flatten((e.drop||[]).slice());k.available=f.flatten((e.droppable||[]).slice());return k},element:function(c){if(c&&(c.jquery||1==c.nodeType))return c},flatten:function(c){return d.map(c,function(c){return c&&c.jquery?d.makeArray(c):c&&c.length?
f.flatten(c):c})},textselect:function(c){d(document)[c?"unbind":"bind"]("selectstart",f.dontstart).css("MozUserSelect",c?"":"none");document.unselectable=c?"off":"on"},dontstart:function(){return!1},callback:function(){}};f.callback.prototype={update:function(){m.drop&&this.available.length&&d.each(this.available,function(c){m.drop.locate(this,c)})}};var n=k.dispatch;k.dispatch=function(c){if(0<d.data(this,"suppress."+c.type)-(new Date).getTime())d.removeData(this,"suppress."+c.type);else return n.apply(this,
arguments)};var e=k.fixHooks.touchstart=k.fixHooks.touchmove=k.fixHooks.touchend=k.fixHooks.touchcancel={props:"clientX clientY pageX pageY screenX screenY".split(" "),filter:function(c,g){if(g){var f=g.touches&&g.touches[0]||g.changedTouches&&g.changedTouches[0]||null;f&&d.each(e.props,function(d,e){c[e]=f[e]})}return c}};m.draginit=m.dragstart=m.dragend=f})(jQuery);
(function(d){function k(){var c=!1,d=!1;this.stopPropagation=function(){c=!0};this.isPropagationStopped=function(){return c};this.stopImmediatePropagation=function(){d=!0};this.isImmediatePropagationStopped=function(){return d}}function m(){this.__nonDataRow=!0}function f(){this.__group=!0;this.count=this.level=0;this.title=this.value=null;this.collapsed=!1;this.totals=null;this.rows=[];this.groupingKey=this.groups=null}function n(){this.__groupTotals=!0;this.group=null;this.initialized=!1}function e(){var c=
null;this.isActive=function(d){return d?c===d:null!==c};this.activate=function(d){if(d!==c){if(null!==c)throw"SlickGrid.EditorLock.activate: an editController is still active, can't activate another editController";if(!d.commitCurrentEdit)throw"SlickGrid.EditorLock.activate: editController must implement .commitCurrentEdit()";if(!d.cancelCurrentEdit)throw"SlickGrid.EditorLock.activate: editController must implement .cancelCurrentEdit()";c=d}};this.deactivate=function(d){if(c!==d)throw"SlickGrid.EditorLock.deactivate: specified editController is not the currently active one";
c=null};this.commitCurrentEdit=function(){return c?c.commitCurrentEdit():!0};this.cancelCurrentEdit=function(){return c?c.cancelCurrentEdit():!0}}d.extend(!0,window,{Slick:{Event:function(){var c=[];this.subscribe=function(d){c.push(d)};this.unsubscribe=function(d){for(var e=c.length-1;0<=e;e--)c[e]===d&&c.splice(e,1)};this.notify=function(d,e,f){e=e||new k;f=f||this;for(var m,n=0;n<c.length&&!e.isPropagationStopped()&&!e.isImmediatePropagationStopped();n++)m=c[n].call(f,e,d);return m}},EventData:k,
EventHandler:function(){var c=[];this.subscribe=function(d,e){c.push({event:d,handler:e});d.subscribe(e);return this};this.unsubscribe=function(d,e){for(var f=c.length;f--;)if(c[f].event===d&&c[f].handler===e){c.splice(f,1);d.unsubscribe(e);return}return this};this.unsubscribeAll=function(){for(var d=c.length;d--;)c[d].event.unsubscribe(c[d].handler);c=[];return this}},Range:function(c,d,e,f){void 0===e&&void 0===f&&(e=c,f=d);this.fromRow=Math.min(c,e);this.fromCell=Math.min(d,f);this.toRow=Math.max(c,
e);this.toCell=Math.max(d,f);this.isSingleRow=function(){return this.fromRow==this.toRow};this.isSingleCell=function(){return this.fromRow==this.toRow&&this.fromCell==this.toCell};this.contains=function(c,d){return c>=this.fromRow&&c<=this.toRow&&d>=this.fromCell&&d<=this.toCell};this.toString=function(){return this.isSingleCell()?"("+this.fromRow+":"+this.fromCell+")":"("+this.fromRow+":"+this.fromCell+" - "+this.toRow+":"+this.toCell+")"}},NonDataRow:m,Group:f,GroupTotals:n,EditorLock:e,GlobalEditorLock:new e}});
f.prototype=new m;f.prototype.equals=function(c){return this.value===c.value&&this.count===c.count&&this.collapsed===c.collapsed&&this.title===c.title};n.prototype=new m})(jQuery);if("undefined"===typeof jQuery)throw"SlickGrid requires jquery module to be loaded";if(!jQuery.fn.drag)throw"SlickGrid requires jquery.event.drag module to be loaded";if("undefined"===typeof Slick)throw"slick.core.js not loaded";
(function(d){d.extend(!0,window,{Slick:{Grid:function(f,n,e,c){function g(){da||(da=!0,O=parseFloat(d.css(D[0],"width",!0)),U(),L(F),c.enableTextSelectionOnCells||I.bind("selectstart.ui",function(a){return d(a.target).is("input,textarea")}),nb(),w(),ia(),v(),ka(),C(),D.bind("resize.slickgrid",ka),I.bind("scroll",La),Aa.bind("contextmenu",vc).bind("click",wc).delegate(".slick-header-column","mouseenter",xc).delegate(".slick-header-column","mouseleave",yc),ea.bind("scroll",zc),Va.add(ob).bind("keydown",
Kb),M.bind("keydown",Kb).bind("click",Ac).bind("dblclick",Bc).bind("contextmenu",Cc).bind("draginit",Dc).bind("dragstart",{distance:3},Ec).bind("drag",Fc).bind("dragend",Gc).delegate(".slick-cell","mouseenter",Hc).delegate(".slick-cell","mouseleave",Ic),navigator.userAgent.toLowerCase().match(/webkit/)&&navigator.userAgent.toLowerCase().match(/macintosh/)&&M.bind("mousewheel",Jc))}function B(a){for(var b=na.length;0<=b;b--)if(na[b]===a){na[b].destroy&&na[b].destroy();na.splice(b,1);break}}function E(){for(var a=
0,b=0,h=e.length;b<h;b++)a+=e[b].width;a+=k.width;return Math.max(a,O)+1E3}function Z(){for(var a=la?O-k.width:O,b=0,h=e.length;h--;)b+=e[h].width;return c.fullWidthRows?Math.max(b,a):b}function z(a){var b=fa;fa=Z();fa!=b&&(M.width(fa),sa.width(fa),F.width(E()));pb=fa>O-(la?k.width:0);Lb.width(fa+(la?k.width:0));(fa!=b||a)&&qb()}function L(a){a&&a.jquery&&a.attr("unselectable","on").css("MozUserSelect","none").bind("selectstart.ui",function(){return!1})}function C(){for(var a=M[0];(a=a.parentNode)!=
document.body&&null!=a;)if(a==I[0]||a.scrollWidth!=a.clientWidth||a.scrollHeight!=a.clientHeight){var b=d(a);Ba=Ba?Ba.add(b):b;b.bind("scroll."+P,Mb)}}function w(){function a(){d(this).addClass("ui-state-hover")}function b(){d(this).removeClass("ui-state-hover")}F.find(".slick-header-column").each(function(){var a=d(this).data("column");a&&l(p.onBeforeHeaderCellDestroy,{node:this,column:a})});F.empty();F.width(E());sa.find(".slick-headerrow-column").each(function(){var a=d(this).data("column");a&&
l(p.onBeforeHeaderRowCellDestroy,{node:this,column:a})});sa.empty();for(var h=0;h<e.length;h++){var y=e[h],V=d("<div class='ui-state-default slick-header-column' />").html("<span class='slick-column-name'>"+y.name+"</span>").width(y.width-oa).attr("id",""+P+y.id).attr("title",y.toolTip||"").data("column",y).addClass(y.headerCssClass||"").appendTo(F);if(c.enableColumnReorder||y.sortable)V.on("mouseenter",a).on("mouseleave",b);y.sortable&&(V.addClass("slick-header-sortable"),V.append("<span class='slick-sort-indicator' />"));
l(p.onHeaderCellRendered,{node:V[0],column:y});c.showHeaderRow&&(V=d("<div class='ui-state-default slick-headerrow-column l"+h+" r"+h+"'></div>").data("column",y).appendTo(sa),l(p.onHeaderRowCellRendered,{node:V[0],column:y}))}Wa(Q);ja();c.enableColumnReorder&&u()}function ia(){F.click(function(a){if(1==a.which&&(a.metaKey=a.metaKey||a.ctrlKey,!d(a.target).hasClass("slick-resizable-handle"))){var b=d(a.target).closest(".slick-header-column");if(b.length&&(b=b.data("column"),b.sortable&&K().commitCurrentEdit())){for(var h=
null,y=0;y<Q.length;y++)if(Q[y].columnId==b.id){h=Q[y];h.sortAsc=!h.sortAsc;break}a.metaKey&&c.multiColumnSort?h&&Q.splice(y,1):((a.shiftKey||a.metaKey)&&c.multiColumnSort||(Q=[]),h?0==Q.length&&Q.push(h):(h={columnId:b.id,sortAsc:b.defaultSortAsc},Q.push(h)));Wa(Q);c.multiColumnSort?l(p.onSort,{multiColumnSort:!0,sortCols:d.map(Q,function(a){return{sortCol:e[T[a.columnId]],sortAsc:a.sortAsc}})},a):l(p.onSort,{multiColumnSort:!1,sortCol:b,sortAsc:h.sortAsc},a)}}})}function u(){F.filter(":ui-sortable").sortable("destroy");
F.sortable({containment:"parent",distance:3,axis:"x",cursor:"default",tolerance:"intersection",helper:"clone",placeholder:"slick-sortable-placeholder ui-state-default slick-header-column",start:function(a,b){b.placeholder.width(b.helper.outerWidth()-oa);d(b.helper).addClass("slick-header-column-active")},beforeStop:function(a,b){d(b.helper).removeClass("slick-header-column-active")},stop:function(a){if(K().commitCurrentEdit()){for(var b=F.sortable("toArray"),h=[],c=0;c<b.length;c++)h.push(e[Nb(b[c].replace(P,
""))]);Ob(h);l(p.onColumnsReordered,{});a.stopPropagation();ja()}else d(this).sortable("cancel")}})}function ja(){var a,b,h,y,V,f,g,k;y=F.children();y.find(".slick-resizable-handle").remove();y.each(function(a,b){e[a].resizable&&(void 0===g&&(g=a),k=a)});void 0!==g&&y.each(function(m,n){m<g||c.forceFitColumns&&m>k||(d(n),d("<div class='slick-resizable-handle' />").appendTo(n).bind("dragstart",function(g,k){if(!K().commitCurrentEdit())return!1;h=g.pageX;d(this).parent().addClass("slick-header-column-active");
var W=null,l=null;y.each(function(a,b){e[a].previousWidth=d(b).outerWidth()});if(c.forceFitColumns)for(l=W=0,a=m+1;a<y.length;a++)b=e[a],b.resizable&&(null!==l&&(l=b.maxWidth?l+(b.maxWidth-b.previousWidth):null),W+=b.previousWidth-Math.max(b.minWidth||0,pa));var n=0,s=0;for(a=0;a<=m;a++)b=e[a],b.resizable&&(null!==s&&(s=b.maxWidth?s+(b.maxWidth-b.previousWidth):null),n+=b.previousWidth-Math.max(b.minWidth||0,pa));null===W&&(W=1E5);null===n&&(n=1E5);null===l&&(l=1E5);null===s&&(s=1E5);f=h+Math.min(W,
s);V=h-Math.min(n,l)}).bind("drag",function(d,g){var k,W=Math.min(f,Math.max(V,d.pageX))-h,l;if(0>W){l=W;for(a=m;0<=a;a--)b=e[a],b.resizable&&(k=Math.max(b.minWidth||0,pa),l&&b.previousWidth+l<k?(l+=b.previousWidth-k,b.width=k):(b.width=b.previousWidth+l,l=0));if(c.forceFitColumns)for(l=-W,a=m+1;a<y.length;a++)b=e[a],b.resizable&&(l&&b.maxWidth&&b.maxWidth-b.previousWidth<l?(l-=b.maxWidth-b.previousWidth,b.width=b.maxWidth):(b.width=b.previousWidth+l,l=0))}else{l=W;for(a=m;0<=a;a--)b=e[a],b.resizable&&
(l&&b.maxWidth&&b.maxWidth-b.previousWidth<l?(l-=b.maxWidth-b.previousWidth,b.width=b.maxWidth):(b.width=b.previousWidth+l,l=0));if(c.forceFitColumns)for(l=-W,a=m+1;a<y.length;a++)b=e[a],b.resizable&&(k=Math.max(b.minWidth||0,pa),l&&b.previousWidth+l<k?(l+=b.previousWidth-k,b.width=k):(b.width=b.previousWidth+l,l=0))}rb();c.syncColumnCellResize&&qb()}).bind("dragend",function(h,c){var V;d(this).parent().removeClass("slick-header-column-active");for(a=0;a<y.length;a++)b=e[a],V=d(y[a]).outerWidth(),
b.previousWidth!==V&&b.rerenderOnResize&&ta();z(!0);N();d(h.toElement).one("click",function(a){a.stopImmediatePropagation()});l(p.onColumnsResized,{})}).bind("dblclick",function(){l(p.onColumnResizerDblClick,{column:e[m]})}))})}function s(a){var b=0;d.each(["borderTopWidth","borderBottomWidth","paddingTop","paddingBottom"],function(h,c){b+=parseFloat(a.css(c))||0});return b}function U(){var a,b=["borderLeftWidth","borderRightWidth","paddingLeft","paddingRight"],h=["borderTopWidth","borderBottomWidth",
"paddingTop","paddingBottom"];a=d("<div class='ui-state-default slick-header-column' style='visibility:hidden'>-</div>").appendTo(F);oa=sb=0;"border-box"!=a.css("box-sizing")&&"border-box"!=a.css("-moz-box-sizing")&&"border-box"!=a.css("-webkit-box-sizing")&&(d.each(b,function(b,h){oa+=parseFloat(a.css(h))||0}),d.each(h,function(b,h){sb+=parseFloat(a.css(h))||0}));a.remove();var c=d("<div class='slick-row' />").appendTo(M);a=d("<div class='slick-cell' id='' style='visibility:hidden'>-</div>").appendTo(c);
Xa=Ya=0;"border-box"!=a.css("box-sizing")&&"border-box"!=a.css("-moz-box-sizing")&&"border-box"!=a.css("-webkit-box-sizing")&&(d.each(b,function(b,h){Xa+=parseFloat(a.css(h))||0}),d.each(h,function(b,h){Ya+=parseFloat(a.css(h))||0}));c.remove();pa=Math.max(oa,Xa)}function v(){ua=d("<style type='text/css' rel='stylesheet' />").appendTo(d("head"));for(var a=c.rowHeight-Ya,a=["."+P+" .slick-header-column { left: 1000px; }","."+P+" .slick-top-panel { height:"+c.topPanelHeight+"px; }","."+P+" .grid-inner-top-panel { height:"+
c.innerTopPanelHeight+"px; }","."+P+" .slick-headerrow-columns { height:"+c.headerRowHeight+"px; }","."+P+" .slick-cell { height:"+a+"px; text-align:center; vertical-align: middle; }","."+P+" .slick-row { height:"+c.rowHeight+"px; line-height:"+a+"px; }"],b=0;b<e.length;b++)a.push("."+P+" .l"+b+" { }"),a.push("."+P+" .r"+b+" { }");ua[0].styleSheet?ua[0].styleSheet.cssText=a.join(" "):ua[0].appendChild(document.createTextNode(a.join(" ")))}function l(a,b,h){h=h||new Slick.EventData;b=b||{};b.grid=
p;return a.notify(b,h,p)}function K(){return c.editorLock}function Nb(a){return T[a]}function tb(){var a,b,h=[],c=0,d=0,g,f=la?O-k.width:O;for(a=0;a<e.length;a++)b=e[a],h.push(b.width),d+=b.width,b.resizable&&(c+=b.width-Math.max(b.minWidth,pa));for(g=d;d>f&&c;){var l=(d-f)/c;for(a=0;a<e.length&&d>f;a++){b=e[a];var m=h[a];if(b.resizable&&!(m<=b.minWidth||m<=pa)){b=Math.max(b.minWidth,pa);var n=Math.floor(l*(m-b))||1,n=Math.min(n,m-b),d=d-n,c=c-n;h[a]-=n}}if(g<=d)break;g=d}for(g=d;d<f;){c=f/d;for(a=
0;a<e.length&&d<f;a++)b=e[a],l=h[a],b=!b.resizable||b.maxWidth<=l?0:Math.min(Math.floor(c*l)-l,b.maxWidth-l||1E6)||1,d+=b,h[a]+=b;if(g>=d)break;g=d}d=!1;for(a=0;a<e.length;a++)e[a].rerenderOnResize&&e[a].width!=h[a]&&(d=!0),e[a].width=h[a];rb();z(!0);d&&(ta(),N())}function rb(){if(da){for(var a,b=0,h=F.children(),c=h.length;b<c;b++)a=d(h[b]),a.width()!==e[b].width-oa&&a.width(e[b].width-oa);nb()}}function qb(){for(var a,b,h=0,c,d=0;d<e.length;d++){c=e[d].width;b=d;if(!va){var g=document.styleSheets;
for(a=0;a<g.length;a++)if((g[a].ownerNode||g[a].owningElement)==ua[0]){va=g[a];break}if(!va)throw Error("Cannot find stylesheet.");ub=[];vb=[];var g=va.cssRules||va.rules,f=void 0,f=void 0;for(a=0;a<g.length;a++){var l=g[a].selectorText;if(f=/\.l\d+/.exec(l))f=parseInt(f[0].substr(2,f[0].length-2),10),ub[f]=g[a];else if(f=/\.r\d+/.exec(l))f=parseInt(f[0].substr(2,f[0].length-2),10),vb[f]=g[a]}}a=ub[b];b=vb[b];a.style.left=h+"px";b.style.right=fa-h-c+"px";h+=e[d].width}}function Wa(a){Q=a;var b=F.children();
b.removeClass("slick-header-column-sorted").find(".slick-sort-indicator").removeClass("slick-sort-indicator-asc slick-sort-indicator-desc");d.each(Q,function(a,c){null==c.sortAsc&&(c.sortAsc=!0);var d=T[c.columnId];null!=d&&b.eq(d).addClass("slick-header-column-sorted").find(".slick-sort-indicator").addClass(c.sortAsc?"slick-sort-indicator-asc":"slick-sort-indicator-desc")})}function Pb(a,b){wb=[];for(var h={},d=0;d<b.length;d++)for(var g=b[d].fromRow;g<=b[d].toRow;g++){h[g]||(wb.push(g),h[g]={});
for(var f=b[d].fromCell;f<=b[d].toCell;f++)Qb(g,f)&&(h[g][e[f].id]=c.selectedCellCssClass)}Rb(c.selectedCellCssClass,h);l(p.onSelectedRowsChanged,{rows:Sb()},a)}function nb(){Ca=[];Da=[];for(var a=0,b=0,h=e.length;b<h;b++)Ca[b]=a,Da[b]=a+e[b].width,a+=e[b].width}function Ob(a){e=a;T={};for(a=0;a<e.length;a++){var b=e[a]=d.extend({},xb,e[a]);T[b.id]=a;b.minWidth&&b.width<b.minWidth&&(b.width=b.minWidth);b.maxWidth&&b.width>b.maxWidth&&(b.width=b.maxWidth)}nb();da&&(ta(),w(),ua.remove(),va=null,v(),
ka(),qb(),La())}function R(){return n.getLength?n.getLength():n.length}function ma(){return R()+(c.enableAddRow?1:0)}function ga(a){return n.getItem?n.getItem(a):n[a]}function Za(a){return Math.floor((a+J)/c.rowHeight)}function qa(a){a=Math.max(a,0);a=Math.min(a,$-G+(pb?k.height:0));var b=J;Ea=Math.min(Fa-1,Math.floor(a/Ga));J=Math.round(Ea*$a);a-=J;if(J!=b){var h=Ma(a);Tb(h);for(var d in t)t[d].rowNode.style.top=c.rowHeight*d-J+"px"}Ha!=a&&(wa=Ha+b<a+J?1:-1,I[0].scrollTop=ab=H=Ha=a,l(p.onViewportChanged,
{}))}function bb(a,b){var h=n.getItemMetadata&&n.getItemMetadata(a),d=h&&h.columns&&(h.columns[b.id]||h.columns[T[b.id]]);return d&&d.formatter||h&&h.formatter||b.formatter||c.formatterFactory&&c.formatterFactory.getFormatter(b)||c.defaultFormatter}function Ub(a,b){var h=e[b],d=n.getItemMetadata&&n.getItemMetadata(a);return(d=d&&d.columns)&&d[h.id]&&void 0!==d[h.id].editor?d[h.id].editor:d&&d[b]&&void 0!==d[b].editor?d[b].editor:h.editor||c.editorFactory&&c.editorFactory.getEditor(h)}function cb(a,
b){return c.dataItemColumnValueExtractor?c.dataItemColumnValueExtractor(a,b):a[b.field]}function Vb(a,b,h,c,d){var g=e[h],f="slick-cell l"+h+" r"+Math.min(e.length-1,h+c-1)+(g.cssClass?" "+g.cssClass:"");b===r&&h===A&&(f+=" active");for(var l in X)X[l][b]&&X[l][b][g.id]&&(f+=" "+X[l][b][g.id]);a.push("<div class='"+f+"'>");d&&(f=cb(d,g),a.push(bb(b,g)(b,h,f,g,d)));a.push("</div>");t[b].cellRenderQueue.push(h);t[b].cellColSpans[h]=c}function Tb(a){for(var b in t)(b=parseInt(b,10))!==r&&(b<a.top||b>
a.bottom)&&db(b)}function ta(){q&&ha();Na();for(var a in t)db(a)}function db(a){var b=t[a];b&&(eb==b.rowNode?(b.rowNode.style.display="none",Oa=eb):M[0].removeChild(b.rowNode),delete t[a],delete ra[a],yb--,Wb++)}function Xb(a){var b,h;if(a&&a.length)for(b=wa=0,h=a.length;b<h;b++)q&&r===a[b]&&ha(),Na(),t[a[b]]&&db(a[b])}function Yb(a){Xb([a])}function zb(a){var b=t[a];if(b){Pa(a);var h=ga(a),c;for(c in b.cellNodesByColumnIdx)if(b.cellNodesByColumnIdx.hasOwnProperty(c)){c|=0;var d=e[c],g=b.cellNodesByColumnIdx[c];
a===r&&c===A&&q?q.loadValue(h):g.innerHTML=h?bb(a,d)(a,c,cb(h,d),d,h):""}Ab(a)}}function ka(){da&&(G=c.autoHeight?c.rowHeight*ma():parseFloat(d.css(D[0],"height",!0))-parseFloat(d.css(D[0],"paddingTop",!0))-parseFloat(d.css(D[0],"paddingBottom",!0))-parseFloat(d.css(Aa[0],"height"))-s(Aa)-(c.showTopPanel?c.topPanelHeight+s(Qa):0)-(c.showHeaderRow?c.headerRowHeight+s(ea):0),fb=Math.ceil(G/c.rowHeight),O=parseFloat(d.css(D[0],"width",!0)),c.autoHeight||I.height(G),c.forceFitColumns&&tb(),gb(),La(),
Ra=-1,N())}function gb(){if(da){var a=ma(),b=a+(c.leaveSpaceForNewRows?fb-1:0),h=la,d=c.showInnerTopPanel?c.innerTopPanelHeight+s(Ia):0,e=b*c.rowHeight+d,g=Z();la=!c.autoHeight&&e>G;!la&&g>O&&e>G-k.height&&(la=!0);ha();var a=a-1,f;for(f in t)f>=a&&db(f);x&&r>a&&Na();f=aa;e>G-k.height?(aa=c.rowHeight*b,$=e):aa=$=G-k.height-d;$<m?(Ga=$,Fa=1,$a=0):(aa=m,Ga=aa/100,Fa=Math.floor($/Ga),$a=($-aa)/(Fa-1));aa!==f&&(M.css("height",aa),H=I[0].scrollTop);b=H+J<=$-G;0==$||0==H?Ea=J=0:b?qa(H+J):qa($-G);aa!=f&&
c.autoHeight&&ka();c.forceFitColumns&&h!=la&&tb();z(!1)}}function Ma(a,b){null==a&&(a=H);null==b&&(b=S);return{top:Za(a),bottom:Za(a+G)+1,leftPx:b,rightPx:b+O}}function Zb(a,b){var h=Ma(a,b),d=Math.round(G/c.rowHeight);-1==wa?(h.top-=d,h.bottom+=3):1==wa?(h.top-=3,h.bottom+=d):(h.top-=3,h.bottom+=3);h.top=Math.max(0,h.top);h.bottom=Math.min(ma()-1,h.bottom);h.leftPx-=O;h.rightPx+=O;h.leftPx=Math.max(0,h.leftPx);h.rightPx=Math.min(fa,h.rightPx);return h}function Pa(a){if((a=t[a])&&a.cellRenderQueue.length)for(var b=
a.rowNode.lastChild;a.cellRenderQueue.length;){var c=a.cellRenderQueue.pop();a.cellNodesByColumnIdx[c]=b;b=b.previousSibling}}function $b(){c.enableAsyncPostRender&&(clearTimeout(Bb),Bb=setTimeout(ac,c.asyncPostRenderDelay))}function Ab(a){delete ra[a];Sa=Math.min(Sa,a);Ta=Math.max(Ta,a);$b()}function N(){if(da&&!Cb){var a=Ma(),b=Zb();Tb(b);if(Ra!=S){for(var h,d=[],g=[],f,l,k=b.top,m=b.bottom;k<=m;k++)if(h=t[k]){Pa(k);var s=b;f=k;var p=0,w=t[f],v=[];l=void 0;for(l in w.cellNodesByColumnIdx)if(w.cellNodesByColumnIdx.hasOwnProperty(l)){l|=
0;var U=w.cellColSpans[l];if(Ca[l]>s.rightPx||Da[Math.min(e.length-1,l+U-1)]<s.leftPx)f==r&&l==A||v.push(l)}for(s=void 0;null!=(s=v.pop());)w.rowNode.removeChild(w.cellNodesByColumnIdx[s]),delete w.cellColSpans[s],delete w.cellNodesByColumnIdx[s],ra[f]&&delete ra[f][s],p++;f=0;p=(p=n.getItemMetadata&&n.getItemMetadata(k))&&p.columns;w=ga(k);v=0;for(s=e.length;v<s&&!(Ca[v]>b.rightPx);v++)null==(l=h.cellColSpans[v])&&(l=1,p&&(l=(l=p[e[v].id]||p[v])&&l.colspan||1,"*"===l&&(l=s-v)),Da[Math.min(s-1,v+
l-1)]>b.leftPx&&(Vb(d,k,v,l,w),f++)),v+=1<l?l-1:0;f&&g.push(k)}if(d.length)for(k=document.createElement("div"),k.innerHTML=d.join("");null!=(h=g.pop());)for(h=t[h];null!=(m=h.cellRenderQueue.pop());)d=k.lastChild,h.rowNode.appendChild(d),h.cellNodesByColumnIdx[m]=d}g=M[0];h=[];d=[];k=!1;p=R();m=b.top;for(f=b.bottom;m<=f;m++)if(!t[m]){yb++;d.push(m);t[m]={rowNode:null,cellColSpans:[],cellNodesByColumnIdx:[],cellRenderQueue:[]};w=h;v=m;s=b;U=p;l=ga(v);var q="slick-row"+(v<U&&!l?" loading":"")+(v===
r?" active":"")+(1==v%2?" odd":" even");l||(q+=" "+c.addNewRowCssClass);(U=n.getItemMetadata&&n.getItemMetadata(v))&&U.cssClasses&&(q+=" "+U.cssClasses);w.push("<div class='ui-widget-content "+q+"' style='top:"+(c.rowHeight*v-J)+"px'>");for(var u=void 0,C=void 0,q=0,B=e.length;q<B;q++){C=e[q];u=1;U&&U.columns&&(u=(u=U.columns[C.id]||U.columns[q])&&u.colspan||1,"*"===u&&(u=B-q));if(Da[Math.min(B-1,q+u-1)]>s.leftPx){if(Ca[q]>s.rightPx)break;Vb(w,v,q,u,l)}1<u&&(q+=u-1)}w.push("</div>");x&&r===m&&(k=
!0);bc++}if(d.length){b=document.createElement("div");b.innerHTML=h.join("");m=0;for(f=d.length;m<f;m++)t[d[m]].rowNode=g.appendChild(b.firstChild);k&&(x=Y(r,A))}Sa=a.top;Ta=Math.min(ma()-1,a.bottom);$b();ab=H;Ra=S;hb=null}}function zc(){var a=ea[0].scrollLeft;a!=I[0].scrollLeft&&(I[0].scrollLeft=a)}function La(){H=I[0].scrollTop;S=I[0].scrollLeft;var a=Math.abs(H-Ha),b=Math.abs(S-cc);b&&(cc=S,Aa[0].scrollLeft=S,Qa[0].scrollLeft=S,ea[0].scrollLeft=S);if(a)if(wa=Ha<H?1:-1,Ha=H,a<G)qa(H+J);else{var h=
J;Ea=aa==G?0:Math.min(Fa-1,Math.floor(($-G)/(aa-G)*H*(1/Ga)));J=Math.round(Ea*$a);h!=J&&ta()}if(b||a)if(hb&&clearTimeout(hb),20<Math.abs(ab-H)||20<Math.abs(Ra-S))c.forceSyncScrolling||Math.abs(ab-H)<G&&Math.abs(Ra-S)<O?N():hb=setTimeout(N,50),l(p.onViewportChanged,{});l(p.onScroll,{scrollLeft:S,scrollTop:H})}function ac(){for(var a=R();Sa<=Ta;){var b=0<=wa?Sa++:Ta--,h=t[b];if(h&&!(b>=a)){ra[b]||(ra[b]={});Pa(b);for(var d in h.cellNodesByColumnIdx)if(h.cellNodesByColumnIdx.hasOwnProperty(d)&&(d|=0,
a=e[d],a.asyncPostRender&&!ra[b][d])){var f=h.cellNodesByColumnIdx[d];f&&a.asyncPostRender(f,b,ga(b),a);ra[b][d]=!0}Bb=setTimeout(ac,c.asyncPostRenderDelay);break}}}function Db(a,b){var c,e,f,g,l;for(l in t){g=b&&b[l];f=a&&a[l];if(g)for(e in g)f&&g[e]==f[e]||(c=Y(l,T[e]))&&d(c).removeClass(g[e]);if(f)for(e in f)g&&g[e]==f[e]||(c=Y(l,T[e]))&&d(c).addClass(f[e])}}function Rb(a,b){var c=X[a];X[a]=b;Db(b,c);l(p.onCellCssStylesChanged,{key:a,hash:b})}function Jc(a){a=d(a.target).closest(".slick-row")[0];
a!=eb&&(Oa&&Oa!=a&&(M[0].removeChild(Oa),Oa=null),eb=a)}function Dc(a,b){var c=Ua(a);if(!c||!Eb(c.row,c.cell))return!1;c=l(p.onDragInit,b,a);return a.isImmediatePropagationStopped()?c:!1}function Ec(a,b){var c=Ua(a);if(!c||!Eb(c.row,c.cell))return!1;c=l(p.onDragStart,b,a);return a.isImmediatePropagationStopped()?c:!1}function Fc(a,b){return l(p.onDrag,b,a)}function Gc(a,b){l(p.onDragEnd,b,a)}function Kb(a){l(p.onKeyDown,{row:r,cell:A},a);var b=a.isImmediatePropagationStopped();if(!b)if(a.shiftKey||
a.altKey||a.ctrlKey)9!=a.which||!a.shiftKey||a.ctrlKey||a.altKey||(b=dc());else if(27==a.which){if(!K().isActive())return;ec()}else 34==a.which?(fc(),b=!0):33==a.which?(gc(),b=!0):37==a.which?b=hc():39==a.which?b=ic():38==a.which?b=jc():40==a.which?b=ib():9==a.which?b=kc():13==a.which&&(c.editable&&(q?r===R()?ib():lc():K().commitCurrentEdit()&&jb()),b=!0);if(b){a.stopPropagation();a.preventDefault();try{a.originalEvent.keyCode=0}catch(d){}}}function Ac(a){q||(a.target!=document.activeElement||d(a.target).hasClass("slick-cell"))&&
xa();var b=Ua(a);!b||null!==q&&r==b.row&&A==b.cell||(l(p.onClick,{row:b.row,cell:b.cell},a),a.isImmediatePropagationStopped()||A==b.cell&&r==b.row||!ba(b.row,b.cell)||K().isActive()&&!K().commitCurrentEdit()||(Fb(b.row,!1),ya(Y(b.row,b.cell))))}function Cc(a){var b=d(a.target).closest(".slick-cell",M);0!==b.length&&(x===b[0]&&null!==q||l(p.onContextMenu,{},a))}function Bc(a){var b=Ua(a);!b||null!==q&&r==b.row&&A==b.cell||(l(p.onDblClick,{row:b.row,cell:b.cell},a),a.isImmediatePropagationStopped()||
c.editable&&mc(b.row,b.cell,!0))}function xc(a){l(p.onHeaderMouseEnter,{column:d(this).data("column")},a)}function yc(a){l(p.onHeaderMouseLeave,{column:d(this).data("column")},a)}function vc(a){var b=d(a.target).closest(".slick-header-column",".slick-header-columns"),b=b&&b.data("column");l(p.onHeaderContextMenu,{column:b},a)}function wc(a){var b=d(a.target).closest(".slick-header-column",".slick-header-columns");(b=b&&b.data("column"))&&l(p.onHeaderClick,{column:b},a)}function Hc(a){l(p.onMouseEnter,
{},a)}function Ic(a){l(p.onMouseLeave,{},a)}function Eb(a,b){return!(0>a||a>=R()||0>b||b>=e.length)}function Gb(a){var b=/l\d+/.exec(a.className);if(!b)throw"getCellFromNode: cannot get cell - "+a.className;return parseInt(b[0].substr(1,b[0].length-1),10)}function Hb(a){for(var b in t)if(t[b].rowNode===a)return b|0;return null}function Ua(a){var b=d(a.target).closest(".slick-cell",M);if(!b.length)return null;a=Hb(b[0].parentNode);b=Gb(b[0]);return null==a||null==b?null:{row:a,cell:b}}function Na(){ya(null,
!1)}function xa(){-1==nc?Va[0].focus():ob[0].focus()}function kb(a,b,c){Fb(a,c);c=za(a,b);a=Ca[b];b=Da[b+(1<c?c-1:0)];c=S+O;a<S?(I.scrollLeft(a),La(),N()):b>c&&(I.scrollLeft(Math.min(a,b-I[0].clientWidth)),La(),N())}function ya(a,b){null!==x&&(ha(),d(x).removeClass("active"),t[r]&&d(t[r].rowNode).removeClass("active"));var h=x!==a;x=a;null!=x?(r=Hb(x.parentNode),A=Ja=Gb(x),null==b&&(b=r==R()||c.autoEdit),d(x).addClass("active"),d(t[r].rowNode).addClass("active"),c.editable&&b&&oc(r,A)&&(clearTimeout(Ib),
c.asyncEditorLoading?Ib=setTimeout(function(){jb()},c.asyncEditorLoadDelay):jb())):r=A=null;h&&l(p.onActiveCellChanged,pc())}function oc(a,b){var c=R();return a<c&&!ga(a)||e[b].cannotTriggerInsert&&a>=c||!Ub(a,b)?!1:!0}function ha(){if(q){l(p.onBeforeCellEditorDestroy,{editor:q});q.destroy();q=null;if(x){var a=ga(r);d(x).removeClass("editable invalid");if(a){var b=e[A],c=bb(r,b);x.innerHTML=c(r,A,cb(a,b),b,a);Ab(r)}}if(navigator.userAgent.toLowerCase().match(/msie/))if(document.selection&&document.selection.empty)try{document.selection.empty()}catch(f){}else window.getSelection&&
(a=window.getSelection())&&a.removeAllRanges&&a.removeAllRanges();K().deactivate(lb)}}function jb(a){if(x){if(!c.editable)throw"Grid : makeActiveCellEditable : should never get called when options.editable is false";clearTimeout(Ib);if(oc(r,A)){var b=e[A],h=ga(r);!1===l(p.onBeforeEditCell,{row:r,cell:A,item:h,column:b})?xa():(K().activate(lb),d(x).addClass("editable"),a||(x.innerHTML=""),q=new (a||Ub(r,A))({grid:p,gridPosition:mb(D[0]),position:mb(x),container:x,column:b,item:h||{},commitChanges:lc,
cancelChanges:ec}),h&&q.loadValue(h),qc=q.serializeValue(),q.position&&Mb())}}}function lc(){K().commitCurrentEdit()&&(xa(),c.autoEdit&&ib())}function ec(){K().cancelCurrentEdit()&&xa()}function mb(a){var b={top:a.offsetTop,left:a.offsetLeft,bottom:0,right:0,width:d(a).outerWidth(),height:d(a).outerHeight(),visible:!0};b.bottom=b.top+b.height;b.right=b.left+b.width;for(var c=a.offsetParent;(a=a.parentNode)!=document.body;)b.visible&&a.scrollHeight!=a.offsetHeight&&"visible"!=d(a).css("overflowY")&&
(b.visible=b.bottom>a.scrollTop&&b.top<a.scrollTop+a.clientHeight),b.visible&&a.scrollWidth!=a.offsetWidth&&"visible"!=d(a).css("overflowX")&&(b.visible=b.right>a.scrollLeft&&b.left<a.scrollLeft+a.clientWidth),b.left-=a.scrollLeft,b.top-=a.scrollTop,a===c&&(b.left+=a.offsetLeft,b.top+=a.offsetTop,c=a.offsetParent),b.bottom=b.top+b.height,b.right=b.left+b.width;return b}function rc(){return mb(x)}function Mb(){if(x&&(l(p.onActiveCellPositionChanged,{}),q)){var a=rc();q.show&&q.hide&&(a.visible?q.show():
q.hide());q.position&&q.position(a)}}function pc(){return x?{row:r,cell:A}:null}function Fb(a,b){var d=a*c.rowHeight,e=(a+1)*c.rowHeight-G+(pb?k.height:0);(a+1)*c.rowHeight>H+G+J?(qa(b?d:e),N()):a*c.rowHeight<H+J&&(qa(b?e:d),N())}function sc(a){a*=fb;qa((Za(H)+a)*c.rowHeight);N();if(c.enableCellNavigation&&null!=r){a=r+a;var b=ma();a>=b&&(a=b-1);0>a&&(a=0);for(var b=0,d=null,e=Ja;b<=Ja;)ba(a,b)&&(d=b),b+=za(a,b);null!==d?(ya(Y(a,d)),Ja=e):Na()}}function fc(){sc(1)}function gc(){sc(-1)}function za(a,
b){var c=n.getItemMetadata&&n.getItemMetadata(a);if(!c||!c.columns)return 1;c=(c=c.columns[e[b].id]||c.columns[b])&&c.colspan;return c="*"===c?e.length-b:c||1}function tc(a){for(var b=0;b<e.length;){if(ba(a,b))return b;b+=za(a,b)}return null}function Jb(a,b,c){if(b>=e.length)return null;do b+=za(a,b);while(b<e.length&&!ba(a,b));return b<e.length?{row:a,cell:b,posX:b}:null}function uc(a,b,c){if(0>=b)return null;c=tc(a);if(null===c||c>=b)return null;for(a={row:a,cell:c,posX:c};;){c=Jb(a.row,a.cell,
a.posX);if(!c)return null;if(c.cell>=b)return a;a=c}}function Kc(a,b,c){for(var d,e=ma();;){if(++a>=e)return null;for(d=b=0;b<=c;)d=b,b+=za(a,b);if(ba(a,d))return{row:a,cell:d,posX:c}}}function Lc(a,b,c){for(var d;;){if(0>--a)return null;for(d=b=0;b<=c;)d=b,b+=za(a,b);if(ba(a,d))return{row:a,cell:d,posX:c}}}function Mc(a,b,c){if(null==a&&null==b&&(a=b=c=0,ba(a,b)))return{row:a,cell:b,posX:b};if(b=Jb(a,b,c))return b;b=null;for(c=ma();++a<c;)if(b=tc(a),null!==b)return{row:a,cell:b,posX:b};return null}
function Nc(a,b,c){if(null==a&&null==b&&(a=ma()-1,b=c=e.length-1,ba(a,b)))return{row:a,cell:b,posX:b};for(var d,f;!d&&!(d=uc(a,b,c));){if(0>--a)return null;b=0;f=a;for(var g=0,l=null;g<e.length;)ba(f,g)&&(l=g),g+=za(f,g);f=l;null!==f&&(d={row:a,cell:f,posX:f})}return d}function ic(){return Ka("right")}function hc(){return Ka("left")}function ib(){return Ka("down")}function jc(){return Ka("up")}function kc(){return Ka("next")}function dc(){return Ka("prev")}function Ka(a){if(!c.enableCellNavigation||
!x&&"prev"!=a&&"next"!=a)return!1;if(!K().commitCurrentEdit())return!0;xa();nc={up:-1,down:1,left:-1,right:1,prev:-1,next:1}[a];if(a=(0,{up:Lc,down:Kc,left:uc,right:Jb,prev:Nc,next:Mc}[a])(r,A,Ja)){var b=a.row==R();kb(a.row,a.cell,!b);ya(Y(a.row,a.cell));Ja=a.posX;return!0}ya(Y(r,A));return!1}function Y(a,b){return t[a]?(Pa(a),t[a].cellNodesByColumnIdx[b]):null}function ba(a,b){if(!c.enableCellNavigation||a>=ma()||0>a||b>=e.length||0>b||e[b]._noactive)return!1;var d=n.getItemMetadata&&n.getItemMetadata(a);
return d&&"boolean"===typeof d.focusable?d.focusable:(d=d&&d.columns)&&d[e[b].id]&&"boolean"===typeof d[e[b].id].focusable?d[e[b].id].focusable:d&&d[b]&&"boolean"===typeof d[b].focusable?d[b].focusable:e[b].focusable}function Qb(a,b){if(a>=R()||0>a||b>=e.length||0>b)return!1;var c=n.getItemMetadata&&n.getItemMetadata(a);return c&&"boolean"===typeof c.selectable?c.selectable:(c=c&&c.columns&&(c.columns[e[b].id]||c.columns[b]))&&"boolean"===typeof c.selectable?c.selectable:e[b].selectable}function mc(a,
b,d){da&&ba(a,b)&&K().commitCurrentEdit()&&(kb(a,b,!1),b=Y(a,b),ya(b,d||a===R()||c.autoEdit),q||xa())}function Oc(){var a=ga(r),b=e[A];if(q){if(q.isValueChanged()){var h=q.validate();if(h.valid)return r<R()?(h={row:r,cell:A,editor:q,serializedValue:q.serializeValue(),prevSerializedValue:qc,execute:function(){this.editor.applyValue(a,this.serializedValue);zb(this.row);l(p.onCellChange,{row:r,cell:A,item:a})},undo:function(){this.editor.applyValue(a,this.prevSerializedValue);zb(this.row);l(p.onCellChange,
{row:r,cell:A,item:a})}},c.editCommandHandler?(ha(),c.editCommandHandler(a,b,h)):(h.execute(),ha())):(h={},q.applyValue(h,q.serializeValue()),ha(),l(p.onAddNewRow,{item:h,column:b})),!K().isActive();d(x).removeClass("invalid");d(x).width();d(x).addClass("invalid");l(p.onValidationError,{editor:q,cellNode:x,validationResults:h,row:r,cell:A,column:b});q.focus();return!1}ha()}return!0}function Pc(){ha();return!0}function Qc(a){for(var b=[],c=e.length-1,d=0;d<a.length;d++)b.push(new Slick.Range(a[d],
0,a[d],c));return b}function Sb(){if(!ca)throw"Selection model is not set";return wb}var Rc={explicitInitialization:!1,rowHeight:25,defaultColumnWidth:80,enableAddRow:!1,leaveSpaceForNewRows:!1,editable:!1,autoEdit:!0,enableCellNavigation:!0,enableColumnReorder:!0,asyncEditorLoading:!1,asyncEditorLoadDelay:100,forceFitColumns:!1,enableAsyncPostRender:!1,asyncPostRenderDelay:50,autoHeight:!1,editorLock:Slick.GlobalEditorLock,showHeaderRow:!1,headerRowHeight:25,showTopPanel:!1,topPanelHeight:25,showInnerTopPanel:!1,
innerTopPanelHeight:25,formatterFactory:null,editorFactory:null,cellFlashingCssClass:"flashing",selectedCellCssClass:"selected",multiSelect:!0,enableTextSelectionOnCells:!1,dataItemColumnValueExtractor:null,fullWidthRows:!1,multiColumnSort:!1,defaultFormatter:function(a,b,c,d,e){return null==c?"":(c+"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")},forceSyncScrolling:!1,addNewRowCssClass:"new-row"},xb={name:"",resizable:!0,sortable:!1,minWidth:30,rerenderOnResize:!1,headerCssClass:null,
defaultSortAsc:!0,focusable:!0,selectable:!0},$,aa,Ga,Fa,$a,Ea=0,J=0,wa=1,da=!1,D,P="slickgrid_"+Math.round(1E6*Math.random()),p=this,Va,ob,Aa,F,sa,ea,Lb,Qa,I,Ia,M,ua,Ba,va,ub,vb,G,O,fa,pb,la,oa=0,sb=0,Xa=0,Ya=0,pa,nc=1,Ja,r,A,x=null,q=null,qc,lb,t={},yb=0,fb,Ha=0,H=0,ab=0,Ra=0,cc=0,S=0,ca,wb=[],na=[],X={},T={},Q=[],Ca=[],Da=[],Ib=null,hb=null,Bb=null,ra={},Ta=null,Sa=null,bc=0,Wb=0,eb,Oa,Cb=!1;this.debug=function(){var a;a="\ncounter_rows_rendered:  "+bc;a+="\ncounter_rows_removed:  "+Wb;a+="\nrenderedRows:  "+
yb;a+="\nnumVisibleRows:  "+fb;a+="\nmaxSupportedCssHeight:  "+m;a+="\nn(umber of pages):  "+Fa;a+="\n(current) page:  "+Ea;a+="\npage height (ph):  "+Ga;a+="\nvScrollDir:  "+wa;alert(a)};this.eval=function(a){return eval(a)};d.extend(this,{slickGridVersion:"2.1",onScroll:new Slick.Event,onSort:new Slick.Event,onHeaderMouseEnter:new Slick.Event,onHeaderMouseLeave:new Slick.Event,onHeaderContextMenu:new Slick.Event,onHeaderClick:new Slick.Event,onHeaderCellRendered:new Slick.Event,onBeforeHeaderCellDestroy:new Slick.Event,
onHeaderRowCellRendered:new Slick.Event,onBeforeHeaderRowCellDestroy:new Slick.Event,onMouseEnter:new Slick.Event,onMouseLeave:new Slick.Event,onClick:new Slick.Event,onDblClick:new Slick.Event,onContextMenu:new Slick.Event,onKeyDown:new Slick.Event,onAddNewRow:new Slick.Event,onValidationError:new Slick.Event,onViewportChanged:new Slick.Event,onColumnsReordered:new Slick.Event,onColumnsResized:new Slick.Event,onCellChange:new Slick.Event,onBeforeEditCell:new Slick.Event,onBeforeCellEditorDestroy:new Slick.Event,
onBeforeDestroy:new Slick.Event,onActiveCellChanged:new Slick.Event,onActiveCellPositionChanged:new Slick.Event,onDragInit:new Slick.Event,onDragStart:new Slick.Event,onDrag:new Slick.Event,onDragEnd:new Slick.Event,onSelectedRowsChanged:new Slick.Event,onCellCssStylesChanged:new Slick.Event,registerPlugin:function(a){na.unshift(a);a.init(p)},unregisterPlugin:B,getColumns:function(){return e},setColumns:Ob,getColumnIndex:Nb,updateColumnHeader:function(a,b,c){if(da&&(a=T[a],null!=a)){var d=e[a],f=
F.children().eq(a);f&&(void 0!==b&&(e[a].name=b),void 0!==c&&(e[a].toolTip=c),l(p.onBeforeHeaderCellDestroy,{node:f[0],column:d}),f.attr("title",c||"").children().eq(0).html(b),l(p.onHeaderCellRendered,{node:f[0],column:d}))}},setSortColumn:function(a,b){Wa([{columnId:a,sortAsc:b}])},setSortColumns:Wa,getSortColumns:function(){return Q},autosizeColumns:tb,getOptions:function(){return c},setOptions:function(a){K().commitCurrentEdit()&&(ha(),c.enableAddRow!==a.enableAddRow&&Yb(R()),c=d.extend(c,a),
c.autoHeight&&(c.leaveSpaceForNewRows=!1),I.css("overflow-y",c.autoHeight?"hidden":"auto"),N())},getData:function(){return n},getDataLength:R,getDataItem:ga,setData:function(a,b){n=a;ta();gb();b&&qa(0)},getSelectionModel:function(){return ca},setSelectionModel:function(a){ca&&(ca.onSelectedRangesChanged.unsubscribe(Pb),ca.destroy&&ca.destroy());if(ca=a)ca.init(p),ca.onSelectedRangesChanged.subscribe(Pb)},getSelectedRows:Sb,setSelectedRows:function(a){if(!ca)throw"Selection model is not set";ca.setSelectedRanges(Qc(a))},
getContainerNode:function(){return D.get(0)},render:N,invalidate:function(){gb();ta();N()},invalidateRow:Yb,invalidateRows:Xb,invalidateAllRows:ta,updateCell:function(a,b){var c=Y(a,b);if(c){var d=e[b],f=ga(a);q&&r===a&&A===b?q.loadValue(f):(c.innerHTML=f?bb(a,d)(a,b,cb(f,d),d,f):"",Ab(a))}},updateRow:zb,getViewport:Ma,getRenderedRange:Zb,resizeCanvas:ka,updateRowCount:gb,scrollRowIntoView:Fb,scrollRowToTop:function(a){qa(a*c.rowHeight);N()},scrollCellIntoView:kb,getCanvasNode:function(){return M[0]},
focus:xa,getCellFromPoint:function(a,b){for(var c=Za(b),d=0,f=0,g=0;g<e.length&&f<a;g++)f+=e[g].width,d++;0>d&&(d=0);return{row:c,cell:d-1}},getCellFromEvent:Ua,getActiveCell:pc,setActiveCell:function(a,b){!da||a>R()||0>a||b>=e.length||0>b||!c.enableCellNavigation||(kb(a,b,!1),ya(Y(a,b),!1))},getActiveCellNode:function(){return x},getActiveCellPosition:rc,resetActiveCell:Na,editActiveCell:jb,getCellEditor:function(){return q},getCellNode:Y,getCellNodeBox:function(a,b){if(!Eb(a,b))return null;for(var d=
c.rowHeight*a-J,f=d+c.rowHeight-1,g=0,l=0;l<b;l++)g+=e[l].width;return{top:d,left:g,bottom:f,right:g+e[b].width}},canCellBeSelected:Qb,canCellBeActive:ba,navigatePrev:dc,navigateNext:kc,navigateUp:jc,navigateDown:ib,navigateLeft:hc,navigateRight:ic,navigatePageUp:gc,navigatePageDown:fc,gotoCell:mc,getInnerTopPanel:function(){return Ia[0]},setInnerTopPanelVisibility:function(a){c.showInnerTopPanel!=a&&((c.showInnerTopPanel=a)?Ia.slideDown("fast",ka):Ia.slideUp("fast",ka))},setHeaderRowVisibility:function(a){c.showHeaderRow!=
a&&((c.showHeaderRow=a)?ea.slideDown("fast",ka):ea.slideUp("fast",ka))},getHeaderRow:function(){return sa[0]},getHeaderRowColumn:function(a){a=T[a];return(a=sa.children().eq(a))&&a[0]},getGridPosition:function(){return mb(D[0])},flashCell:function(a,b,f){f=f||100;if(t[a]){var e=d(Y(a,b)),g=function(a){a&&setTimeout(function(){e.queue(function(){e.toggleClass(c.cellFlashingCssClass).dequeue();g(a-1)})},f)};g(4)}},addCellCssStyles:function(a,b){if(X[a])throw"addCellCssStyles: cell CSS hash with key '"+
a+"' already exists.";X[a]=b;Db(b,null);l(p.onCellCssStylesChanged,{key:a,hash:b})},setCellCssStyles:Rb,removeCellCssStyles:function(a){X[a]&&(Db(null,X[a]),delete X[a],l(p.onCellCssStylesChanged,{key:a,hash:null}))},getCellCssStyles:function(a){return X[a]},init:g,destroy:function(){K().cancelCurrentEdit();l(p.onBeforeDestroy,{});for(var a=na.length;a--;)B(na[a]);c.enableColumnReorder&&F.filter(":ui-sortable").sortable("destroy");Ba&&(Ba.unbind("scroll."+P),Ba=null);D.unbind(".slickgrid");ua.remove();
va=null;M.unbind("draginit dragstart dragend drag");D.empty().removeClass(P)},getEditorLock:K,getEditController:function(){return lb},beginRender:function(){Cb=!0},endRender:function(a){Cb=!1;!1!=a&&N()},onColumnResizerDblClick:new Slick.Event,enableColumnFit:function(){function a(a){var b=a.cloneNode(!0);b.style.cssText="position: absolute; right: auto;text-overflow: initial;white-space: nowrap; visibility: hidden;";a.parentNode.insertBefore(b,a);a=b.offsetWidth;b.parentNode.removeChild(b);return a}
var b=document.createElement("canvas").getContext("2d");p.onColumnResizerDblClick.subscribe(function(c,d){var f=d.column;if(f&&!0!=f._nofit){for(var e=T[f.id],g=F.children()[e],g=g?a(g)+8:0,k=0,m=Ma(),s=m.top,n=m.top;n<m.bottom;++n)if(t[n]){Pa(n);var v=t[n].cellNodesByColumnIdx[e],v=v?b.measureText(v.textContent||"").width:0;v>k&&(k=v,s=n)}e=t[s]?1+a(t[s].cellNodesByColumnIdx[e]):0;e=Math.max(g,e);0<e&&e!=f.width&&(f.width=e,rb(),z(!0),l(p.onColumnsResized,{}))}})},getRowNode:function(a){return t[a]?
t[a].rowNode:null},getCellNodeFromEvent:function(a){a=d(a.target).closest(".slick-cell",M);if(!a.length)return null;var b=Hb(a[0].parentNode),c=Gb(a[0]);return null==b||null==c?null:{row:b,cell:c,$cell:a}}});(function(){D=d(f);if(1>D.length)throw Error("SlickGrid requires a valid container, "+f+" does not exist in the DOM.");var a;if(!(a=m)){a=1E6;for(var b=navigator.userAgent.toLowerCase().match(/firefox/)?6E6:1E9,h=d("<div style='display:none' />").appendTo(document.body);;){var l=2*a;h.css("height",
l);if(l>b||h.height()!==l)break;else a=l}h.remove()}m=a;(a=k)||(a=d("<div style='position:absolute; top:-10000px; left:-10000px; width:100px; height:100px; overflow:scroll;'></div>").appendTo("body"),b={width:a.width()-a[0].clientWidth,height:a.height()-a[0].clientHeight},a.remove(),a=b);k=a;c=d.extend({},Rc,c);c.autoHeight&&(c.leaveSpaceForNewRows=!1);xb.width=c.defaultColumnWidth;T={};for(a=0;a<e.length;a++)b=e[a]=d.extend({},xb,e[a]),T[b.id]=a,b.minWidth&&b.width<b.minWidth&&(b.width=b.minWidth),
b.maxWidth&&b.width>b.maxWidth&&(b.width=b.maxWidth);if(c.enableColumnReorder&&!d.fn.sortable)throw Error("SlickGrid's 'enableColumnReorder = true' option requires jquery-ui.sortable module to be loaded");lb={commitCurrentEdit:Oc,cancelCurrentEdit:Pc};D.empty().css("overflow","hidden").css("outline",0).addClass(P).addClass("ui-widget");/relative|absolute|fixed/.test(D.css("position"))||D.css("position","relative");Va=d("<div tabIndex='0' hideFocus style='position:fixed;width:0;height:0;top:0;left:0;outline:0;'></div>").appendTo(D);
Aa=d("<div class='slick-header ui-state-default' style='overflow:hidden;position:relative;' />").appendTo(D);F=d("<div class='slick-header-columns' style='left:-1000px' />").appendTo(Aa);F.width(E());ea=d("<div class='slick-headerrow ui-state-default' style='overflow:hidden;position:relative;' />").appendTo(D);sa=d("<div class='slick-headerrow-columns' />").appendTo(ea);Lb=d("<div style='display:block;height:1px;position:absolute;top:0;left:0;'></div>").css("width",Z()+k.width+"px").appendTo(ea);
Qa=d("<div class='slick-top-panel-scroller ui-state-default' style='overflow:hidden;position:relative;' />").appendTo(D);d("<div class='slick-top-panel' style='width:10000px' />").appendTo(Qa);c.showTopPanel||Qa.hide();c.showHeaderRow||ea.hide();I=d("<div class='slick-viewport' style='width:100%;overflow:auto;outline:0;position:relative;;'>").appendTo(D);I.css("overflow-y",c.autoHeight?"hidden":"auto");M=d("<div class='grid-canvas' />").appendTo(I);Ia=d("<div class='grid-inner-top-panel'/>").prependTo(I);
c.showInnerTopPanel||Ia.hide();ob=Va.clone().appendTo(D);c.explicitInitialization||g()})()}}});var k,m})(jQuery);
(function(d){d.extend(!0,window,{Slick:{Formatters:{PercentComplete:function(d,m,f,n,e){return null==f||""===f?"-":50>f?"<span style='color:red;font-weight:bold;'>"+f+"%</span>":"<span style='color:green'>"+f+"%</span>"},PercentCompleteBar:function(d,m,f,n,e){return null==f||""===f?"":"<span class='percent-complete-bar' style='background:"+(30>f?"red":70>f?"silver":"green")+";width:"+f+"%'></span>"},YesNo:function(d,m,f,n,e){return f?"Yes":"No"},Checkmark:function(d,m,f,n,e){return f?"<img src='../images/tick.png'>":
""}}}})})(jQuery);
(function(d){d.extend(!0,window,{Slick:{AutoTooltips:function(k){function m(c){if((c=n.getCellNodeFromEvent(c))&&!n.getColumns()[c.cell]._notip){c=c.$cell;k.tipHandle&&(c=c.find(k.tipHandle));var f=c[0];if(f.tt_oldsw!=f.scrollWidth){var e;c.innerWidth()<f.scrollWidth?(e=d.trim(c.text()),k.maxToolTipLength&&e.length>k.maxToolTipLength&&(e=e.substr(0,k.maxToolTipLength-3)+"...")):e="";f.tt_oldsw=f.scrollWidth;c.attr("title",e)}}}function f(c,f){var e=f.column,k=d(c.target).closest(".slick-header-column");e.toolTip||
k.attr("title",k.innerWidth()<k[0].scrollWidth?e.name:"")}var n,e={enableForCells:!0,enableForHeaderCells:!1,maxToolTipLength:null,tipHandle:null};d.extend(this,{init:function(c){k=d.extend(!0,{},e,k);n=c;k.enableForCells&&n.onMouseEnter.subscribe(m);k.enableForHeaderCells&&n.onHeaderMouseEnter.subscribe(f)},destroy:function(){k.enableForCells&&n.onMouseEnter.unsubscribe(m);k.enableForHeaderCells&&n.onHeaderMouseEnter.unsubscribe(f)},config:function(c,d){k[c]=d}})}}})})(jQuery);
(function(d){d.extend(!0,window,{Slick:{RowSelectionModel:function(k){function m(c){return function(){ia||(ia=!0,c.apply(this,arguments),ia=!1)}}function f(c){for(var d=[],f=0;f<c.length;f++)for(var e=c[f].fromRow;e<=c[f].toRow;e++)d.push(e);return d}function n(c){for(var d=[],f=z.getColumns().length-1,e=0;e<c.length;e++)d.push(new Slick.Range(c[e],0,c[e],f));return d}function e(c,d){var f,e=[];for(f=c;f<=d;f++)e.push(f);for(f=d;f<c;f++)e.push(f);return e}function c(){return f(L)}function g(c){L=
c;C.onSelectedRangesChanged.notify(L)}function B(c,d){u.selectActiveRow&&null!=d.row&&g([new Slick.Range(d.row,0,d.row,z.getColumns().length-1)])}function E(d){var f=z.getActiveCell();if(f&&d.shiftKey&&!(d.ctrlKey||d.altKey||d.metaKey||38!=d.which&&40!=d.which)){var k=c();k.sort(function(c,d){return c-d});k.length||(k=[f.row]);var l=k[0],k=k[k.length-1],f=40==d.which?f.row<k||l==k?++k:++l:f.row<k?--k:--l;0<=f&&f<z.getDataLength()&&(z.scrollRowIntoView(f),L=n(e(l,k)),g(L));d.preventDefault();d.stopPropagation()}}
function Z(c){var e=z.getCellFromEvent(c);if(!(e&&z.canCellBeActive(e.row,e.cell)&&z.getOptions().multiSelect&&(c.ctrlKey||c.shiftKey||c.metaKey)))return!1;var k=f(L),l=d.inArray(e.row,k);if(-1===l&&(c.ctrlKey||c.metaKey))k.push(e.row),z.setActiveCell(e.row,e.cell);else if(-1!==l&&(c.ctrlKey||c.metaKey))k=d.grep(k,function(c,d){return c!==e.row}),z.setActiveCell(e.row,e.cell);else if(k.length&&c.shiftKey){for(var l=k.pop(),m=Math.min(e.row,l),w=Math.max(e.row,l),k=[];m<=w;m++)m!==l&&k.push(m);k.push(l);
z.setActiveCell(e.row,e.cell)}L=n(k);g(L);c.stopImmediatePropagation();return!0}var z,L=[],C=this,w=new Slick.EventHandler,ia,u,ja={selectActiveRow:!0};d.extend(this,{getSelectedRows:c,setSelectedRows:function(c){g(n(c))},getSelectedRanges:function(){return L},setSelectedRanges:g,init:function(c){u=d.extend(!0,{},ja,k);z=c;w.subscribe(z.onActiveCellChanged,m(B));w.subscribe(z.onKeyDown,m(E));w.subscribe(z.onClick,m(Z))},destroy:function(){w.unsubscribeAll()},onSelectedRangesChanged:new Slick.Event})}}})})(jQuery);
(function(d){d.extend(!0,window,{Slick:{Controls:{ColumnPicker:function(k,m,f){function n(c,d){m.getOptions().forceFitColumns&&(m.getOptions().forceFitColumns=!1,z.notify(!1,null,null))}function e(e,g){e.preventDefault();B.empty();c();E=[];for(var n,C,s=0;s<k.length;s++)n=d("<li />").appendTo(B),C=d("<input type='checkbox' />").data("column-id",k[s].id),E.push(C),null!=m.getColumnIndex(k[s].id)&&C.attr("checked","checked"),d("<label />").text(k[s].name).prepend(C).appendTo(n);d("<hr/>").appendTo(B);
n=d("<li />").appendTo(B);C=d("<input type='checkbox' />").data("option","autoresize");d("<label />").text(chrome.i18n.getMessage("optionTableAutoResize")).prepend(C).appendTo(n);m.getOptions().forceFitColumns&&C.attr("checked","checked");n=d("<li />").appendTo(B);C=d("<input type='checkbox' />").data("option","syncresize");d("<label />").text(chrome.i18n.getMessage("optionTableSyncResize")).prepend(C).appendTo(n);m.getOptions().syncColumnCellResize&&C.attr("checked","checked");B.css("top",e.pageY-
10).css("left",e.pageX-10).fadeIn(f.fadeSpeed)}function c(){for(var c=m.getColumns().slice(0),d=Array(k.length),e=0;e<d.length;e++)void 0===m.getColumnIndex(k[e].id)?d[e]=k[e]:d[e]=c.shift();k=d}function g(c){if("autoresize"==d(c.target).data("option"))c.target.checked?(m.setOptions({forceFitColumns:!0}),m.autosizeColumns()):m.setOptions({forceFitColumns:!1}),z.notify(c.target.checked,null,null);else if("syncresize"==d(c.target).data("option"))c.target.checked?m.setOptions({syncColumnCellResize:!0}):
m.setOptions({syncColumnCellResize:!1}),L.notify(c.target.checked,null,null);else if(d(c.target).is(":checkbox")){var e=[];d.each(E,function(c,f){d(this).is(":checked")&&e.push(k[c])});e.length?(m.setColumns(e),Z.notify(e,null,null)):d(c.target).attr("checked","checked")}}var B,E,Z=new Slick.Event,z=new Slick.Event,L=new Slick.Event,C={fadeSpeed:250};(function(){m.onHeaderContextMenu.subscribe(e);m.onColumnsReordered.subscribe(c);m.onColumnsResized.subscribe(n);f=d.extend({},C,f);B=d("<span class='slick-columnpicker' style='display:none;position:absolute;z-index:20;' />").appendTo(document.body);
B.bind("mouseleave",function(c){d(this).fadeOut(f.fadeSpeed)});B.bind("click",g)})();return{getAllColumns:function(){return k},onFitColumnsChanged:z,onSyncResizeChanged:L,onVisColumnsChanged:Z}}}}})})(jQuery);
(function(d){d.extend(!0,window,{Slick:{RowMoveManager:function(k){function m(c,d){c.stopImmediatePropagation()}function f(e,f){var m=c.getCellFromEvent(e);k.cancelEditOnDrag&&c.getEditorLock().isActive()&&c.getEditorLock().cancelCurrentEdit();if(c.getEditorLock().isActive()||!/move|selectAndMove/.test(c.getColumns()[m.cell].behavior))return!1;B=!0;e.stopImmediatePropagation();var n=c.getSelectedRows();if(0==n.length||-1==d.inArray(m.row,n))n=[m.row],c.setSelectedRows(n);m=c.getOptions().rowHeight;
f.selectedRows=n;f.selectionProxy=d("<div class='slick-reorder-proxy'/>").css("position","absolute").css("zIndex","99999").css("width",d(g).innerWidth()).css("height",m*n.length).css("top",e.pageY-d(g).offset().top-5).appendTo(g);f.guide=d("<div class='slick-reorder-guide'/>").css("position","absolute").css("zIndex","99998").css("width",d(g).innerWidth()).css("top",-1E3).appendTo(g);f.insertBefore=-1}function n(e,f){if(B){e.stopImmediatePropagation();var k=e.pageY-d(g).offset().top;f.selectionProxy.css("top",
k-5);k=Math.max(0,Math.min(Math.round(k/c.getOptions().rowHeight),c.getDataLength()));k!==f.insertBefore&&(!1===E.onBeforeMoveRows.notify({rows:f.selectedRows,insertBefore:k})?(f.guide.css("top",-1E3),f.canMove=!1):(f.guide.css("top",k*c.getOptions().rowHeight),f.canMove=!0),f.insertBefore=k)}}function e(c,d){B&&(B=!1,c.stopImmediatePropagation(),d.guide.remove(),d.selectionProxy.remove(),d.canMove&&E.onMoveRows.notify({rows:d.selectedRows,insertBefore:d.insertBefore}))}var c,g,B,E=this,Z=new Slick.EventHandler,
z={cancelEditOnDrag:!1};d.extend(this,{onBeforeMoveRows:new Slick.Event,onMoveRows:new Slick.Event,init:function(B){k=d.extend(!0,{},z,k);c=B;g=c.getCanvasNode();Z.subscribe(c.onDragInit,m).subscribe(c.onDragStart,f).subscribe(c.onDrag,n).subscribe(c.onDragEnd,e)},destroy:function(){Z.unsubscribeAll()}})}}})})(jQuery);
