"function"!==typeof Object.create&&(Object.create=function(a){function c(){}c.prototype=a;return new c});
(function(a){var c={init:function(b){this.options=a.extend({},a.noty.defaults,b);this.options.layout=this.options.custom?a.noty.layouts.inline:a.noty.layouts[this.options.layout];a.noty.themes[this.options.theme]?this.options.theme=a.noty.themes[this.options.theme]:b.themeClassName=this.options.theme;delete b.layout;delete b.theme;this.options=a.extend({},this.options,this.options.layout.options);this.options.id="noty_"+(new Date).getTime()*Math.floor(1E6*Math.random());this.options=a.extend({},this.options,
b);this._build();return this},_build:function(){var b=a('<div class="noty_bar noty_type_'+this.options.type+'"></div>').attr("id",this.options.id);b.append(this.options.template).find(".noty_text").html(this.options.text);this.$bar=null!==this.options.layout.parent.object?a(this.options.layout.parent.object).css(this.options.layout.parent.css).append(b):b;this.options.themeClassName&&this.$bar.addClass(this.options.themeClassName).addClass("noty_container_type_"+this.options.type);if(this.options.buttons){this.options.timeout=
!1;b=a("<div/>").addClass("noty_buttons");null!==this.options.layout.parent.object?this.$bar.find(".noty_bar").append(b):this.$bar.append(b);var c=this;a.each(this.options.buttons,function(b,d){var e=a("<button/>").addClass(d.addClass?d.addClass:"gray").html(d.text).attr("id",d.id?d.id:"button-"+b).appendTo(c.$bar.find(".noty_buttons")).bind("click",function(){a.isFunction(d.onClick)&&d.onClick.call(e,c)})})}this.$message=this.$bar.find(".noty_message");this.$closeButton=this.$bar.find(".noty_close");
this.$buttons=this.$bar.find(".noty_buttons");a.noty.store[this.options.id]=this},show:function(){var b=this;b.options.custom?b.options.custom.find(b.options.layout.container.selector).append(b.$bar):a(b.options.layout.container.selector).append(b.$bar);b.options.theme&&b.options.theme.style&&b.options.theme.style.apply(b);"function"===a.type(b.options.layout.css)?this.options.layout.css.apply(b.$bar):b.$bar.css(this.options.layout.css||{});b.$bar.addClass(b.options.layout.addClass);b.options.layout.container.style.apply(a(b.options.layout.container.selector));
b.showing=!0;b.options.theme&&b.options.theme.style&&b.options.theme.callback.onShow.apply(this);if(-1<a.inArray("click",b.options.closeWith))b.$message.css("cursor","pointer").one("click",function(a){b.stopPropagation(a);b.options.callback.onCloseClick&&b.options.callback.onCloseClick.apply(b);b.close()});if(-1<a.inArray("hover",b.options.closeWith))b.$bar.one("mouseenter",function(){b.close()});if(-1<a.inArray("button",b.options.closeWith))b.$closeButton.one("click",function(a){b.stopPropagation(a);
b.close()});-1==a.inArray("button",b.options.closeWith)&&b.$closeButton.remove();b.options.callback.onShow&&b.options.callback.onShow.apply(b);b.$bar.animate(b.options.animation.open,b.options.animation.speed,b.options.animation.easing,function(){b.options.callback.afterShow&&b.options.callback.afterShow.apply(b);b.showing=!1;b.shown=!0});b.options.timeout&&b.$bar.delay(b.options.timeout).promise().done(function(){b.close()});return this},close:function(){if(!(this.closed||this.$bar&&this.$bar.hasClass("i-am-closing-now"))){var b=
this;if(this.showing)b.$bar.queue(function(){b.close.apply(b)});else if(this.shown||this.showing)b.$bar.addClass("i-am-closing-now"),b.options.callback.onClose&&b.options.callback.onClose.apply(b),b.$bar.clearQueue().stop().animate(b.options.animation.close,b.options.animation.speed,b.options.animation.easing,function(){b.options.callback.afterClose&&b.options.callback.afterClose.apply(b)}).promise().done(function(){b.options.modal&&(a.notyRenderer.setModalCount(-1),0==a.notyRenderer.getModalCount()&&
a(".noty_modal").fadeOut("fast",function(){a(this).remove()}));a.notyRenderer.setLayoutCountFor(b,-1);0==a.notyRenderer.getLayoutCountFor(b)&&a(b.options.layout.container.selector).remove();"undefined"!==typeof b.$bar&&null!==b.$bar&&(b.$bar.remove(),b.$bar=null,b.closed=!0);delete a.noty.store[b.options.id];b.options.theme.callback&&b.options.theme.callback.onClose&&b.options.theme.callback.onClose.apply(b);b.options.dismissQueue||(a.noty.ontap=!0,a.notyRenderer.render());0<b.options.maxVisible&&
b.options.dismissQueue&&a.notyRenderer.render()});else{var c=[];a.each(a.noty.queue,function(a,d){d.options.id!=b.options.id&&c.push(d)});a.noty.queue=c}}},setText:function(a){this.closed||(this.options.text=a,this.$bar.find(".noty_text").html(a));return this},setType:function(a){this.closed||(this.options.type=a,this.options.theme.style.apply(this),this.options.theme.callback.onShow.apply(this));return this},setTimeout:function(a){if(!this.closed){var c=this;this.options.timeout=a;c.$bar.delay(c.options.timeout).promise().done(function(){c.close()})}return this},
stopPropagation:function(a){a=a||window.event;"undefined"!==typeof a.stopPropagation?a.stopPropagation():a.cancelBubble=!0},closed:!1,showing:!1,shown:!1};a.notyRenderer={};a.notyRenderer.init=function(b){b=Object.create(c).init(b);b.options.killer&&a.noty.closeAll();b.options.force?a.noty.queue.unshift(b):a.noty.queue.push(b);a.notyRenderer.render();return"object"==a.noty.returns?b:b.options.id};a.notyRenderer.render=function(){var b=a.noty.queue[0];"object"===a.type(b)?b.options.dismissQueue?0<
b.options.maxVisible?a(b.options.layout.container.selector+" li").length<b.options.maxVisible&&a.notyRenderer.show(a.noty.queue.shift()):a.notyRenderer.show(a.noty.queue.shift()):a.noty.ontap&&(a.notyRenderer.show(a.noty.queue.shift()),a.noty.ontap=!1):a.noty.ontap=!0};a.notyRenderer.show=function(b){b.options.modal&&(a.notyRenderer.createModalFor(b),a.notyRenderer.setModalCount(1));b.options.custom?0==b.options.custom.find(b.options.layout.container.selector).length?b.options.custom.append(a(b.options.layout.container.object).addClass("i-am-new")):
b.options.custom.find(b.options.layout.container.selector).removeClass("i-am-new"):0==a(b.options.layout.container.selector).length?a("body").append(a(b.options.layout.container.object).addClass("i-am-new")):a(b.options.layout.container.selector).removeClass("i-am-new");a.notyRenderer.setLayoutCountFor(b,1);b.show()};a.notyRenderer.createModalFor=function(b){if(0==a(".noty_modal").length){var c=a("<div/>").addClass("noty_modal").addClass(b.options.theme).data("noty_modal_count",0);b.options.theme.modal&&
b.options.theme.modal.css&&c.css(b.options.theme.modal.css);c.prependTo(a("body")).fadeIn("fast")}};a.notyRenderer.getLayoutCountFor=function(b){return a(b.options.layout.container.selector).data("noty_layout_count")||0};a.notyRenderer.setLayoutCountFor=function(b,c){return a(b.options.layout.container.selector).data("noty_layout_count",a.notyRenderer.getLayoutCountFor(b)+c)};a.notyRenderer.getModalCount=function(){return a(".noty_modal").data("noty_modal_count")||0};a.notyRenderer.setModalCount=
function(b){return a(".noty_modal").data("noty_modal_count",a.notyRenderer.getModalCount()+b)};a.fn.noty=function(b){b.custom=a(this);return a.notyRenderer.init(b)};a.noty={};a.noty.queue=[];a.noty.ontap=!0;a.noty.layouts={};a.noty.themes={};a.noty.returns="object";a.noty.store={};a.noty.get=function(b){return a.noty.store.hasOwnProperty(b)?a.noty.store[b]:!1};a.noty.close=function(b){return a.noty.get(b)?a.noty.get(b).close():!1};a.noty.setText=function(b,c){return a.noty.get(b)?a.noty.get(b).setText(c):
!1};a.noty.setType=function(b,c){return a.noty.get(b)?a.noty.get(b).setType(c):!1};a.noty.clearQueue=function(){a.noty.queue=[]};a.noty.closeAll=function(){a.noty.clearQueue();a.each(a.noty.store,function(a,c){c.close()})};a.noty.visibleCount=function(){return Object.keys(a.noty.store).length};var d=window.alert;a.noty.consumeAlert=function(b){window.alert=function(c){b?b.text=c:b={text:c};a.notyRenderer.init(b)}};a.noty.stopConsumeAlert=function(){window.alert=d};a.noty.defaults={layout:"top",theme:"defaultTheme",
type:"alert",text:"",dismissQueue:!0,template:'<div class="noty_message"><span class="noty_text"></span><div class="noty_close"></div></div>',animation:{open:{height:"toggle"},close:{height:"toggle"},easing:"swing",speed:500},timeout:!1,force:!1,modal:!1,maxVisible:5,killer:!1,closeWith:["click"],callback:{onShow:function(){},afterShow:function(){},onClose:function(){},afterClose:function(){},onCloseClick:function(){}},buttons:!1};a(window).resize(function(){a.each(a.noty.layouts,function(b,c){c.container.style.apply(a(c.container.selector))})})})(jQuery);
window.noty=function(a){return jQuery.notyRenderer.init(a)};(function(a){a.noty.layouts.bottom={name:"bottom",options:{},container:{object:'<ul id="noty_bottom_layout_container" />',selector:"ul#noty_bottom_layout_container",style:function(){a(this).css({bottom:0,left:"5%",position:"fixed",width:"90%",height:"auto",margin:0,padding:0,listStyleType:"none",zIndex:9999999})}},parent:{object:"<li />",selector:"li",css:{}},css:{display:"none"},addClass:""}})(jQuery);
(function(a){a.noty.layouts.bottomCenter={name:"bottomCenter",options:{},container:{object:'<ul id="noty_bottomCenter_layout_container" />',selector:"ul#noty_bottomCenter_layout_container",style:function(){a(this).css({bottom:20,left:0,position:"fixed",width:"310px",height:"auto",margin:0,padding:0,listStyleType:"none",zIndex:1E7});a(this).css({left:(a(window).width()-a(this).outerWidth(!1))/2+"px"})}},parent:{object:"<li />",selector:"li",css:{}},css:{display:"none",width:"310px"},addClass:""}})(jQuery);
(function(a){a.noty.layouts.bottomLeft={name:"bottomLeft",options:{},container:{object:'<ul id="noty_bottomLeft_layout_container" />',selector:"ul#noty_bottomLeft_layout_container",style:function(){a(this).css({bottom:20,left:20,position:"fixed",width:"310px",height:"auto",margin:0,padding:0,listStyleType:"none",zIndex:1E7});600>window.innerWidth&&a(this).css({left:5})}},parent:{object:"<li />",selector:"li",css:{}},css:{display:"none",width:"310px"},addClass:""}})(jQuery);
(function(a){a.noty.layouts.bottomRight={name:"bottomRight",options:{},container:{object:'<ul id="noty_bottomRight_layout_container" />',selector:"ul#noty_bottomRight_layout_container",style:function(){a(this).css({bottom:25,right:25,position:"fixed",width:"310px",height:"auto",margin:0,padding:0,listStyleType:"none",zIndex:1E7});600>window.innerWidth&&a(this).css({right:5})}},parent:{object:"<li />",selector:"li",css:{}},css:{display:"none",width:"310px","margin-top":"5px"},addClass:""}})(jQuery);
(function(a){a.noty.layouts.center={name:"center",options:{},container:{object:'<ul id="noty_center_layout_container" />',selector:"ul#noty_center_layout_container",style:function(){a(this).css({position:"fixed",width:"450px",height:"auto",margin:0,padding:0,listStyleType:"none",zIndex:1E7});var c=a(this).clone().css({visibility:"hidden",display:"block",position:"absolute",top:0,left:0}).attr("id","dupe");a("body").append(c);c.find(".i-am-closing-now").remove();c.find("li").css("display","block");
var d=c.height();c.remove();a(this).hasClass("i-am-new")?a(this).css({left:(a(window).width()-a(this).outerWidth(!1))/2+"px",top:(a(window).height()-d)/2+"px"}):a(this).animate({left:(a(window).width()-a(this).outerWidth(!1))/2+"px",top:(a(window).height()-d)/2+"px"},500)}},parent:{object:"<li />",selector:"li",css:{}},css:{display:"none",width:"450px"},addClass:""}})(jQuery);
(function(a){a.noty.layouts.centerLeft={name:"centerLeft",options:{},container:{object:'<ul id="noty_centerLeft_layout_container" />',selector:"ul#noty_centerLeft_layout_container",style:function(){a(this).css({left:20,position:"fixed",width:"310px",height:"auto",margin:0,padding:0,listStyleType:"none",zIndex:1E7});var c=a(this).clone().css({visibility:"hidden",display:"block",position:"absolute",top:0,left:0}).attr("id","dupe");a("body").append(c);c.find(".i-am-closing-now").remove();c.find("li").css("display",
"block");var d=c.height();c.remove();a(this).hasClass("i-am-new")?a(this).css({top:(a(window).height()-d)/2+"px"}):a(this).animate({top:(a(window).height()-d)/2+"px"},500);600>window.innerWidth&&a(this).css({left:5})}},parent:{object:"<li />",selector:"li",css:{}},css:{display:"none",width:"310px"},addClass:""}})(jQuery);
(function(a){a.noty.layouts.centerRight={name:"centerRight",options:{},container:{object:'<ul id="noty_centerRight_layout_container" />',selector:"ul#noty_centerRight_layout_container",style:function(){a(this).css({right:20,position:"fixed",width:"310px",height:"auto",margin:0,padding:0,listStyleType:"none",zIndex:1E7});var c=a(this).clone().css({visibility:"hidden",display:"block",position:"absolute",top:0,left:0}).attr("id","dupe");a("body").append(c);c.find(".i-am-closing-now").remove();c.find("li").css("display",
"block");var d=c.height();c.remove();a(this).hasClass("i-am-new")?a(this).css({top:(a(window).height()-d)/2+"px"}):a(this).animate({top:(a(window).height()-d)/2+"px"},500);600>window.innerWidth&&a(this).css({right:5})}},parent:{object:"<li />",selector:"li",css:{}},css:{display:"none",width:"310px"},addClass:""}})(jQuery);
(function(a){a.noty.layouts.inline={name:"inline",options:{},container:{object:'<ul class="noty_inline_layout_container" />',selector:"ul.noty_inline_layout_container",style:function(){a(this).css({width:"100%",height:"auto",margin:0,padding:0,listStyleType:"none",zIndex:9999999})}},parent:{object:"<li />",selector:"li",css:{}},css:{display:"none"},addClass:""}})(jQuery);
(function(a){a.noty.layouts.top={name:"top",options:{},container:{object:'<ul id="noty_top_layout_container" />',selector:"ul#noty_top_layout_container",style:function(){a(this).css({top:0,left:"5%",position:"fixed",width:"90%",height:"auto",margin:0,padding:0,listStyleType:"none",zIndex:9999999})}},parent:{object:"<li />",selector:"li",css:{}},css:{display:"none"},addClass:""}})(jQuery);
(function(a){a.noty.layouts.topCenter={name:"topCenter",options:{},container:{object:'<ul id="noty_topCenter_layout_container" />',selector:"ul#noty_topCenter_layout_container",style:function(){a(this).css({top:20,left:0,position:"fixed",width:"310px",height:"auto",margin:0,padding:0,listStyleType:"none",zIndex:1E7});a(this).css({left:(a(window).width()-a(this).outerWidth(!1))/2+"px"})}},parent:{object:"<li />",selector:"li",css:{}},css:{display:"none",width:"310px"},addClass:""}})(jQuery);
(function(a){a.noty.layouts.topLeft={name:"topLeft",options:{},container:{object:'<ul id="noty_topLeft_layout_container" />',selector:"ul#noty_topLeft_layout_container",style:function(){a(this).css({top:20,left:20,position:"fixed",width:"310px",height:"auto",margin:0,padding:0,listStyleType:"none",zIndex:1E7});600>window.innerWidth&&a(this).css({left:5})}},parent:{object:"<li />",selector:"li",css:{}},css:{display:"none",width:"310px"},addClass:""}})(jQuery);
(function(a){a.noty.layouts.topRight={name:"topRight",options:{},container:{object:'<ul id="noty_topRight_layout_container" />',selector:"ul#noty_topRight_layout_container",style:function(){a(this).css({top:20,right:20,position:"fixed",width:"310px",height:"auto",margin:0,padding:0,listStyleType:"none",zIndex:1E7});600>window.innerWidth&&a(this).css({right:5})}},parent:{object:"<li />",selector:"li",css:{}},css:{display:"none",width:"310px"},addClass:""}})(jQuery);
(function(a){a.noty.themes.defaultTheme={name:"defaultTheme",helpers:{borderFix:function(){if(this.options.dismissQueue){var c=this.options.layout.container.selector+" "+this.options.layout.parent.selector;switch(this.options.layout.name){case "top":a(c).css({borderRadius:"0px 0px 0px 0px"});a(c).last().css({borderRadius:"0px 0px 5px 5px"});break;case "topCenter":case "topLeft":case "topRight":case "bottomCenter":case "bottomLeft":case "bottomRight":case "center":case "centerLeft":case "centerRight":case "inline":a(c).css({borderRadius:"0px 0px 0px 0px"});
a(c).first().css({"border-top-left-radius":"5px","border-top-right-radius":"5px"});a(c).last().css({"border-bottom-left-radius":"5px","border-bottom-right-radius":"5px"});break;case "bottom":a(c).css({borderRadius:"0px 0px 0px 0px"}),a(c).first().css({borderRadius:"5px 5px 0px 0px"})}}}},modal:{css:{position:"fixed",width:"100%",height:"100%",backgroundColor:"#000",zIndex:1E4,opacity:0.6,display:"none",left:0,top:0}},style:function(){this.$bar.css({overflow:"hidden",background:"url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABsAAAAoCAYAAAAPOoFWAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAPZJREFUeNq81tsOgjAMANB2ov7/7ypaN7IlIwi9rGuT8QSc9EIDAsAznxvY4pXPKr05RUE5MEVB+TyWfCEl9LZApYopCmo9C4FKSMtYoI8Bwv79aQJU4l6hXXCZrQbokJEksxHo9KMOgc6w1atHXM8K9DVC7FQnJ0i8iK3QooGgbnyKgMDygBWyYFZoqx4qS27KqLZJjA1D0jK6QJcYEQEiWv9PGkTsbqxQ8oT+ZtZB6AkdsJnQDnMoHXHLGKOgDYuCWmYhEERCI5gaamW0bnHdA3k2ltlIN+2qKRyCND0bhqSYCyTB3CAOc4WusBEIpkeBuPgJMAAX8Hs1NfqHRgAAAABJRU5ErkJggg==') repeat-x scroll left top #fff"});
this.$message.css({fontSize:"0.9em",lineHeight:"1.3em",textAlign:"center",padding:"8px 10px 9px",width:"auto",position:"relative"});this.$closeButton.css({position:"absolute",top:4,right:4,width:10,height:10,background:"",display:"none",cursor:"pointer"});this.$buttons.css({padding:5,textAlign:"right",borderTop:"1px solid #ccc",backgroundColor:"#fff",fontSize:"0.9em"});this.$buttons.find("button").css({marginLeft:5});this.$buttons.find("button:first").css({marginLeft:0});this.$bar.bind({mouseenter:function(){a(this).find(".noty_close").stop().fadeTo("normal",
1)},mouseleave:function(){a(this).find(".noty_close").stop().fadeTo("normal",0)}});switch(this.options.layout.name){case "top":this.$bar.css({borderRadius:"0px 0px 5px 5px",borderBottom:"2px solid #eee",borderLeft:"2px solid #eee",borderRight:"2px solid #eee",boxShadow:"0 2px 4px rgba(0, 0, 0, 0.1)"});break;case "topCenter":case "center":case "bottomCenter":case "inline":this.$bar.css({borderRadius:"5px",border:"1px solid #eee",boxShadow:"0 2px 4px rgba(0, 0, 0, 0.1)"});this.$message.css({fontSize:"0.9em",
textAlign:"center"});break;case "topLeft":case "topRight":case "bottomLeft":case "bottomRight":case "centerLeft":case "centerRight":this.$bar.css({borderRadius:"5px",border:"1px solid #eee",boxShadow:"0 2px 4px rgba(0, 0, 0, 0.1)"});this.$message.css({fontSize:"0.9em",textAlign:"left"});break;case "bottom":this.$bar.css({borderRadius:"5px 5px 0px 0px",borderTop:"2px solid #eee",borderLeft:"2px solid #eee",borderRight:"2px solid #eee",boxShadow:"0 -2px 4px rgba(0, 0, 0, 0.1)"});break;default:this.$bar.css({border:"2px solid #eee",
boxShadow:"0 2px 4px rgba(0, 0, 0, 0.1)"})}switch(this.options.type){case "alert":case "notification":this.$bar.css({backgroundColor:"#FFF",borderColor:"#CCC",color:"#444"});break;case "warning":this.$bar.css({backgroundColor:"#FFEAA8",borderColor:"#FFC237",color:"#826200"});this.$buttons.css({borderTop:"1px solid #FFC237"});break;case "error":this.$bar.css({backgroundColor:"red",borderColor:"darkred",color:"#FFF"});this.$message.css({fontWeight:"bold"});this.$buttons.css({borderTop:"1px solid darkred"});
break;case "information":this.$bar.css({backgroundColor:"#57B7E2",borderColor:"#0B90C4",color:"#FFF"});this.$buttons.css({borderTop:"1px solid #0B90C4"});break;case "success":this.$bar.css({backgroundColor:"lightgreen",borderColor:"#50C24E",color:"darkgreen"});this.$buttons.css({borderTop:"1px solid #50C24E"});break;default:this.$bar.css({backgroundColor:"#FFF",borderColor:"#CCC",color:"#444"})}},callback:{onShow:function(){a.noty.themes.defaultTheme.helpers.borderFix.apply(this)},onClose:function(){a.noty.themes.defaultTheme.helpers.borderFix.apply(this)}}}})(jQuery);
