document.oncontextmenu=function(s){var l=s.target.nodeName.toLowerCase();if("input"!=l&&"textarea"!=l||s.target.disabled)return!1};
document.onready=function(){function s(a){return(a=RegExp("[\\?&]"+a+"=([^&#]*)").exec(location.href))?a[1]:void 0}function l(a){return a?a.trim():""}function x(a){a=a||"";var b=0==a.indexOf("data:"),c=a.indexOf("\r");-1==c&&(c=a.indexOf("\n"));-1!=c?a=a.substr(0,b?Math.min(c,1024):c):b&&1024<a.length&&(a=a.substr(0,1024));return b?C.test(a):D.test(a)}function u(a,b,c){q&&(clearTimeout(q),q=void 0);v.text(a);a&&c?v.addClass(c):v.removeClass();b&&(q=setTimeout(function(){v.text("").removeClass();q=
void 0},b))}function B(a){var b=f.find("form").serializeObject(),c=(b.naming||"").trim().replace(/(^(\\|\/|\.)+)|((\\|\/|\.)+$)/g,"").replace(/\s*(\\|\/)+\s*/g,"/").trim();if(0!=((c?c.length-c.replace(/\*/g,"").length:0)&1))return w.val(c),show_error_field(w),u(chrome.i18n.getMessage("errorInvalidNamingMask"),2E3),!1;a=!0==a;for(var k=[],e=b.url.split("\r\n"),d=l(b.referer),g=l(b.desc),E=l(b.text),h=l(b.title),s="on"==b.addtop||"checked"==b.addtop||"yes"==b.addtop,n="",z=0,p=e.length;z<p;++z){var t=
l(e[z]).replace(/ /g,"%20");if(t){var q=F(t);if(q)if(x(t.replace(/\[[^\[\]]*\]/g,""))){if(!confirm(G(q))||""!=b.naming&&-1==b.naming.indexOf("*")&&!confirm(chrome.i18n.getMessage("confirmBatchDownloadNaming")))return!1;r(q,"",0,function(a){k.push({url:a,folder:"",naming:c,referer:d,desc:g,threads:0})})}else n+=t+"\n";else x(t)?k.push({url:t,folder:"",naming:c,referer:d,desc:g,text:E,title:h,threads:0}):n+=t+"\n"}}b=!0;if(k&&0<k.length)try{chrome.runtime.sendMessage({cmd:"new_task",add_paused:a,addtop:s,
tasks:k,page_title:H},function(a){a||u(chrome.runtime.lastError,2E3)})}catch(v){u(v,2E3),b=!1}else b=!1;n&&(b=!1,n=l(n),m.val(n),show_error_field(m),u(chrome.i18n.getMessage("errorInvalidURLs"),2E3));return b}function A(a,b){a||(a={url:"",referer:"",desc:""});if("<clipboard>"==a.url)u(chrome.i18n.getMessage("statusReadClipboard"),0,"info"),setTimeout(function(){var c=readClipboard().trim().replace(/ /g,"%20");a.url=c&&x(c)?c:"";u("");A(a,b)},100);else{b&&b.fontSize&&(document.body.style.fontSize=
b.fontSize+"px");loadRecentList("naming_history","naming_list");var c=m.val();if(c)a.url&&(m.val(c+"\n"+a.url),m[0].style.height||m.attr("rows",""+Math.min(4,parseInt(m.attr("rows")||"1")+1)));else if(m.val(a.url),-1==a.url.indexOf("\n")&&-1==a.url.indexOf("\r")||m.attr("rows","2"),f.find("[name=referer]").val(a.referer),f.find("[name=desc]").val(a.desc),a.text&&f.find("[name=text]").val(a.text),a.title&&f.find("[name=title]").val(a.title),f.find("[name=addtop]").removeAttr("checked"),c=b?b.taskDef:
null)w.val(c.naming),c.addtop&&f.find("[name=addtop]").attr("checked","checked");a&&a.url?w.focus():m.focus()}}function y(){f.addClass("transparent");m.val("").attr("rows","1")[0].style.height="";setTimeout(function(){window.parent.postMessage({cmd:"close_dlg",id:I},"*");f.removeClass("transparent")},400)}function J(){f.find(".page").addClass("pulse");f.find(".page").on("webkitAnimationEnd",function(){$(this).removeClass("pulse")})}function G(a){var b=chrome.i18n.getMessage("confirmBatchDownload")+
"\n",c="",k=3,e=2,d=k+e+1;r(a,"",0,function(a){0<k--&&(c+=a+"\n");return 0<--d});if(d-1<e){var g="",e=e-Math.max(d-1,0),f={iterators:[]};f.comps=a.comps;for(var h=0;h<a.iterators.length;++h){var m=a.iterators[h].from,n=a.iterators[h].to,l=a.iterators[h].step,p=m;if(0<l)for(;p<=n;p+=l);else for(;p>=n;p+=l);p-=l;f.iterators.push({from:p,to:m,step:-l,isalpha:a.iterators[h].isalpha,padding:a.iterators[h].padding,padding0s:a.iterators[h].padding0s})}r(f,"",0,function(a){g=a+"\n"+g;return 0<--e});0>=d&&
(c+="...\n");c+=g}a.stop=!1;return b=b+c+("\n"+chrome.i18n.getMessage("confirmProceed"))}function r(a,b,c,k){if(a&&!a.stop)if(c<a.comps.length&&(b+=a.comps[c]),c>=a.comps.length-1)!1==k(b)&&(a.stop=!0);else{var e=a.iterators[c];if(0<e.step)if(e.isalpha)for(var d=e.from;d<=e.to;d+=e.step)r(a,b+String.fromCharCode(d),c+1,k);else if(e.padding)for(d=e.from;d<=e.to;d+=e.step){var g=Math.abs(d).toString();r(a,b+(0>d?"-":"")+(e.padding0s+g).slice(-Math.max(e.padding,g.length)),c+1,k)}else for(d=e.from;d<=
e.to;d+=e.step)r(a,b+d,c+1,k);else if(e.isalpha)for(d=e.from;d>=e.to;d+=e.step)r(a,b+String.fromCharCode(d),c+1,k);else if(e.padding)for(d=e.from;d>=e.to;d+=e.step)g=Math.abs(d).toString(),r(a,b+(0>d?"-":"")+(e.padding0s+g).slice(-Math.max(e.padding,g.length)),c+1,k);else for(d=e.from;d>=e.to;d+=e.step)r(a,b+d,c+1,k)}}function F(a){function b(a){return"0"==a[0]&&1<a.length||"-"==a[0]&&"0"==a[1]&&2<a.length}if(-1!=a.indexOf("\x00\x00"))return null;var c={comps:[],iterators:[],stop:!1};a=a.replace(/\[((?:-)?\d+|[a-z]):((?:-)?\d+|[a-z])(?::((?:-)?\d+))?\]/gi,
function(a,e,d,g){var f=0;if(void 0!=g&&(f=parseInt(g),isNaN(f)||!isFinite(f)))return a;g=e.charCodeAt(0);var h=d.charCodeAt(0);if(65<=g&&90>=g&&65<=h&&90>=h||97<=g&&122>=g&&97<=h&&122>=h){if(f=f||(0>h-g?-1:1),h==g||0>h-g==0>f)return c.iterators.push({isalpha:!0,from:g,to:h,step:f}),"\x00\x00"}else{g=parseInt(e,10);h=parseInt(d,10);if(isNaN(g)||isNaN(h))return a;f=f||(0>h-g?-1:1);if(h==g||0>h-g==0>f){a={isalpha:!1,from:g,to:h,step:f};b(e)?(e=e.length-("-"==e[0]),b(d)?a.padding=Math.max(e,d.length-
("-"==d[0])):a.padding=e):b(d)&&(a.padding=d.length-("-"==d[0]));if(a.padding)for(a.padding0s=Array(a.padding+1).join("0"),a.padding_stop=1,d=0;d<a.padding;++d)a.padding_stop*=10;c.iterators.push(a);return"\x00\x00"}}return a});return c.iterators.length?(c.comps=a.split("\x00\x00"),c):null}$.fn.serializeObject=function(){var a={},b=this.serializeArray();$.each(b,function(){void 0!==a[this.name]?(a[this.name].push||(a[this.name]=[a[this.name]]),a[this.name].push(this.value||"")):a[this.name]=this.value||
""});return a};var C=/^data:([^;]+)((?:;[^=]+=[^;]+)*)(?:;(base64))?,(.+)$/,D=RegExp("^(?:(?:https?|ftp)://)?(?:\\S+(?::\\S*)?@)?(?:(?!(?:10|127)(?:\\.\\d{1,3}){3})(?!(?:169\\.254|192\\.168)(?:\\.\\d{1,3}){2})(?!172\\.(?:1[6-9]|2\\d|3[0-1])(?:\\.\\d{1,3}){2})(?:[1-9]\\d?|1\\d\\d|2[01]\\d|22[0-3])(?:\\.(?:1?\\d{1,2}|2[0-4]\\d|25[0-5])){2}(?:\\.(?:[1-9]\\d?|1\\d\\d|2[0-4]\\d|25[0-4]))|(?:(?:[a-z\\u00a1-\\uffff0-9]-*)*[a-z\\u00a1-\\uffff0-9]+)(?:\\.(?:[a-z\\u00a1-\\uffff0-9]-*)*[a-z\\u00a1-\\uffff0-9]+)*(?:\\.(?:[a-z\\u00a1-\\uffff]{2,}))\\.?)(?::\\d{2,5})?(?:[/?#]\\S*)?$",
"i"),I=s("id"),K="1"==s("native"),H=decodeURIComponent((s("page_title")||"").replace(/\+/g," ")),f=$(".overlay"),m=f.find("[name=url]"),w=f.find("[name=naming]"),q,v=$("#error_msg");window.addEventListener("message",function(a){"init"==a.data.cmd&&A(a.data.task,a.data.dlg_opts)},!1);do_i18n();K||$(".native_only").remove();w.attr("placeholder",chrome.i18n.getMessage("phraseAutomatic"));f.find("input[type=number]").numeric({decimal:!1,negative:!1});$(document).bind("keydown.dydlg",function(a){27==a.keyCode&&
a.target==document.body&&y()});escape_clear_focus(f.find("input, textarea"));f.find(".dlg_cancel_btn, .close-button").click(function(){y()});f.find(".dlg_start_btn").click(function(){B()&&y()});f.find(".dlg_apause_btn").click(function(){B(!0)&&y()});f.find(".simptip-position-right").click(function(){chrome.runtime.sendMessage({cmd:"open_options",section:"help"})});f.click(function(a){a:{a=a.target;for(var b=f.find(".page")[0],c=document.body;a&&c!=a;){if(a==b){a=!0;break a}a=a.parentNode}a=!1}a||
J()});window.addEventListener("dragover",function(a){var b=a.target.nodeName.toLowerCase();("input"!=b&&"textarea"!=b||a.target.disabled)&&a.preventDefault()},!1);window.addEventListener("drop",function(a){var b=a.target.nodeName.toLowerCase();if("input"!=b&&"textarea"!=b||a.target.disabled)b=a.dataTransfer.getData("text/plain").replace(/ /g,"%20"),x(b)&&(A({url:b},null),a.preventDefault())},!1)};
