var cur_t=Date.now()/1E3,dy_bkg={url:window.location.href,ui_tabid:-1,popup_sniffer_tabid:-1,popup_dlist_open:!1},dy_pathman=new HistoryMan(DyStrings.Store.PathRecent,DyStrings.Store.PathRecentCnt),dy_namingman=new HistoryMan(DyStrings.Store.NamingRecent,DyStrings.Store.NamingRecentCnt);
(function(){function B(a){for(var b=dy_bkg.bg_tasks.length,c=0;c<b;++c)if(dy_bkg.bg_tasks[c].id==a)return c;return-1}function C(){chrome.runtime.sendMessage({cmd:"u_updated",data:D})}function s(a,b){return a[0]-b[0]||a[1]-b[1]||a[2]-b[2]}function t(a){a=a.split(".");for(var b=Array(3),c=0;c<a.length&&3>c;++c){var d=parseInt(a[c]);if(isNaN(d)||!isFinite(d))d=0;b[c]=d}for(;3>c;++c)b[c]=0;return b}function J(a){dy_settings.set("tip_translate",0);a=t(a);if(0>s(a,[0,7,3]))for(var b in dy_settings.items)if(0==
b.indexOf("tip_")&&"tip_rateshare"!=b){var c=dy_settings.items[b];0<c.value&&(c.value=100,localStorage["#"+b]=c.value)}s(a,[0,9,0]);console.log("onVerUpdated process")}function E(a,b){var c=document.getElementsByTagName("head")[0],d=document.createElement("script");d.type="text/javascript";d.src=a;d.onreadystatechange=b;d.onload=b;c.appendChild(d)}function K(){var a=/((ftp)|(https?)):\/\/.+/;chrome.windows.getAll({populate:!0},function(b){for(var c=["libs/jquery-2.1.0.min.js","com/dlgwrap.js","cs/dlg.js",
"cs/sniffer.js"],d=[!1,!1,!1,!0],e=0;e<b.length;e++)for(var f=b[e].tabs,g=0;g<f.length;g++)if(a.test(f[g].url))for(var h=0;h<c.length;++h)chrome.tabs.executeScript(f[g].id,{file:c[h],allFrames:d[h]},function(a){chrome.runtime.lastError&&console.log(chrome.runtime.lastError)})})}function L(){console.log("bkg init");dy_settings.load();dy_pathman.load([dy_settings.get("def_folder")]);var a=["*page_title*.*ext*","*title*.*ext*","*text*.*ext*","*name*.*ext*"];a.push(dy_settings.get("def_naming"));dy_namingman.load(a);
u&&J(u);chrome.downloads.setShelfEnabled(!1==dy_settings.get("hide_cr_bar"));dy_urlmonitor.start();dy_streammonitor.start();dy_settings.get("override_cr")&&dy_tabman.override(!0);chrome.tabs.onActivated.addListener(function(a){chrome.tabs.get(a.tabId,function(a){dy_bkg.ui_tab_ontop=a&&0==a.url.indexOf(dy_tabman.index_url);dy_bkg.ui_tab_ontop&&dy_settings.get("notify_progress")&&dy_notify.clear("task_")})});chrome.windows.onFocusChanged.addListener(function(a){-1!=dy_bkg.ui_tabid?chrome.tabs.get(dy_bkg.ui_tabid,
function(c){chrome.runtime.lastError?dy_bkg.ui_tab_ontop=!1:(dy_bkg.ui_tab_ontop=c&&c.windowId==a&&c.active,dy_bkg.ui_tab_ontop&&dy_settings.get("notify_progress")&&dy_notify.clear("task_"))}):dy_bkg.ui_tab_ontop=!1});chrome.browserAction.setPopup({popup:"pop/pop.htm"});1==dy_settings.get("pop_content")?chrome.browserAction.setTitle({title:chrome.i18n.getMessage("tipBrowserAction")}):chrome.browserAction.setTitle({title:chrome.i18n.getMessage("extName")});dy_menuman.addBA();chrome.runtime.onMessage.addListener(bg_listener);
chrome.runtime.onMessageExternal.addListener(ext_listener);dy_store.start_timer();(v||dy_settings.get("startup_show"))&&dy_tabman.open_ui({activate:!0},function(){v&&C();F=!0});chrome.webRequest.onBeforeRequest.addListener(function(a){return{cancel:!0}},{urls:[dy_bkg.url+"*"]},["blocking"]);K();setTimeout(function(){chrome.runtime.requestUpdateCheck(function(a,c){})},3E4);setInterval(function(){chrome.runtime.requestUpdateCheck(function(a,c){})},18E6);dy_taskstarter.schedule();(function(){for(var a=
[],c=dy_rules.getRules(),d=0;d<c.length;++d)if(c[d].as_filter){var e=dy_taskfilter.compile(c[d].condition);e&&(a.push(c[d].condition),a.push(e))}k.add(function(a,b){a._cf||(a._cf={});for(var c=0;c<b.length;c+=2)void 0==a._cf[b[c]]&&(a._cf[b[c]]=dy_taskfilter.testWith(b[c+1],a))},dy_bkg.bg_tasks,200,!1,0,a)})();chrome.alarms.clear("auto-clear-tasks",function(){var a=dy_settings.get("autoclear_type"),c=dy_settings.get("autoclear_timer");G(a,c)&&(a=dy_settings.get("autoclear_lasttime"),-1==a&&(a=Date.now(),
dy_settings.set("autoclear_lasttime",a)),a=c-Math.max(0,Date.now()-a)/6E4,a=Math.max(1,Math.ceil(a)),chrome.alarms.create("auto-clear-tasks",{delayInMinutes:a,periodInMinutes:c}),console.log("auto_clear will run in "+a+" mins"))})}function H(a){chrome.runtime.sendMessage({cmd:"hi_ui"},function(b){"hi"==b?(console.log("connected to ui"),a&&a()):(console.log("connecting to ui, try again"),H(a))})}function M(a){if(!a.filename)return null;var b=dy_bkg.create_task(a.url,a.referrer);if(!b)return-1;var c=
a.filename.replace(/^.*(\\|\/|\:)/,"");b.full_path=a.filename;b.naming="*name*.*ext*";b.file_ext=c;b.finished_bytes=a.bytesReceived;b.size=a.fileSize||a.totalBytes;b.exists=a.exists;b.mine_type=a.mime;b.time_add=new Date(a.startTime);a.endTime&&(b.time_finish=new Date(a.endTime),b.time_elapsed=(b.time_finish-b.time_add)/1E3);a.error&&(b.error_str=a.error);b.state=DyEnums.TaskState.PAUSE;"in_progress"==a.state?a.paused||(b.state=DyEnums.TaskState.DOWNLOAD):"complete"==a.state?b.state=DyEnums.TaskState.FINISH:
"interrupted"==a.state&&(b.state=DyEnums.TaskState.INTERRUPTED);b.state==DyEnums.TaskState.FINISH?(b.size=b.finished_bytes,b.progress=100):b.progress=0<b.size?b.finished_bytes/b.size*100:0;"safe"!=a.danger&&"accepted"!=a.danger&&(b._danger=!0);return b}function m(){w=!0;window.sendUIMessage=function(){}}function r(){window.sendUIMessage=chrome.runtime.sendMessage;w=!1}function x(){n+=1/N;l.save();l.clearRect(0,0,19,19);l.translate(Math.ceil(9.5),Math.ceil(9.5));l.rotate(2*Math.PI*((1-Math.sin(Math.PI/
2+n*Math.PI))/2));l.drawImage(y,-Math.ceil(9.5),-Math.ceil(9.5));l.restore();chrome.browserAction.setIcon({imageData:l.getImageData(0,0,19,19)});1>=n?setTimeout(x,O):(n=0,chrome.browserAction.setIcon({path:"../icons/logo/19.png"}))}function G(a,b){p=void 0;if(0>b)return!1;var c=6E4*b;switch(a){case "finished":cmp_func=function(a){return a.state==DyEnums.TaskState.FINISH&&Date.now()-a.time_add>c};break;case "interrupted":cmp_func=function(a){return a.state==DyEnums.TaskState.INTERRUPTED&&Date.now()-
a.time_add>c};break;case "both":cmp_func=function(a){return(a.state==DyEnums.TaskState.FINISH||a.state==DyEnums.TaskState.INTERRUPTED)&&Date.now()-a.time_add>c};break;default:return!1}console.log("setup auto_clear: "+a+", "+b+" mins");p=cmp_func;return!0}dy_bkg.file_access=!0;chrome.extension.isAllowedFileSchemeAccess(function(a){dy_bkg.file_access=a});var q=new bitset(9999);dy_bkg.dirtyTaskMan=new bitset(9999);dy_bkg.bg_tasks=[];dy_bkg.getDatas=function(){return dy_bkg.bg_tasks};dy_bkg.getRecents=
function(a){a||(a=15);for(var b=[],c=dy_bkg.bg_tasks.length,d=0;d<c;++d)dy_bkg.bg_tasks[d].recycled||b.push(d);dy_settings.get("poplist_showd_first")?b.sort(function(a,b){var c=dy_bkg.bg_tasks[a],d=dy_bkg.bg_tasks[b];return c.state==d.state?d.time_add-c.time_add:c.state<=DyEnums.TaskState._active?c.state-d.state:d.state<=DyEnums.TaskState._active?1:d.time_add-c.time_add}):b.sort(function(a,c){return dy_bkg.bg_tasks[c].time_add-dy_bkg.bg_tasks[a].time_add});return b.slice(0,a)};dy_bkg.task_by_id=function(a){a=
B(a);return-1==a?null:dy_bkg.bg_tasks[a]};chrome.runtime.onUpdateAvailable.addListener(function(a){dy_notify.show_crxupdate(a.version)});var u,v=!1,F=!1,D=!1;(function(){var a=localStorage.ver,b=chrome.runtime.getManifest().version,c=!1,d=a||b;localStorage.ver1&&localStorage.ver1_t||(localStorage.ver1=d,localStorage.ver1_t=Date.now());if(a){var d=t(a),e=t(b);d[2]=e[2]=0;0>s(d,e)&&(c=!0);a!=b&&(u=a)}else c=D=!0;c&&(v=!0,F&&C());localStorage.ver=b})();window.onload=function(){console.log("onload");
dy_store.open(function(){dy_store.getAllTasks(function(a){for(var b=0;b<a.length;++b){var c=a[b];q.set(c.id);c.state==DyEnums.TaskState.DOWNLOAD&&(c.state=DyEnums.TaskState.QUEUE,dy_bkg.dirtyTaskMan.set(c.id),dy_taskstarter.enqueue(c));-1==c.cr_id&&(c.cr_id=-2)}dy_bkg.bg_tasks=a;E(chrome.extension.getURL("bg/api_engine.js"),function(){dy_engine.setup()&&(L(),E(chrome.extension.getURL("com/ga.js"),function(){var a=Date.now(),c=dy_settings.get("stat_lastactive");864E5<a-c&&(gaTrackCustom("ext_stat",
"log","alive"),dy_settings.set("stat_lastactive",a))}))})})})};window.onunload=function(){chrome.runtime.onMessage.removeListener(bg_listener);chrome.runtime.onMessageExternal.removeListener(ext_listener);dy_store.stop_timer();dy_pathman.commit();dy_namingman.commit();dy_urlmonitor.stop();dy_streammonitor.stop();dy_tabman.override(!1);dy_store.commit(dy_store.close)};var z=[];dy_bkg.scheduleUIInit=function(a){z.push(a)};var P=1;dy_bkg.ui_ready=function(a){dy_bkg.ui_tabid=a;H(function(){for(;0<z.length;)z.shift()()});
a=new XMLHttpRequest;a.open("GET","http://www.chronodownloader.net?i="+P++,!0);a.send()};dy_bkg.ui_close=function(){dy_bkg.ui_tabid=-1;console.log("ui close")};dy_bkg.importChrome=function(a){function b(a){chrome.downloads.getFileIcon(a.cr_id,{size:16},function(b){chrome.runtime.lastError||dy_bkg.update_field(a,"iconURL16",b)});chrome.downloads.getFileIcon(a.cr_id,{size:32},function(b){chrome.runtime.lastError||(dy_bkg.update_field(a,"iconURL32",b),a.state==DyEnums.TaskState.DOWNLOAD&&dy_notify.update_icon(a,
b))})}chrome.downloads.search({},function(c){if(c&&c.length){dy_settings.get_taskdef();m();for(var d=dy_bkg.bg_tasks.length+10,e=0;e<c.length;++e){var f=M(c[e]);if(f){if(-1==f){dy_tabman.open_ui({activate:!0},function(){chrome.runtime.sendMessage({cmd:"u_alert",data:DyStrings.Error.noID})});break}dy_engine.addChromeTask(f,c[e].id,c[e].filename,!0);f=dy_bkg.push_task(f,!1);f<d&&(d=f)}}r();d<dy_bkg.bg_tasks.length&&(chrome.runtime.sendMessage({cmd:"u_new",idx:d,scroll_id:dy_bkg.bg_tasks[dy_bkg.bg_tasks.length-
1].id}),c=dy_bkg.bg_tasks.slice(d),c.reverse(),k.add(b,c,15,!1,100))}a&&a()})};var A,I=0;dy_bkg.showBadge=function(a){if(!w&&!A){var b=Date.now(),c=I;I=b;500>b-c?A=setTimeout(function(){A=void 0;dy_bkg.showBadge(-1)},500):(b="",dy_settings.get("badge_downnum")&&(c=dy_engine.numDownloading(),99<c?b="99+":0<c&&(b=c.toString(),-1==a&&(a=0<dy_taskstarter.queueSize()),a&&(b+="+"))),chrome.browserAction.setBadgeText({text:b}))}};window.sendUIMessage=chrome.runtime.sendMessage;var w=!1;dy_bkg.update_field=
function(a,b,c,d){a[b]=c;dy_bkg.dirtyTaskMan.set(a.id);!1!=d&&sendUIMessage({cmd:"u_fields",id:a.id,fields:[b]})};var l=document.createElement("canvas").getContext("2d"),y;y=new Image;y.src="../icons/logo/19.png";var n=0,N=36,O=10;dy_bkg.animateFlip=x;dy_bkg.add_display_task=function(a,b){var c=dy_settings.get_taskdef().addtop,d=dy_bkg.push_task(a,c);sendUIMessage({cmd:"u_new",ids:[a.id],idx:d,addtop:c,scroll_id:a.id});dy_tabman.getLastTab(function(a){chrome.tabs.sendMessage(a.id,{cmd:"d_anim",addpause:b})});
x();dy_settings.get("notify_oneclick")&&(dy_notify.task_start(a,b),dy_notify.show_tip("tip_notifications",6))};dy_bkg.create_task=function(a,b){var c=new DYTask;c.id=q.lowest0(!0);if(-1==c.id)return null;c.referer=b||"";c.eurl=c.url=a;return c};dy_bkg.push_task=function(a,b){if(!a)return-1;a.naming_auto=!a.naming;a.folder_auto=!a.folder;var c=-1;b?(dy_bkg.bg_tasks.unshift(a),c=0):(dy_bkg.bg_tasks.push(a),c=dy_bkg.bg_tasks.length-1);dy_bkg.dirtyTaskMan.set(a.id);return c};dy_bkg.start_tasks=function(a){a||
(a=dy_bkg.bg_tasks);var b=-1234;dy_settings.get("start_interrupted")&&(b=DyEnums.TaskState.INTERRUPTED);for(var c=[],d=0,e=a.length;d<e;++d){var f=a[d];if(f.state==DyEnums.TaskState.PAUSE||f.state==b)dy_bkg.update_field(f,"state",DyEnums.TaskState.QUEUE,!1),dy_taskstarter.enqueue(f),c.push(f.id)}c.length&&(dy_taskstarter.schedule(),chrome.runtime.sendMessage({cmd:"u_tasks_by_field",ids:c,field:"state"}))};dy_bkg.stop_tasks=function(a){a||(a=dy_bkg.bg_tasks);for(var b=[],c=0,d=a.length;c<d;++c){var e=
a[c];e.state==DyEnums.TaskState.QUEUE?(dy_bkg.update_field(e,"state",DyEnums.TaskState.PAUSE,!1),dy_taskstarter.dequeue(e)):e.state==DyEnums.TaskState.DOWNLOAD&&dy_engine.pause(e);b.push(e.id)}b.length&&(chrome.runtime.sendMessage({cmd:"u_tasks_by_field",ids:b,field:"state"}),dy_taskstarter.reschedule())};dy_bkg.restart_tasks=function(a){a||(a=dy_bkg.bg_tasks);var b=!1,c=[];m();for(var d=0,e=a.length;d<e;++d){var f=a[d];dy_engine.erase(f,!0);DYTask.reset(f);f.state==DyEnums.TaskState.DOWNLOAD?dy_engine.download(f):
(f.state=DyEnums.TaskState.QUEUE,dy_taskstarter.enqueue(f),b=!0);c.push(f.id);dy_bkg.dirtyTaskMan.set(f.id)}r();b&&dy_taskstarter.reschedule();chrome.runtime.sendMessage({cmd:"u_tasks",ids:c})};dy_bkg.remove_task_completely=function(a,b,c){a.state==DyEnums.TaskState.QUEUE&&(a.state=DyEnums.TaskState.PAUSE);dy_engine.erase(a,b);q.clear(a.id);dy_bkg.dirtyTaskMan.clear(a.id);dy_store.removeTaskById(a.id);b=B(a.id);-1!=b&&dy_bkg.bg_tasks.splice(b,1);dy_notify.remove(a.id);c&&chrome.runtime.sendMessage({cmd:"u_clear",
src:c})};dy_bkg.remove_tasks=function(a,b,c){m();for(var d=0,e=a.length;d<e;++d){var f=a[d];f.state==DyEnums.TaskState.QUEUE&&(f.state=DyEnums.TaskState.PAUSE);dy_engine.erase(f,b);q.clear(f.id);dy_bkg.dirtyTaskMan.clear(f.id)}r();k.add(dy_store.removeTasks,a,200,!0);k.add(dy_notify.removeTask,a,50,!1,150);c&&chrome.runtime.sendMessage({cmd:"u_clear",src:c,count:a.length})};dy_bkg.clear_tasks=function(a,b){console.log("Begin clearing tasks");var c=!1,d=!1,e=[];m();for(var f=dy_bkg.bg_tasks.length-
1;0<=f;--f){var g=dy_bkg.bg_tasks[f];a(g)&&(d||g.state!=DyEnums.TaskState.DOWNLOAD&&g.state!=DyEnums.TaskState.QUEUE||(d=!0),dy_engine.erase(g,b),q.clear(g.id),dy_bkg.dirtyTaskMan.clear(g.id),e.push(g.id),dy_bkg.bg_tasks.splice(f,1),c=!0)}r();k.add(dy_store.removeIds,e,200,!0);k.add(dy_notify.remove,e,50,!1,150);c&&chrome.runtime.sendMessage({cmd:"u_clear",count:e.length});d&&dy_bkg.showBadge(-1);console.log(e.length+" task(s) cleared")};var p;dy_bkg.auto_clear=function(a,b){chrome.alarms.clear("auto-clear-tasks",
function(){dy_settings.set("autoclear_type",a);dy_settings.set("autoclear_timer",b);G(a,b)?(dy_settings.set("autoclear_lasttime",Date.now()),chrome.alarms.create("auto-clear-tasks",{delayInMinutes:b,periodInMinutes:b})):console.log("autoclear disabled")})};chrome.alarms.onAlarm.addListener(function(a){a&&"auto-clear-tasks"==a.name&&p&&(a=chrome.i18n.getMessage("statusScheduledAutoClear",[20]),console.log(a),chrome.runtime.sendMessage({cmd:"u_status",data:a,duration:9E3}),setTimeout(function(){p&&
(dy_bkg.clear_tasks(p,!1),dy_settings.set("autoclear_lasttime",Date.now()))},2E4))});dy_bkg.reset=function(){m();for(var a=0;a<dy_bkg.bg_tasks.length;++a)dy_engine.erase(dy_bkg.bg_tasks[a],!1,!0,!1);dy_bkg.bg_tasks.splice(0,dy_bkg.bg_tasks.length);var a=localStorage.ver1,b=localStorage.ver1_t;localStorage.clear();localStorage.ver1=a;localStorage.ver1_t=b;dy_store.clear(function(){chrome.runtime.reload()})};dy_bkg.isBusy=function(){return k.busy()};var k=function(){function a(){c=void 0;if(b.length){var d=
b[0];if(d.b)d.f(d.p.slice(d.idx,d.idx+d.bsz),d.extras);else for(var e=d.idx,f=e+d.bsz;e<f&&e<d.tsz;++e)d.f(d.p[e],d.extras);(d.idx+=d.bsz)>=d.tsz&&b.shift();b.length?c=setTimeout(a,b[0].iv):(chrome.runtime.sendMessage({cmd:"u_bgbusy",data:!1}),console.log("work queue empty"))}}var b=[],c;return{add:function(d,e,f,g,h,k){h=h||150;b.push({f:d,p:e,tsz:e.length,bsz:f,b:g,iv:h,idx:0,extras:k});c||(c=setTimeout(a,h),chrome.runtime.sendMessage({cmd:"u_bgbusy",data:!0}))},busy:function(){return void 0!=c||
0<b.length}}}()})();
