var dy_obj={version:1},dyport;dy_obj.host_name="com.downloady.k";var _msg_id=5,_max_msg_id=1E7;function get_msg_id(){++_msg_id>_max_msg_id&&(_msg_id=0);return _msg_id}var _msg_callbacks={};dy_obj.loaded=!1;
dy_obj.load=function(){try{dyport=chrome.runtime.connectNative(dy_obj.host_name),dyport.onMessage.addListener(function(b){console.log(JSON.stringify(b));switch(b.cmd){case "response":if(b._mid){var a=_msg_callbacks[b._mid];a&&a(b.data);delete _msg_callbacks[b._mid]}break;case "dyu_field":dyu_field(b.id,b.field,b.data);break;case "dyu_bits":dyu_bits(b.id,b.type,b.pos,b.len);break;case "dyu_task":dyu_task(b.id,b.task);break;case "dyu_progress":dyu_progress(b.data);break;case "dyprint":console.log(b.data)}}),
dyport.onDisconnect.addListener(function(){dy_obj.loaded=!1;dyport=null;chrome.runtime.lastError&&console.log(chrome.runtime.lastError.message);console.log("Cannot communicate with native cooperative program.")}),dy_obj.loaded=!0}catch(c){console.log(c)}return dy_obj.loaded};dy_obj.newt=function(c,b,a,d,e){dyport.postMessage({cmd:"new",id:c,url:b,referer:a,folder:d,threads:e});return!0};dy_obj.resume=function(c){dyport.postMessage({cmd:"resume",task:c});return!0};
dy_obj.stop=function(c,b){dyport.postMessage({cmd:"stop",id:c,stop_op:b})};dy_obj.config=function(c,b){dyport.postMessage({cmd:"config",field:c,value:b})};dy_obj.getVersion=function(c){var b={_mid:get_msg_id(),cmd:"ver"};_msg_callbacks[b._mid]=c;dyport.postMessage(b)};dy_obj.idle=function(c){var b={_mid:get_msg_id(),cmd:"idle"};_msg_callbacks[b._mid]=c;dyport.postMessage(b)};dy_obj.empty=function(c){var b={_mid:get_msg_id(),cmd:"empty"};_msg_callbacks[b._mid]=c;dyport.postMessage(b)};
dy_obj.browse=function(c,b){var a={_mid:get_msg_id(),cmd:"browse",def:c};_msg_callbacks[a._mid]=b;dyport.postMessage(a)};dy_obj.explore=function(c){dyport.postMessage({cmd:"explore",file:c})};dy_obj.exec=function(c){dyport.postMessage({cmd:"exec",file:c})};dy_obj.rename=function(c,b){dyport.postMessage({cmd:"rename",src:c,dst:b})};dy_obj.wake=function(c,b){dyport.postMessage({cmd:"wake",id:c,folder:b})};dy_obj.memr=function(){dyport.postMessage({cmd:"memr"})};
function dy_gettask(c){return task_by_id(c)}function update_progress(c,b){var a=task_by_id(c);if(a){a.time_elapsed+=cur_t-a._start_time;a._start_time=cur_t;a.speed=b-a.finished_bytes;a.finished_bytes=b;if(0<a.size){a.progress=a.finished_bytes/a.size*100;a.progress=Math.min(100,a.progress);var d=0.5*a.speed+0.5*a.finished_bytes/a.time_elapsed;a.time_remained=0>=d?362439:(a.size-a.finished_bytes)/d}chrome.extension.sendMessage({cmd:"u_prog",id:a.id,data:a})}}
function dyu_task(c,b){var a=task_by_id(c);if(a){a.size=b.size;a.blocksize=b.blocksize;a.blockcnt=b.blockcnt;a.single_thread=b.single_thread;b.etag&&(a.etag=b.etag);b.mime_type&&(a.mime_type=b.mime_type);b.eurl&&(a.eurl=b.eurl);b.last_modified&&(a.last_modified=b.last_modified);DYTask.reset(a);a.bits=new bitset(a.blockcnt);var d=dy_rules.match(a,!0);a.naming||(a.naming=d.naming);a.folder||(a.folder=d.folder,dy_obj.wake(c,a.folder));dy_pathman.touch(a.folder);chrome.extension.sendMessage({cmd:"u_task",
id:c,data:a})}}function dyu_progress(c){cur_t=Date.now()/1E3;for(var b=c.length>>1,a=0;a<b;++a)update_progress(c[a+a],c[a+a+1])}function dylog(c,b,a){console.log("bg_dylog: tid: "+c+", code: "+b+", type: "+a)}
function dyu_bits(c,b,a,d){var e=task_by_id(c);if(e){ismem=!0;switch(b){case DyShareEnums.TaskField.BITS_MEM:if(!e.bits_mem)if(e.bits&&e.bits.size_)e.bits_mem=new bitset(e.bits.size_);else return;e.bits_mem.set(a,d);break;case DyShareEnums.TaskField.BITS_DISK:if(e.bits){if(-2==a)e.bits.reset(),e.finished_bytes=e.finished_blocks=e.progress=0;else if(-1==a)e.bits.complete(),e.finished_bytes=e.size,e.finished_blocks=e.blockcnt,e.progress=100;else{b=e.bits.set(a,d);if(!b)return;e.finished_blocks+=b}ismem=
!1}else return;break;default:return}dy_bkg.dirtyBitsMan.set(c);chrome.extension.sendMessage({cmd:"u_bits",id:e.id,start:a,len:d,membits:ismem})}}
function dyu_field(c,b,a){var d=task_by_id(c);if(d){var e;switch(b){case DyShareEnums.TaskField.TEMP_FILE:d.temp_file=a;e="temp_file";break;case DyShareEnums.TaskField.MAX_THREADS:d.max_threads=a;e="active_threads";break;case DyShareEnums.TaskField.ACTIVE_THREADS:d.active_threads=a;e="active_threads";break;case DyShareEnums.TaskField.STATE:d.state=a;a==DyEnums.TaskState.FINISH&&(console.log("task finish, todo: rename file"),b=DYTask.render_full_path(d),b!=d.temp_file&&(console.log("task finish, rename: "+
d.temp_file+" ->"+b),dy_obj.rename(d.temp_file,b),d.temp_file=b));d.active_threads=0;d.finished_bytes=Math.min(d.size,d.finished_blocks*d.blocksize);d.progress=d.finished_bytes/d.size*100;d.bits_mem&&delete d.bits_mem;schedule();break;default:return}dy_bkg.dirtyTaskMan.set(c);e?chrome.extension.sendMessage({cmd:"u_field",id:d.id,field:e,data:a}):chrome.extension.sendMessage({cmd:"u_task",id:d.id,data:d})}};
