function RuleMan(){function r(a){return a.replace(/\[([^\]]+)\]/gi,function(a,c){var b=c?c.trim().toLowerCase():"";if(!0==l[b])throw"dy_rules.expand_exts: loop of link filter ["+b+"] detected";l[b]=!0;var d=s(b);delete l[b];if(!d)throw"dy_rules.expand_exts: ref link filter ["+b+"] not found";return"("+d+")"})}function s(a){for(var b=0;b<k.length;++b)if(k[b].int_name==a)try{return r(k[b].exts)}catch(c){console.log(c);break}return null}function t(){n=!0;q()}function u(){p=!0;q()}function q(){p&&(localStorage[DyStrings.Store.LinkFilters]=
JSON.stringify(k),p=!1);if(n){localStorage[DyStrings.Store.Rules]=JSON.stringify(b);for(var a=n=!1,f={},c=0,g=b.length;c<g;++c){for(var m=-1,h=0,e=d.length;h<e;h+=2)if(d[h]==b[c].id){m=h;f[b[c].id]=1;break}b[c].as_filter?-1==m&&(d.push(b[c].id),d.push(0),a=!0,f[b[c].id]=1):0<=m&&(d.splice(m,2),a=!0)}for(h=d.length-2;0<=h;h-=2)f[d[h]]||(d.splice(h,2),a=!0);a&&(localStorage[DyStrings.Store.DisplayFilters]=JSON.stringify(d));chrome.runtime.sendMessage({cmd:"u_filters",rebuild:a})}}var p=!0,n=!0,v=new bitset(500),
w={caption:chrome.i18n.getMessage("extsNew"),int_name:"",exts:"*.*",filter_links:!1},k=[{caption:chrome.i18n.getMessage("extsAudio"),int_name:"ext_audio",exts:"aac|aif|ape|flac|oga|opus|m3u|m4a|mid|midi|mp3|ra|wav|wma|weba",filter_links:!0},{caption:chrome.i18n.getMessage("extsVideo"),int_name:"ext_video",exts:"3gp|3g2|asf|avi|f4f|f4i|f4m|f4v|flv|h264|m4v|mkv|mov|mp4|mpg|ogg|ogv|qt|rm|rmvb|srt|ts|vob|webm|wmv",filter_links:!0},{caption:chrome.i18n.getMessage("extsImage"),int_name:"ext_image",exts:"bmp|cur|dds|exr|gif|ico|jpg|jpeg|pcx|pbm|pfm|pgm|ppm|png|psd|svg|tga|tif|tiff|webp",
filter_links:!0},{caption:chrome.i18n.getMessage("extsDocument"),int_name:"ext_doc",exts:"c|cfg|cpp|cs|css|csv|dat|doc|docx|h|hpp|ini|js|log|m|pdf|ppt|pptx|ps|py|rtf|sh|tex|torrent|txt|xls|xlsx",filter_links:!0},{caption:chrome.i18n.getMessage("extsArchive"),int_name:"ext_arch",exts:"7z|bin|cbr|cue|deb|dmg|gz|iso|mdf|pkg|rar|rpm|sitx|tar.gz|vcd|zip",filter_links:!0},{caption:chrome.i18n.getMessage("extsApp"),int_name:"ext_app",exts:"apk|app|bat|cgi|com|dll|exe|gadget|jar|msi|pif|sys",filter_links:!0},
{caption:chrome.i18n.getMessage("extsAll"),int_name:"ext_all",exts:"[ext_audio]|[ext_video]|[ext_image]|[ext_doc]|[ext_arch]|[ext_app]",filter_links:!1}],x={id:-1,int_name:"",condition:"true",as_filter:!1,caption:chrome.i18n.getMessage("ruleNew"),active:!1,folder:"",naming:"",post_action:""},e=1,b=[{id:e++,int_name:"r_recent",condition:"*time_add*>=[3_days_ago]",as_filter:!0,caption:chrome.i18n.getMessage("ruleRecent"),active:!1,folder:"",naming:"",post_action:"",init_indent:0},{id:e++,int_name:"r_downloading",
condition:"*state*!=[finished]&&*state*!=[interrupted]",as_filter:!0,caption:chrome.i18n.getMessage("ruleDownloading"),active:!1,folder:"",naming:"",post_action:"",init_indent:0},{id:e++,int_name:"r_done",condition:"*state*==[finished]",as_filter:!0,caption:chrome.i18n.getMessage("ruleFinished"),active:!1,folder:"",naming:"",post_action:"",init_indent:0},{id:e++,int_name:"r_done_audio",condition:"{r_done}&&*ext*.is([ext_audio])",as_filter:!0,caption:chrome.i18n.getMessage("ruleAudio"),active:!1,folder:"./music",
naming:"",post_action:"",init_indent:1},{id:e++,int_name:"r_done_video",condition:"{r_done}&&*ext*.is([ext_video])",as_filter:!0,caption:chrome.i18n.getMessage("ruleVideo"),active:!1,folder:"./videos",naming:"",post_action:"",init_indent:1},{id:e++,int_name:"r_done_image",condition:"{r_done}&&*ext*.is([ext_image])",as_filter:!0,caption:chrome.i18n.getMessage("ruleImage"),active:!1,folder:"./images",naming:"",post_action:"<file>",init_indent:1},{id:e++,int_name:"r_done_doc",condition:"{r_done}&&*ext*.is([ext_doc])",
as_filter:!0,caption:chrome.i18n.getMessage("ruleDocument"),active:!1,folder:"./docs",naming:"",post_action:"<file>",init_indent:1},{id:e++,int_name:"r_done_other",condition:"{r_done}&&!(*ext*.is([ext_audio])||*ext*.is([ext_video])||*ext*.is([ext_image])||*ext*.is([ext_doc]))",as_filter:!0,caption:chrome.i18n.getMessage("ruleOther"),active:!1,folder:"",naming:"",post_action:"",init_indent:1},{id:e++,int_name:"r_interrupted",condition:"*state*==[interrupted]",as_filter:!0,caption:chrome.i18n.getMessage("ruleInterrupted"),
active:!1,folder:"",naming:"",post_action:"",init_indent:0},{id:e++,active:!1,caption:chrome.i18n.getMessage("ruleSmallFiles"),int_name:"r_smallf",condition:"*size*>0&&*size*<kb(1024)",folder:"./small_files",naming:"",as_filter:!1,post_action:"<folder>"}],d=[],l={};return{is_prompt:function(a){return!0!=dy_settings.get("doneclick_rule")},internal_audio:"aac|aif|ape|flac|oga|opus|m3u|m4a|mid|midi|mp3|ra|wav|wma|weba",internal_video:"3gp|3g2|asf|avi|f4f|f4i|f4m|f4v|flv|h264|m4v|mkv|mov|mp4|mpg|ogg|ogv|qt|rm|rmvb|srt|ts|vob|webm|wmv",
internal_image:"bmp|cur|dds|exr|gif|ico|jpg|jpeg|pcx|pbm|pfm|pgm|ppm|png|psd|svg|tga|tif|tiff|webp",def_link_filter:w,def_rule:x,getLinkFilters:function(){return k},getRules:function(){return b},get_display_filters:function(){for(var a=[],f=0,c=d.length;f<c;f+=2)for(var g=0,e=b.length;g<e;++g)b[g].id==d[f]&&!0==b[g].as_filter&&a.push({id:b[g].id,caption:b[g].caption,filter:b[g].condition,indent:d[f+1]});return a},set_display_filters:function(a){d=a;localStorage[DyStrings.Store.DisplayFilters]=JSON.stringify(d)},
ref_rule:function(a){for(var f=0;f<b.length;++f)if(b[f].int_name==a)return b[f].condition;return null},ref_filter:function(a){l={};return s(a)},ref_filteri:function(a){l={};var b=null;if(0<=a&&a<k.length)try{b=r(k[a].exts)}catch(c){console.log(c)}return b},add_rule:function(a){a.id=v.lowest0(!0);b.push(a);t()},add_filter:function(a){k.push(a);u()},on_rules_change:t,on_filters_change:u,load:function(){var a=localStorage.getItem(DyStrings.Store.LinkFilters);a&&(k=JSON.parse(a));(a=localStorage.getItem(DyStrings.Store.Rules))&&
(b=JSON.parse(a));if(a=localStorage.getItem(DyStrings.Store.DisplayFilters))d=JSON.parse(a);else for(d=[],a=0;a<b.length;++a){var f=b[a];void 0!=f.init_indent&&(d.push(f.id),d.push(f.init_indent))}for(a=0;a<b.length;++a)v.set(b[a].id);p=n=!1},commit:q,match:function(a){for(var d=dy_settings.get("match_mode"),c={},g=0;g<b.length;++g)if(b[g].active&&dy_taskfilter.testOnce(a,b[g].condition))if(d==DyEnums.MatchMode.FIRST_MATCH){a=b[g];c.naming=a.naming;c.folder=a.folder;c.post_action=a.post_action;var e=
trim_str(c.folder);e&&(c.folder=e.replace(/^\./,dy_settings.get("def_folder")));break}else if(d==DyEnums.MatchMode.REPLACE){var h=trim_str(b[g].naming),e=trim_str(b[g].folder),k=trim_str(b[g].post_action);h&&(c.naming=h);e&&(c.folder=e.replace(/^\./,c.folder||dy_settings.get("def_folder")));k&&(c.post_action=k)}c.naming||(c.naming=dy_settings.get("def_naming"));c.folder||(c.folder=dy_settings.get("def_folder"));return c},def_matched:function(){return{naming:dy_settings.get("def_naming"),folder:dy_settings.get("def_folder")}}}}
var dy_rules=new RuleMan;
