var dy_settings={categorys:{general:{name:chrome.i18n.getMessage("titleOptionsGeneral"),sections:[{name:"Chrome",items:["override_cr","hide_cr_bar"]},{name:chrome.i18n.getMessage("optSectionTaskDefaults"),tip:chrome.i18n.getMessage("tipOptSectionTaskDefaults"),items:["def_task_folder","def_task_naming","def_threads","def_addtop","def_addpause"]},{name:chrome.i18n.getMessage("optSectionOneClick"),tip:chrome.i18n.getMessage("tipOptSectionOneClick"),items:["doneclick_rule"]},{name:chrome.i18n.getMessage("optSectionNetwork"),
items:["dy_max_con_tasks","dy_max_per_server"]},{name:chrome.i18n.getMessage("optSectionMisc"),items:["fnconflict","down_clipboard","clear_search","recycle_cancel"]}]},"interface":{name:chrome.i18n.getMessage("titleOptionsInterface"),sections:[{name:chrome.i18n.getMessage("chromesysLanguageSection"),description:chrome.i18n.getMessage("msgChromeI18nLanguage")+(chrome.i18n.getMessage("uilang").substr(0,2).toLowerCase()!=chrome.i18n.getUILanguage().substr(0,2).toLowerCase()?"<br>Oops, Chrono is not yet available in "+
(chrome.i18n.getMessage("uilangName")||"your language")+', please help us with <a target=_blank href="http://translate.chronodownloader.net">translation</a> :)':""),items:["_uilanguage"]},{name:chrome.i18n.getMessage("optSectionBehaviors"),items:["start_interrupted","slide_details_panel","dbclick_action"]},{name:chrome.i18n.getMessage("optSectionMenu"),items:["menu_d_dialog","menu_d_oneclick"]},{name:chrome.i18n.getMessage("optSectionPopup"),items:"poplist_showd_first poplist_clear_close poplist_slide_btns poplist_like_btns poplist_max_items poplist_remove_confirm".split(" ")},
{name:chrome.i18n.getMessage("optSectionNotifications"),items:"notify_oneclick notify_finish notify_error sound_finish sound_error notify_progress notify_large_preview notify_openman_scroll click_notify".split(" ")},{name:chrome.i18n.getMessage("optSectionMisc"),items:["badge_downnum","font_size"]}]},rules:{name:chrome.i18n.getMessage("titleOptionsRules"),sections:[{items:["match_mode","def_naming","def_folder"]}]}},items:{_uilanguage:{label:"",type:"button",buttonText:chrome.i18n.getMessage("chromesysChange"),
onclick:function(){chrome.tabs.create({url:"chrome://settings/languages"})}},fnconflict:{label:"When file name conflicts",type:"select",options:[chrome.i18n.getMessage("optOptionUniquify"),chrome.i18n.getMessage("optOptionOverwrite"),chrome.i18n.getMessage("optOptionPrompt"),chrome.i18n.getMessage("optOptionSkipPause"),chrome.i18n.getMessage("optOptionSkipCancel")],value:DyEnums.FnConflictAction.UNIQUIFY,i18n:"NameConflict"},def_task_folder:{label:chrome.i18n.getMessage("fieldFolder"),type:"string",
placeholder:chrome.i18n.getMessage("phraseAutomatic"),value:"",native_only:!0,tip:chrome.i18n.getMessage("tipOptItemDefFolder",["<def>"])},def_task_naming:{label:chrome.i18n.getMessage("fieldNaming"),type:"string",placeholder:chrome.i18n.getMessage("phraseAutomatic"),value:"",tip:chrome.i18n.getMessage("tipOptItemDefNaming",["<def>"])},def_threads:{label:chrome.i18n.getMessage("fieldThreads"),type:"int",native_only:!0,value:5,min:1,max:15},def_addtop:{label:chrome.i18n.getMessage("optionAddTop"),
type:"bool",value:!1},def_addpause:{label:"Add paused",type:"bool",value:!1,i18n:"DefAddPaused"},down_clipboard:{label:"Download URL from Clipboard",type:"bool",value:!0,i18n:"DownloadClipboard"},start_interrupted:{label:"Start Button also starts interrupted tasks",type:"bool",value:!1,i18n:"StartInterrupted"},override_cr:{label:"Override Chrome's original Downloads page",type:"bool",value:!0,changeEvent:function(a){dy_tabman.override(a)},i18n:"OverrideChrome"},hide_cr_bar:{label:"Hide Chrome's Downloads Shelf(Bar)",
type:"bool",value:!0,changeEvent:function(a){chrome.downloads.setShelfEnabled(!a)},i18n:"HideShelf"},slide_details_panel:{label:"Slide bottom panel when click on task",type:"bool",value:!0,i18n:"SlideDetailsPanel",tip:chrome.i18n.getMessage("tipOptItemSlideDetailsPanel")},recycle_cancel:{label:"Cancel the task when it's recycled",type:"bool",value:!1,i18n:"RecycleCancel"},clear_search:{label:"Clear search box when filter changes",type:"bool",value:!1,i18n:"ClearSearch"},menu_d_dialog:{label:"Download this link",
type:"bool",value:!0,changeEvent:function(a){dy_menuman.toggleDialog(a)},initEvent:function(a){this.changeEvent(a)},i18n:"MenuDialog"},menu_d_oneclick:{label:"Download the link with One-Click",type:"bool",value:!0,changeEvent:function(a){dy_menuman.toggleOneclick(a)},initEvent:function(a){this.changeEvent(a)},i18n:"MenuOneClick"},notify_error:{label:"When error occurs",type:"bool",value:!0,changeEvent:function(a){!1==a&&dy_notify.clear("terr_")},i18n:"NotifyError"},notify_finish:{label:"When download completes",
type:"bool",value:!0,changeEvent:function(a){!1==a&&dy_notify.clear("tfin_")},i18n:"NotifyFinish"},sound_finish:{label:"Play sound when download completes",type:"bool",value:!0,i18n:"SoundFinish"},sound_error:{label:"Play sound when error occurs",type:"bool",value:!0,i18n:"SoundError"},notify_oneclick:{label:"When adding One-Click download",type:"bool",value:!0,changeEvent:function(a){!1==a&&dy_notify.clear("task_")},i18n:"NotifyOneClick"},notify_progress:{label:"Show download progress",type:"bool",
value:!0,changeEvent:function(a){!1==a&&dy_notify.clear("task_",!0)},i18n:"NotifyProgress"},notify_large_preview:{label:"Show large preview for images",type:"bool",value:!1,i18n:"NotifyLargePreview"},click_notify:{label:"Clicking on a notification",type:"select",options:[chrome.i18n.getMessage("btnOpenManager"),chrome.i18n.getMessage("optOptionClearNotify"),chrome.i18n.getMessage("optOptionClearAllNotify")],value:DyEnums.ClickNotify.OPEN_MANAGER,i18n:"ClickNotify"},notify_openman_scroll:{label:chrome.i18n.getMessage("optItemOpenManScroll",
[chrome.i18n.getMessage("btnOpenManager")]),type:"bool",value:!1},msg_singlet:{label:"Notify when task is not resumable",type:"bool",value:!0},dbclick_action:{label:"Double-click on task",type:"select",options:[chrome.i18n.getMessage("optOptionDoNothing"),chrome.i18n.getMessage("optOptionStartPause"),chrome.i18n.getMessage("optOptionOpenFile"),chrome.i18n.getMessage("optOptionOpenFolder")],value:DyEnums.DbclickAction.OPEN_FILE,i18n:"DblClickAction"},doneclick_rule:{label:chrome.i18n.getMessage("phraseEnable"),
type:"bool",value:!0},badge_downnum:{label:"Show Downloading Number",type:"bool",value:!0,i18n:"BadgeDownloadNum",changeEvent:function(a){dy_bkg.showBadge(-1)}},font_size:{label:chrome.i18n.getMessage("chromesysFontSize"),type:"int",value:12,min:12,max:16,changeEvent:function(a){chrome.runtime.sendMessage({cmd:"font_size",data:a})}},poplist_max_items:{label:"Max Items",type:"int",value:15,min:1,max:50,i18n:"PopMaxItems"},poplist_showd_first:{label:"Show downloading tasks first",type:"bool",value:!0,
i18n:"PopShowDLFirst"},poplist_clear_close:{label:"Close after clear",type:"bool",value:!1,i18n:"PopClearClose"},poplist_slide_btns:{label:"Buttons slide-in animation",type:"bool",value:!0,i18n:"PopSlideButtons"},poplist_like_btns:{label:"Show social media button",type:"bool",value:!0,i18n:"PopLikeButtons"},dy_max_con_tasks:{label:"Concurrent downloads",type:"int",value:10,min:1,max:20,dyconfig:DyShareEnums.Config.CFG_INT_MAX_CONCURRENT_TASKS,i18n:"ConcurrentDownloads",changeEvent:function(a){dy_taskstarter.schedule()}},
dy_max_per_server:{label:"Downloads per server",type:"int",value:5,min:1,max:5,i18n:"DownloadsPerServer",changeEvent:function(a){dy_taskstarter.schedule()}},def_folder:{label:"Default folder",type:"string",value:"",native_only:!0,tip:chrome.i18n.getMessage("tipOptNoRuleMatch"),i18n:"DefFolder"},def_naming:{label:"Default Naming Mask",type:"string",value:"*name*.*ext*",emptyValue:"*name*.*ext*",tip:chrome.i18n.getMessage("tipOptNoRuleMatch"),i18n:"DefNaming"},match_mode:{label:"Match Mode",type:"select",
options:[chrome.i18n.getMessage("optOptionFirstMatch"),chrome.i18n.getMessage("optOptionReplace")],value:DyEnums.MatchMode.FIRST_MATCH,tip:chrome.i18n.getMessage("tipOptItemRuleMatchMode"),i18n:"RuleMatchMode"},tb_fit_cols:{type:"bool",value:!1},tb_sync_resize:{type:"bool",value:!1},tb_def_cols:{type:"string",value:'["state","name","progress","size","speed","active_threads","time_remained","url","time_add"]'},tb_sort_cols:{type:"string",value:'[{"field":"time_add","sortAsc":false}]'},tb_free_order:{type:"string",
value:"{}"},tip_rateshare:{type:"int",value:1,i18n:"msgRateShare"},tip_notifications:{type:"int",value:0,message:chrome.i18n.getMessage("tipmsgNotifications",[chrome.i18n.getMessage("titleOptions")+"\u00bb"+chrome.i18n.getMessage("titleOptionsInterface")+"\u00bb"+chrome.i18n.getMessage("optSectionNotifications")]),set_section:"interface"},tip_dblclick:{type:"int",value:0,message:chrome.i18n.getMessage("tipmsgDoubleClick",[chrome.i18n.getMessage("titleOptions")+"\u00bb"+chrome.i18n.getMessage("titleOptionsInterface")+
"\u00bb"+chrome.i18n.getMessage("optSectionBehaviors")]),set_section:"interface"},tip_slide:{type:"int",value:0,message:chrome.i18n.getMessage("tipmsgSlideDetailsPanel",[chrome.i18n.getMessage("titleOptions")+"\u00bb"+chrome.i18n.getMessage("titleOptionsInterface")+"\u00bb"+chrome.i18n.getMessage("optSectionBehaviors")]),set_section:"interface"},tip_taskfilter:{type:"int",value:0,message:chrome.i18n.getMessage("tipmsgTaskFilter",[chrome.i18n.getMessage("titleOptions")+"\u00bb"+chrome.i18n.getMessage("titleOptionsRules")]),
set_section:"rules"},tip_openmanager:{type:"int",value:0,message:chrome.i18n.getMessage("tipmsgOpenShortcut")},tip_grid:{type:"int",value:0,message:chrome.i18n.getMessage("tipmsgGridSelection")},tip_copyselurls:{type:"int",value:0,message:chrome.i18n.getMessage("tipmsgCopySelectedURLs")},tip_colfit:{type:"int",value:0,message:chrome.i18n.getMessage("tipmsgFitColumnWidth")},tip_fileaccess:{type:"int",value:0,message:chrome.i18n.getMessage("tipmsgFileAccess",["<em>"+chrome.i18n.getMessage("chromesysAllowFileAccess")+
"</em>"]),set_page:"chrome://extensions/?id="+chrome.runtime.id},pop_preview:{type:"bool",value:!0},pop_showsize:{type:"bool",value:!0},pop_content:{type:"int",value:0},pop_sniffer_hint:{type:"int",value:0},pop_clear_file:{type:"bool",value:!1},poplist_remove_confirm:{type:"select",value:DyEnums.PopRemoveItem.ASK,i18n:"PopDeleteAction",label:"Click 'Delete' button",options:[chrome.i18n.getMessage("optOptionRemList"),chrome.i18n.getMessage("optOptionRemFile"),chrome.i18n.getMessage("optOptionRemAsk")]},
bg_image_enable:{type:"bool",value:!1},bg_image_everset:{type:"bool",value:!1},bg_image_url:{type:"string",value:"../icons/bg/1.jpg"},bg_image_opacity:{type:"float",value:0.35,min:0,max:1},bg_image_blur:{type:"int",value:0,min:0,max:10},ui_grid_list:{type:"bool",value:!0},stat_lastactive:{type:"int",value:0},stat_lastbgimgtime:{type:"int",value:0},tip_translate:{type:"int",value:0},autoclear_type:{type:"string",value:"both"},autoclear_timer:{type:"int",value:-1},autoclear_lasttime:{type:"int",value:-1}},
load:function(){for(var a in dy_settings.items){var b=dy_settings.items[a];b.i18n&&(b.label=chrome.i18n.getMessage("optItem"+b.i18n));var c=localStorage["#"+a];if(void 0!=c)switch(b.type){case "bool":"true"==c?b.value=!0:"false"==c&&(b.value=!1);break;case "select":case "int":c=parseInt(c);isNaN(c)||c<b.min||c>b.max?console.log('load from storage, invalid value for "'+a+'"'):b.value=c;break;case "float":c=parseFloat(c);isNaN(c)||c<b.min||c>b.max?console.log('load from storage, invalid value for "'+
a+'"'):b.value=c;break;default:b.value=c}b.initEvent&&b.initEvent(b.value)}dy_rules.load();a=0;for(c=DyShareEnums.DyConfigItems.length;a<c;++a)(b=dy_settings.items[DyShareEnums.DyConfigItems[a]])&&dy_engine.config(b.dyconfig,b.value)},commit:function(){dy_rules.commit()},get_taskdef:function(){var a=dy_settings.get("def_task_naming");a&&"<def>"==a.toLowerCase()&&(a=dy_settings.get("def_naming"));var b=dy_settings.get("def_task_folder");b&&"<def>"==b.toLowerCase()&&(b=dy_settings.get("def_folder"));
dy_engine.is_native||(b="[Downloads Location]");return{naming:a,folder:b,threads:dy_settings.get("def_threads"),addtop:dy_settings.get("def_addtop")}},get:function(a){return(a=dy_settings.items[a])?""===a.value?void 0==a.emptyValue?"":a.emptyValue:a.value:null},set:function(a,b){var c=dy_settings.items[a];c&&(void 0==c.min||b>=c.min)&&(void 0==c.max||b<=c.max)&&(c.value=b,localStorage["#"+a]=b,c.changeEvent&&c.changeEvent(b),c.dyconfig&&dy_engine.config(c.dyconfig,c.value))},inc:function(a){var b=
dy_settings.items[a];if(b){var c=b.value?++b.value:1;b.value=c;localStorage["#"+a]=c;b.changeEvent&&b.changeEvent(c);b.dyconfig&&dy_engine.config(b.dyconfig,b.value)}}};
