var dy_poplist=null,dy_popsniffer=null,bkg_page=chrome.extension.getBackgroundPage(),dy_bkg=bkg_page.dy_bkg,dy_settings=bkg_page.dy_settings,dy_rules=bkg_page.dy_rules,dy_taskfilter=bkg_page.dy_taskfilter,dy_tabman=bkg_page.dy_tabman,dy_engine=bkg_page.dy_engine,tab_url="",tab_id=-1;
(function(){function h(a,b,d){a||(a=document.getElementsByTagName("HEAD").item(0));var c=document.createElement("script");c.type="text/javascript";c.src=b;c.onload=c.onreadystatechange=d;a.appendChild(c)}function e(a,b){if(a&&a.length)for(var d=0,c=document.getElementsByTagName("HEAD").item(0),f=function(){var c=this.readyState;this.loaded||c&&"loaded"!=c&&"complete"!=c||(this.loaded=1,++d,d==a.length&&b&&b())},g=0;g<a.length;g++)h(c,a[g],f)}function n(){document.body.ondragstart="return false;";
document.body.ondrop="return false;";document.oncontextmenu=function(a){var b=a.target.nodeName.toLowerCase();if("input"!=b&&"textarea"!=b||a.target.disabled)return!1};$("#btn_manager").click(function(a){1==dy_settings.get("pop_content")?dy_tabman.open_ui():$("#dlist_wrap").hasClass("dlist_empty")||($("#cb_clear_file").prop("checked",dy_settings.get("pop_clear_file")),$(this).dropdown("show"),a.stopPropagation())});$("#btn_list").click(function(){$(".inner-loading-overlay").show();var a=dy_settings.get("pop_content"),
a=0==a?1:0;dy_settings.set("pop_content",a);1==a?(k(!0),chrome.browserAction.setTitle({title:chrome.i18n.getMessage("tipBrowserAction")})):(l(!0),chrome.browserAction.setTitle({title:chrome.i18n.getMessage("extName")}));$(this).hasClass("blink-anim")&&($(this).removeClass("blink-anim"),dy_settings.set("pop_sniffer_hint",1))});$(".dropdown").on("show",function(a,b){$("#tot_wrap").addClass("not-clickable")}).on("hide",function(a,b){$("#tot_wrap").removeClass("not-clickable")});0<dy_settings.get("tip_rateshare")&&
dy_settings.get("poplist_like_btns")&&$.get("https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fchrome.google.com%2Fwebstore%2Fdetail%2Fchrono-download-manager%2Fmciiogijehkdemklbdcbfkefimifhecn&width=90&layout=button_count&action=like&show_faces=false&height=21",function(){$("#fb_span").html('<iframe id="fb_frame" allowTransparency="true" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:90px; height:21px;" src="https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fchrome.google.com%2Fwebstore%2Fdetail%2Fchrono-download-manager%2Fmciiogijehkdemklbdcbfkefimifhecn&width=90&layout=button_count&action=like&show_faces=false&height=21"></iframe>')}).error(function(){});
1==dy_settings.get("pop_content")?k(!1):l(!1)}function l(a){function b(){$("#tot_wrap").removeClass("wider");if(dy_poplist)$("#wrap_dlist").show("slide",{direction:"left"},300,dy_poplist.init);else{var b=0,c=function(){++b;2==b&&(dy_poplist.setup(),dy_poplist.init())};a?$("#wrap_dlist").show("slide",{direction:"left"},300,c):($("#wrap_dlist").show(),++b);e(p,c)}$("#sniffer_title").hide()}dy_bkg.popup_dlist_open=!0;dy_bkg.popup_sniffer_tabid=-1;bkg_page.dy_notify.clear("task_");a?($("#btn_list").attr("title",
chrome.i18n.getMessage("tipBtnPopSniffer")).find("img").attr("src","../icons/pop/scan.png"),$("#btn_manager").attr("title",chrome.i18n.getMessage("tipBtnClear")).find("img").attr("src","../icons/clear.png"),dy_popsniffer&&dy_popsniffer.cleanup(),$("#wrap_sniffer").hide("slide",{direction:"right"},300,b)):b()}function k(a){function b(){try{if(validateURL(tab_url)&&!1==m.test(tab_url)){$("#cannot_sniffer").hide();$("#can_sniffer").show();$("#tot_wrap").addClass("wider");if(dy_popsniffer)$("#wrap_sniffer").show("slide",
{direction:"right"},300,function(){dy_popsniffer.init(tab_id)});else{var b=0,c=function(){++b;2==b&&(dy_popsniffer.setup(),dy_popsniffer.init(tab_id))};a?$("#wrap_sniffer").show("slide",{direction:"right"},300,c):($("#wrap_sniffer").show(),++b);e(q,c)}$("#sniffer_title").fadeIn()}else $("#can_sniffer").hide(),$("#cannot_sniffer").show(),$("#wrap_sniffer").show("slide",{direction:"right"},300),$("#tot_wrap").removeClass("wider")}catch(f){console.log(f)}}dy_bkg.popup_sniffer_tabid=tab_id;dy_bkg.popup_dlist_open=
!1;a?($("#btn_list").attr("title",chrome.i18n.getMessage("tipBtnPopList")).find("img").attr("src","../icons/pop/list.png"),$("#btn_manager").attr("title",chrome.i18n.getMessage("btnOpenManager")).find("img").attr("src","../icons/pop/table.png"),dy_poplist&&dy_poplist.cleanup(),$("#wrap_dlist").hide("slide",{direction:"left"},200,b)):b()}function r(){var a,b,d,c,f=document.getElementById("cannot_sniffer"),g=document.getElementById("can_sniffer"),e=document.getElementById("tot_wrap"),h=document.getElementById("wrap_sniffer"),
k=document.getElementById("wrap_dlist");1==dy_settings.get("pop_content")?(a="../icons/pop/list.png",b="../icons/pop/table.png",d=chrome.i18n.getMessage("tipBtnPopList"),c=chrome.i18n.getMessage("btnOpenManager"),validateURL(tab_url)&&!1==m.test(tab_url)?(g.style.display="block",e.className="wider"):(f.style.display="block",document.getElementById("sniffer_title").style.display="none"),h.style.display="block"):(!dy_settings.get("pop_sniffer_hint")&&validateURL(tab_url)&&(document.getElementById("btn_list").className=
"blink-anim"),a="../icons/pop/scan.png",b="../icons/clear.png",d=chrome.i18n.getMessage("tipBtnPopSniffer"),c=chrome.i18n.getMessage("tipBtnClear"),k.style.display="block",document.getElementById("sniffer_title").style.display="none");document.getElementById("btn_list").title=d;document.getElementById("btn_manager").title=c;document.querySelector("#btn_list img").src=a;document.querySelector("#btn_manager img").src=b;do_i18n()}var p=["../libs/jquery-dropdown/jquery.dropdown.js","../libs/jquery-powertip/jquery.powertip.js",
"../com/uihelper.js","pop_list.js"],q="../libs/slickgrid/slick.gridc.js ../libs/slickgrid/slick.dataview.js ../libs/slickgrid/plugins/slick.checkboxselectcolumn.js ../libs/jquery.numeric.js ../com/uihelper.js pop_sniffer.js".split(" ");window.onunload=function(){dy_bkg.popup_sniffer_tabid=-1;dy_bkg.popup_dlist_open=!1;bkg_page.console.log("popout")};var m=/.*((chrome.google.com)|(www.google.com\/chrome))\/.*/;window.addEventListener("load",function(){chrome.tabs.query({currentWindow:!0,active:!0},
function(a){a&&a.length&&(tab_url=a[0].url,tab_id=a[0].id);r();e(["../libs/jquery-2.1.0.min.js"],function(){h(null,"../libs/jqueryui/jquery-ui.slide.min.js",n)})})})})();
