dy_poplist={};
(function(a){function m(e){if(e.target&&"powerTip"!=e.target.id&&0==a("#powerTip").has(e.target).length)a.powerTip.hide();else a(document).one("click",m)}function l(){return h?h.data("task"):null}function k(e){var b=a("#dlist_wrap");a("#dlist_action_container").stop(!0,!0).hide().insertAfter(b);a("#dlist_btn_folder").hide().insertAfter(b);a("#dlist_btn_copy").hide().insertAfter(b);!0==e&&h?(h.remove(),h=null):h&&h.removeClass("ditem_hover");h=null}function n(e){!1!=e&&k();e=dy_settings.get("poplist_max_items");e=
dy_bkg.getRecents(e);for(var b=dy_bkg.getDatas(),c=a("#dlist_wrap"),v=e.length,h="",f=0;f<v;++f)h+='<div class="ditem_content">&nbsp</div>';c.toggleClass("dlist_empty",0==v);c.html(h);c=c.find("div");for(f=0;f<v;++f)a(c[f]).dListItem({task:b[e[f]]});a("#wrap_list_loading").hide()}function s(a,b,c){switch(a.cmd){case "pop_close":p!=a.srcid&&window.close();break;case "u_new":n();(c=f[a.scroll_id])&&flash_element_bg(c,"rgb(240, 240, 115)");break;case "u_confirm":c(confirm(a.data));break;case "u_accept":chrome.downloads.acceptDanger(a.crid,
function(){});c(!0);break;case "u_clear":"pop"!=a.src&&n();break;case "u_prog":for(b=0;b<a.ids.length;++b)(c=f[a.ids[b]])&&(c=c.data("dListItem"))&&c.updateProgress();break;case "u_tasks":for(b=0;b<a.ids.length;++b)(c=f[a.ids[b]])&&(c=c.data("dListItem"))&&c.refresh();break;case "u_tasks_by_field":for(b=0;b<a.ids.length;++b)(c=f[a.ids[b]])&&(c=c.data("dListItem"))&&c.updateField(a.field);break;case "u_fields":c=f[a.id];if(!c)break;if(c=c.data("dListItem"))for(b=0;b<a.fields.length;++b)c.updateField(a.fields[b])}}
var p=-1,x=dy_settings.get("poplist_slide_btns"),h=null,f={};dy_poplist.cleanup=function(){chrome.runtime.onMessage.removeListener(s);a("#dlist_wrap").removeClass("bottom_shadow top_shadow both_shadow")};dy_poplist.init=function(){function a(){dy_engine.numDownloading()&&chrome.runtime.sendMessage({cmd:"poll_progress"});setTimeout(a,250)}h=null;f={};p=Date.now();n(!1);chrome.runtime.sendMessage({cmd:"pop_close",srcid:p});chrome.runtime.onMessage.addListener(s);a()};dy_poplist.setup=function(){var e=
a("#dlist_wrap");e.mouseleave(function(c){a("#powerTip").is(":visible")||k()});a("#dlist_btn_folder").click(function(){var a=l();a&&dy_engine.explore(a,function(a,c){a||alert(c)})});a("#dlist_btn_copy").click(function(){var a=l();a&&writeClipboard(a.url)});a("#dlist_btn_start").click(function(){var a=l();a&&(a.state==DyEnums.TaskState.PAUSE?dy_bkg.start_tasks([a]):dy_bkg.stop_tasks([a]))});a("#dlist_btn_restart").click(function(){var a=l();a&&dy_bkg.restart_tasks([a])});a("#dlist_btn_remove").data("powertipjq",
function(){return a("#remove_confirm")});a(document).on("click","#btn_rem_list,#btn_rem_file",function(){var c="btn_rem_file"==this.id;a.powerTip.hide();var b=l();delete f[b.id];dy_bkg.remove_task_completely(b,c,"pop");k(!0);a("#cb_no_confirm").prop("checked")&&dy_settings.set("poplist_remove_confirm",c?DyEnums.PopRemoveItem.FILE:DyEnums.PopRemoveItem.LIST)});a.fn.powerTip.smartPlacementLists.sw="sw nw w s n ne sw".split(" ");a("#dlist_btn_remove").powerTip({placement:"sw",smartPlacement:!0,mouseOnToPopup:!0,
fadeInTime:80,closeDelay:9999E4,manual:!0});a("#dlist_btn_remove").click(function(c){var b=l();if(b){var e=dy_settings.get("poplist_remove_confirm");e==DyEnums.PopRemoveItem.LIST?(delete f[b.id],dy_bkg.remove_task_completely(b,!1,"pop"),k(!0)):e==DyEnums.PopRemoveItem.FILE?(delete f[b.id],dy_bkg.remove_task_completely(b,!0,"pop"),k(!0)):b.exists&&b.state!=DyEnums.TaskState.DOWNLOAD&&b.state!=DyEnums.TaskState.QUEUE?a("#powerTip").is(":visible")||(a("#cb_no_confirm").prop("checked",!1),a.powerTip.show(a("#dlist_btn_remove")),
c.stopPropagation(),a(document).one("click",m)):(delete f[b.id],dy_bkg.remove_task_completely(b,!0,"pop"),k(!0))}});e.scrollTop()+e.innerHeight()<e[0].scrollHeight&&e.addClass("bottom_shadow");var b=null;e.scroll(function(){b?(clearTimeout(b),b=null):e.addClass("scroll-ing");b=setTimeout(function(){e.removeClass("scroll-ing");b=null;a(".ditem_content:hover").data("dListItem").focus()},200);a("#powerTip").is(":visible")&&(a.powerTip.hide(),a(document).off("click",m));var c=a(this).scrollTop(),f=a(this).innerHeight();
a(this).removeClass("both_shadow bottom_shadow top_shadow");c+f<this.scrollHeight?0<c?a(this).addClass("both_shadow"):a(this).addClass("bottom_shadow"):0<c&&a(this).addClass("top_shadow")});a("#dlist_btn_manager").click(function(){dy_tabman.open_ui()});a("#cb_clear_file").change(function(){dy_settings.set("pop_clear_file",this.checked)});a("#btn_clear_finished").click(function(){var a=dy_settings.get("pop_clear_file");dy_bkg.clear_tasks(function(a){return a.state==DyEnums.TaskState.FINISH},a);dy_settings.get("poplist_clear_close")&&
window.close()});a("#btn_clear_fmissing").click(function(){dy_bkg.clear_tasks(function(a){return a.state==DyEnums.TaskState.FINISH&&!a.exists},!1);dy_settings.get("poplist_clear_close")&&window.close()});a("#btn_clear_failed").click(function(){var a=dy_settings.get("pop_clear_file");dy_bkg.clear_tasks(function(a){return a.state==DyEnums.TaskState.INTERRUPTED},a);dy_settings.get("poplist_clear_close")&&window.close()});a("#btn_clear_all").click(function(){var a=dy_settings.get("pop_clear_file");dy_bkg.clear_tasks(function(a){return a.state==
DyEnums.TaskState.FINISH||a.state==DyEnums.TaskState.INTERRUPTED},a);dy_settings.get("poplist_clear_close")&&window.close()})};var y=RegExp("^("+imgtag_formats+")$","i"),z=chrome.i18n.getMessage("tipBtnOpenFile"),t=null,A=function(e,b){function c(){var a="";if(dy_bkg.file_access&&d.state==DyEnums.TaskState.FINISH&&d.full_path&&d.exists){var b=xtractFile(d.file_ext||file_from_url(d.url));b.fext&&y.test(b.fext)&&(a="file:///"+d.full_path)}a||(a=d.iconURL32||DyStrings.Icons.Unknown32);g.find(".ditem_icon img")[0].src=
a}function f(){var a=0.5*Math.PI*d.progress;g.find(".radial-progress-bar").attr("stroke-dasharray",a+",200")}function l(a){var b=a[0];b.offsetWidth<b.scrollWidth?a.attr("title",a.text()):a.removeAttr("title")}function k(){var a=DYTask.render_UI_name(d);q.text(a);l(q);d.state==DyEnums.TaskState.FINISH&&d.exists?q.addClass("title_openable").attr("title",z):q.removeClass("title_openable").removeAttr("title")}function m(){l(g.find(".ditem_src_url").text(trimLen(d.url,256,"...")))}function n(a){if(0>=
a.size)return 0<a.finished_bytes?get_byte_string(a.finished_bytes):chrome.i18n.getMessage("phraseUnknownSize");var b=get_byte_string(a.size);return a.state==DyEnums.TaskState.FINISH||a.state==DyEnums.TaskState.INTERRUPTED?b:chrome.i18n.getMessage("statusDownloadedSize",[get_byte_string(a.finished_bytes),b])}function p(){var a=d.state;d.state!=DyEnums.TaskState.FINISH||d.exists||(a=DyEnums.TaskState.FILEMISS);a='<span class="ditem_state"><img width=20 height=20 title="'+DyStrings.TaskState[a]+'" src="'+
DyStrings.TaskStateIcon[a]+'"/></span>';if(d.state==DyEnums.TaskState.DOWNLOAD){var b=get_byte_string_(d.speed,"/s"),c=get_readable_duration(d.time_remained),b=b+" - "+n(d)+" | "+chrome.i18n.getMessage("statusTimeLeft",[c]);s.html(a+"<span>"+b+"</span>")}else b="<span"+(d.error_str?' class="error_msg"':"")+">"+(d.error_str?DyStrings.Error[d.error_str]||d.error_str:n(d))+"</span>",s.html(a+b+'<span class="time_add">'+get_readable_date(d.time_add)+"</span>")}function w(){var b=a("#dlist_btn_start"),
c=g.find(".radial-progress");if(d.state==DyEnums.TaskState.FINISH||d.state==DyEnums.TaskState.INTERRUPTED)g.removeClass("shorter"),b.addClass("force_hide"),c.remove();else{var e=d.state==DyEnums.TaskState.DOWNLOAD||0<d.progress;d.state==DyEnums.TaskState.PAUSE?b.css("background-image",'url("../icons/toolbar/start.png")'):b.css("background-image",'url("../icons/toolbar/pause.png")');g.addClass("shorter");b.removeClass("force_hide");e&&!c.length?g.find(".ditem_icon").prepend('<div class="radial-progress">\t\t\t\t\t\t\t<svg>\t\t\t\t\t\t\t  <circle class="radial-progress-cover"></circle>\t\t\t\t\t\t\t  <circle class="radial-progress-bar" stroke-dasharray="'+
0.5*Math.PI*d.progress+',200"></circle>\t\t\t\t\t\t\t</svg>\t\t\t\t\t\t</div>'):!e&&c.length&&c.remove()}r.updateProgress()}function u(b){h==g||b&&a("#powerTip").is(":visible")||(h&&h.removeClass("ditem_hover"),h=g,g.addClass("ditem_hover"),w(),b=a("#dlist_action_container").stop(!0,!0).hide().appendTo(g),x?b.show("slide",{direction:"right"},150):b.show(),d.state==DyEnums.TaskState.FINISH&&d.exists?a("#dlist_btn_folder").hide().insertAfter(g.find(".ditem_title")).show():a("#dlist_btn_folder").hide().insertAfter(g.find(".ditem_title")),
a("#dlist_btn_copy").hide().insertAfter(g.find(".ditem_src_url")).show())}var g=a(e),d=b.task,r=this;g.html('<div class="ditem_icon"><img class="centerme"/>                    </div>                    <div class="ditem_details">                        <div><span class="ditem_ellipsisable ditem_title"></span></div>                        <div><span class="ditem_ellipsisable ditem_src_url"></span></div>                        <div><span class="ditem_stat"></span></div>                    </div>');
g.addClass("ditem_content");r.updateField=function(a){switch(a){case "iconURL32":c();break;case "naming":k();break;case "url":m();break;case "state":w();k();break;case "size":p();break;case "progress":f()}};r.updateProgress=function(){p();f()};r.refresh=function(){k();m();c();w()};var q=g.find(".ditem_title");q.click(function(){q.hasClass("title_openable")&&dy_engine.exec(d,function(a,b){a||alert(b)})});var s=g.find(".ditem_stat");r.refresh();r.focus=u;g.mouseenter(function(){t&&(clearTimeout(t),
t=null);g.parent().hasClass("scroll-ing")?t=setTimeout(function(){u(!0)},200):u(!0)}).click(function(){u(!1)})};a.fn.dListItem=function(e){return this.each(function(){var b=a(this);if(!b.data("dListItem")){var c=new A(this,e);b.data("dListItem",c);b.data("task",e.task);f[e.task.id]=b}})}})(jQuery);
